Repository OCA/l10n-italy, pull requests merged in 2018-08, with the labels that each got.

#521 [10.0] Fix l10n_it_fiscalcode performance migration
  l10n_it_fiscalcode/migrations/10.0.1.0.1/post-migrate.py
Labels: needs fixing

#571 IMP l10n_it_fatturapa_out: showing the XML field that is failing
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#355 [IMP] Different transportation method error string
  l10n_it_ddt/wizard/add_picking_to_ddt.py
Labels: 10.0
