Repository OCA/l10n-italy, pull requests merged in 2018-11, with the labels that each got.

#618 [10.0][FIX] l10n_it_fatturapa_out_ddt: wizard popup
  l10n_it_fatturapa_out_ddt/__manifest__.py
  l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa_view.xml
Labels: work in progress

#644 IMP global README with translations info
  README.md
Labels: needs review

#634 [11.0] mig l10n_it_fiscal_payment_term
  l10n_it_fiscal_payment_term/README.rst
  l10n_it_fiscal_payment_term/__init__.py
  l10n_it_fiscal_payment_term/__manifest__.py
  l10n_it_fiscal_payment_term/data/fatturapa_data.xml
  l10n_it_fiscal_payment_term/i18n/it.po
  l10n_it_fiscal_payment_term/i18n/l10n_it_fiscal_payment_term.pot
  l10n_it_fiscal_payment_term/models/__init__.py
  l10n_it_fiscal_payment_term/models/account.py
  l10n_it_fiscal_payment_term/readme/CONFIGURE.rst
  l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_payment_term/readme/DESCRIPTION.rst
  l10n_it_fiscal_payment_term/security/ir.model.access.csv
  l10n_it_fiscal_payment_term/static/description/index.html
  l10n_it_fiscal_payment_term/views/account_view.xml
Labels: needs review

#649 FIX global README link
  README.md
Labels: needs review

#648 [12.0] mig l10n_it_fiscal_payment_term
  l10n_it_fiscal_payment_term/README.rst
  l10n_it_fiscal_payment_term/__init__.py
  l10n_it_fiscal_payment_term/__manifest__.py
  l10n_it_fiscal_payment_term/data/fatturapa_data.xml
  l10n_it_fiscal_payment_term/i18n/it.po
  l10n_it_fiscal_payment_term/i18n/l10n_it_fiscal_payment_term.pot
  l10n_it_fiscal_payment_term/models/__init__.py
  l10n_it_fiscal_payment_term/models/account.py
  l10n_it_fiscal_payment_term/readme/CONFIGURE.rst
  l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_payment_term/readme/DESCRIPTION.rst
  l10n_it_fiscal_payment_term/security/ir.model.access.csv
  l10n_it_fiscal_payment_term/static/description/index.html
  l10n_it_fiscal_payment_term/views/account_view.xml
Labels: needs review

#645 [12.0] mig l10n_it_ipa
  l10n_it_ipa/README.rst
  l10n_it_ipa/__init__.py
  l10n_it_ipa/__manifest__.py
  l10n_it_ipa/i18n/am.po
  l10n_it_ipa/i18n/ar.po
  l10n_it_ipa/i18n/bg.po
  l10n_it_ipa/i18n/bs.po
  l10n_it_ipa/i18n/ca.po
  l10n_it_ipa/i18n/cs.po
  l10n_it_ipa/i18n/da.po
  l10n_it_ipa/i18n/de.po
  l10n_it_ipa/i18n/el_GR.po
  l10n_it_ipa/i18n/en_GB.po
  l10n_it_ipa/i18n/es.po
  l10n_it_ipa/i18n/es_AR.po
  l10n_it_ipa/i18n/es_CR.po
  l10n_it_ipa/i18n/es_EC.po
  l10n_it_ipa/i18n/es_MX.po
  l10n_it_ipa/i18n/es_VE.po
  l10n_it_ipa/i18n/et.po
  l10n_it_ipa/i18n/fi.po
  l10n_it_ipa/i18n/fr.po
  l10n_it_ipa/i18n/fr_CA.po
  l10n_it_ipa/i18n/fr_CH.po
  l10n_it_ipa/i18n/gl.po
  l10n_it_ipa/i18n/hr.po
  l10n_it_ipa/i18n/hr_HR.po
  l10n_it_ipa/i18n/hu.po
  l10n_it_ipa/i18n/it.po
  l10n_it_ipa/i18n/ja.po
  l10n_it_ipa/i18n/l10n_it_ipa.pot
  l10n_it_ipa/i18n/lt.po
  l10n_it_ipa/i18n/lv.po
  l10n_it_ipa/i18n/mk.po
  l10n_it_ipa/i18n/mn.po
  l10n_it_ipa/i18n/nb.po
  l10n_it_ipa/i18n/nb_NO.po
  l10n_it_ipa/i18n/nl.po
  l10n_it_ipa/i18n/nl_BE.po
  l10n_it_ipa/i18n/pl.po
  l10n_it_ipa/i18n/pt.po
  l10n_it_ipa/i18n/pt_BR.po
  l10n_it_ipa/i18n/pt_PT.po
  l10n_it_ipa/i18n/ro.po
  l10n_it_ipa/i18n/ru.po
  l10n_it_ipa/i18n/sl.po
  l10n_it_ipa/i18n/sr@latin.po
  l10n_it_ipa/i18n/sv.po
  l10n_it_ipa/i18n/th.po
  l10n_it_ipa/i18n/tr.po
  l10n_it_ipa/i18n/vi.po
  l10n_it_ipa/i18n/zh_CN.po
  l10n_it_ipa/i18n/zh_TW.po
  l10n_it_ipa/model/__init__.py
  l10n_it_ipa/model/partner.py
  l10n_it_ipa/readme/CONTRIBUTORS.rst
  l10n_it_ipa/readme/DESCRIPTION.rst
  l10n_it_ipa/static/description/icon.png
  l10n_it_ipa/static/description/index.html
  l10n_it_ipa/view/partner_view.xml
Labels: needs review

#491 [10.0] FIX + IMP Conto contabile corretto e gestione nota credito fornitore
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax_payment/models/withholding_tax.py
Labels: needs review

#629 [12.0] mig l10n_it_account
  l10n_it_account/README.rst
  l10n_it_account/__init__.py
  l10n_it_account/__manifest__.py
  l10n_it_account/i18n/es_AR.po
  l10n_it_account/i18n/it.po
  l10n_it_account/i18n/l10n_it_account.pot
  l10n_it_account/i18n/sl.po
  l10n_it_account/models/__init__.py
  l10n_it_account/models/account_tax.py
  l10n_it_account/readme/CONTRIBUTORS.rst
  l10n_it_account/readme/CREDITS.rst
  l10n_it_account/readme/DESCRIPTION.rst
  l10n_it_account/reports/account_reports_view.xml
  l10n_it_account/static/description/icon.png
  l10n_it_account/static/description/index.html
  l10n_it_account/static/src/css/l10n_it_account.css
  l10n_it_account/views/account_menuitem.xml
  l10n_it_account/views/account_setting.xml
  l10n_it_account/views/partner_view.xml
  l10n_it_account/views/product_view.xml
  l10n_it_account/views/res_config_settings_views.xml
  oca_dependencies.txt
Labels: needs review

#657 IMP l10n_it_fatturapa codice destinatario default 0000000
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/partner.py
Labels: approved, needs review

#670 [IMP] l10n_it_ddt: avoid print useless time part of field 'Date'
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/views/report_ddt.xml
Labels: approved

#669 12.0 mig l10n it abicab
  l10n_it_abicab/README.rst
  l10n_it_abicab/__init__.py
  l10n_it_abicab/__manifest__.py
  l10n_it_abicab/i18n/de.po
  l10n_it_abicab/i18n/it.po
  l10n_it_abicab/i18n/l10n_it_abicab.pot
  l10n_it_abicab/i18n/nb_NO.po
  l10n_it_abicab/i18n/sl.po
  l10n_it_abicab/models/__init__.py
  l10n_it_abicab/models/abicab.py
  l10n_it_abicab/readme/CONTRIBUTORS.rst
  l10n_it_abicab/readme/DESCRIPTION.rst
  l10n_it_abicab/static/description/index.html
  l10n_it_abicab/tests/__init__.py
  l10n_it_abicab/tests/test_abicab.py
  l10n_it_abicab/views/abicab_view.xml
Labels: approved

#675 Remove en.po as it should not be there.
  l10n_it_ddt/i18n/en.po
Labels: needs review

#653 [12.0] mig l10n_it_withholding_tax
  l10n_it_withholding_tax/README.rst
  l10n_it_withholding_tax/__init__.py
  l10n_it_withholding_tax/__manifest__.py
  l10n_it_withholding_tax/i18n/it.po
  l10n_it_withholding_tax/i18n/l10n_it_withholding_tax.pot
  l10n_it_withholding_tax/models/__init__.py
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax/readme/DESCRIPTION.rst
  l10n_it_withholding_tax/readme/USAGE.rst
  l10n_it_withholding_tax/security/ir.model.access.csv
  l10n_it_withholding_tax/security/security.xml
  l10n_it_withholding_tax/static/description/index.html
  l10n_it_withholding_tax/static/img/fattura-fornitore-768x517.png
  l10n_it_withholding_tax/static/img/foto-3-1-1024x505.png
  l10n_it_withholding_tax/static/img/ritenuta-acconto-odoo-codifica-768x457.png
  l10n_it_withholding_tax/static/src/xml/account_payment.xml
  l10n_it_withholding_tax/tests/__init__.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
  l10n_it_withholding_tax/views/account.xml
  l10n_it_withholding_tax/views/withholding_tax.xml
Labels: needs review

#674 [FIX] change FatturaPA into E-invoice
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/models/account.py
  l10n_it_fatturapa_out/models/attachment.py
  l10n_it_fatturapa_out/readme/CONFIGURE.rst
  l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out/readme/USAGE.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/views/account_view.xml
  l10n_it_fatturapa_out/views/attachment_view.xml
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#682 l10n_it_fatturapa_pec: check possible fetch errors and track them
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/__init__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
Labels: approved, needs review

#671 [10.0] add TD12 document type
  l10n_it_fiscal_document_type/data/fiscal.document.type.csv
Labels: approved

#677 [FIX] fatturapa translation source strings
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa/readme/CONFIGURE.rst
  l10n_it_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa/readme/DESCRIPTION.rst
  l10n_it_fatturapa/readme/INSTALL.rst
  l10n_it_fatturapa/static/description/index.html
  l10n_it_fatturapa/views/account_view.xml
  l10n_it_fatturapa/views/company_view.xml
  l10n_it_fatturapa/views/partner_view.xml
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/models/partner.py
  l10n_it_fatturapa_in/readme/CONFIGURE.rst
  l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in/readme/INSTALL.rst
  l10n_it_fatturapa_in/readme/USAGE.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.xml
  l10n_it_fatturapa_in/tests/data/IT03638121008_X11111.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_005.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_006.XML
  l10n_it_fatturapa_in/tests/data/IT05979361218_009.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/tests/data/CHE114993395IVA_00007.xml
  l10n_it_fatturapa_out/tests/data/IT03297040366_00005.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00003.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00004.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00006.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00008.xml
  l10n_it_fatturapa_out/views/account_view.xml
  l10n_it_fatturapa_out_ddt/README.rst
  l10n_it_fatturapa_out_ddt/__manifest__.py
  l10n_it_fatturapa_out_ddt/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_ddt/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_ddt/readme/USAGE.rst
  l10n_it_fatturapa_out_ddt/static/description/index.html
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00006.xml
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml
  l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa.py
Labels: approved

#684 FIX l10n_it_fatturapa: partner checks must be done for customers only…
  l10n_it_fatturapa/models/partner.py
Labels: approved, needs review
