Repository OCA/l10n-italy, pull requests merged in 2018-12, with the labels that each got.

#688 [10.0] FIX l10n_it_fatturapa_in when writing attachment name without file
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: needs review

#691 10.0 fix fatturapa translation source strings
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/data/fatturapa_data.xml
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa/readme/CONFIGURE.rst
  l10n_it_fatturapa/static/description/index.html
  l10n_it_fatturapa/views/account_view.xml
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/models/partner.py
  l10n_it_fatturapa_in/readme/CONFIGURE.rst
  l10n_it_fatturapa_in/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in/readme/USAGE.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml
  l10n_it_fatturapa_in_purchase/README.rst
  l10n_it_fatturapa_in_purchase/__manifest__.py
  l10n_it_fatturapa_in_purchase/models/purchase_order.py
  l10n_it_fatturapa_in_purchase/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in_purchase/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in_purchase/readme/USAGE.rst
  l10n_it_fatturapa_in_purchase/static/description/index.html
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/models/account.py
  l10n_it_fatturapa_out/models/attachment.py
  l10n_it_fatturapa_out/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out/readme/USAGE.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_ddt/README.rst
  l10n_it_fatturapa_out_ddt/__manifest__.py
  l10n_it_fatturapa_out_ddt/static/description/index.html
  l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_pec/readme/DESCRIPTION.rst
  l10n_it_fatturapa_pec/readme/USAGE.rst
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/views/account.xml
Labels: approved

#693 [10.0] FIX l10n_it_fatturapa: province is not required in XML
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#646 [12.0] mig l10n_it_causali_pagamento
  l10n_it_causali_pagamento/README.rst
  l10n_it_causali_pagamento/__init__.py
  l10n_it_causali_pagamento/__manifest__.py
  l10n_it_causali_pagamento/data/causali_pagamento_data.xml
  l10n_it_causali_pagamento/i18n/it.po
  l10n_it_causali_pagamento/i18n/l10n_it_causali_pagamento.pot
  l10n_it_causali_pagamento/models/__init__.py
  l10n_it_causali_pagamento/models/causale_pagamento.py
  l10n_it_causali_pagamento/readme/CONFIGURE.rst
  l10n_it_causali_pagamento/readme/CONTRIBUTORS.rst
  l10n_it_causali_pagamento/readme/DESCRIPTION.rst
  l10n_it_causali_pagamento/readme/USAGE.rst
  l10n_it_causali_pagamento/security/ir.model.access.csv
  l10n_it_causali_pagamento/static/description/index.html
  l10n_it_causali_pagamento/tests/__init__.py
  l10n_it_causali_pagamento/tests/test_causali.py
  l10n_it_causali_pagamento/views/causali_pagamento_view.xml
Labels: needs review

#699 FIX not allowed empty Causale
  l10n_it_fatturapa_out/tests/data/IT06363391001_00008.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#665 [12.0] mig l10n_it_withholding_tax_causali
  l10n_it_withholding_tax_causali/README.rst
  l10n_it_withholding_tax_causali/__init__.py
  l10n_it_withholding_tax_causali/__manifest__.py
  l10n_it_withholding_tax_causali/i18n/it.po
  l10n_it_withholding_tax_causali/i18n/l10n_it_withholding_tax_causali.pot
  l10n_it_withholding_tax_causali/models/__init__.py
  l10n_it_withholding_tax_causali/models/withholding_tax.py
  l10n_it_withholding_tax_causali/readme/DESCRIPTION.rst
  l10n_it_withholding_tax_causali/static/description/index.html
  l10n_it_withholding_tax_causali/views/withholding_tax.xml
  setup/l10n_it_withholding_tax_causali/odoo/addons/l10n_it_withholding_tax_causali
  setup/l10n_it_withholding_tax_causali/setup.py
Labels: needs review

#666 [12.0] mig l10n_it_fatturapa_pec & l10n_it_sdi_channel
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__init__.py
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/i18n/l10n_it_fatturapa_pec.pot
  l10n_it_fatturapa_pec/models/__init__.py
  l10n_it_fatturapa_pec/models/account.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_pec/readme/DESCRIPTION.rst
  l10n_it_fatturapa_pec/readme/USAGE.rst
  l10n_it_fatturapa_pec/static/description/icon.png
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/views/account.xml
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
  l10n_it_fatturapa_pec/wizard/__init__.py
  l10n_it_fatturapa_pec/wizard/send_pec.py
  l10n_it_fatturapa_pec/wizard/send_pec_view.xml
  l10n_it_sdi_channel/README.rst
  l10n_it_sdi_channel/__init__.py
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/data/config_parameter.xml
  l10n_it_sdi_channel/i18n/it.po
  l10n_it_sdi_channel/i18n/l10n_it_sdi_channel.pot
  l10n_it_sdi_channel/models/__init__.py
  l10n_it_sdi_channel/models/company.py
  l10n_it_sdi_channel/models/fetchmail_server.py
  l10n_it_sdi_channel/models/ir_mail_server.py
  l10n_it_sdi_channel/models/sdi.py
  l10n_it_sdi_channel/readme/CONFIGURE.rst
  l10n_it_sdi_channel/readme/CONTRIBUTORS.rst
  l10n_it_sdi_channel/readme/DESCRIPTION.rst
  l10n_it_sdi_channel/security/ir.model.access.csv
  l10n_it_sdi_channel/security/security.xml
  l10n_it_sdi_channel/static/description/icon.png
  l10n_it_sdi_channel/static/description/index.html
  l10n_it_sdi_channel/views/company_view.xml
  l10n_it_sdi_channel/views/fetchmail_server.xml
  l10n_it_sdi_channel/views/ir_mail_server.xml
  l10n_it_sdi_channel/views/sdi_view.xml
  setup/l10n_it_fatturapa_pec/odoo/addons/l10n_it_fatturapa_pec
  setup/l10n_it_fatturapa_pec/setup.py
  setup/l10n_it_sdi_channel/odoo/addons/l10n_it_sdi_channel
  setup/l10n_it_sdi_channel/setup.py
Labels: work in progress

#718 [FIX] fatturapa titles using italian guidelines
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/readme/CONFIGURE.rst
  l10n_it_fatturapa/static/description/index.html
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_sdi_channel/README.rst
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/readme/CONFIGURE.rst
  l10n_it_sdi_channel/static/description/index.html
Labels: approved

#723 [10.0] ADD TD20 doc type
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fiscal_document_type/__manifest__.py
  l10n_it_fiscal_document_type/data/fiscal.document.type.csv
  l10n_it_fiscal_document_type/models/account_invoice.py
  l10n_it_fiscal_document_type/tests/test_doc_type.py
Labels: approved, needs review

#724 [10.0] latin for Descrizione invoice line and RiferimentoNormativo tax
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#714 [FIX] l10n_it_fiscal_document_type: fix translation source strings
  l10n_it_fiscal_document_type/README.rst
  l10n_it_fiscal_document_type/__manifest__.py
  l10n_it_fiscal_document_type/models/account_fiscal_position.py
  l10n_it_fiscal_document_type/models/account_invoice.py
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
  l10n_it_fiscal_document_type/models/res_partner.py
  l10n_it_fiscal_document_type/readme/CONFIGURE.rst
  l10n_it_fiscal_document_type/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_document_type/readme/CREDITS.rst
  l10n_it_fiscal_document_type/readme/DESCRIPTION.rst
  l10n_it_fiscal_document_type/static/description/index.html
  l10n_it_fiscal_document_type/views/fiscal_document_type_view.xml
Labels: approved

#716 [8.0] [FIX] tax included amount
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#709 [8.0] [IMP] view more specific xpath
  l10n_it_withholding_tax/views/account.xml
Labels: approved

#696 IMP l10n_it_fatturapa_pec allowing user to configure contacts to be n…
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
Labels: needs review

#722 [10.0] FIX l10n_it_fatturapa_pec: sending PEC with invoicing user raises permission error
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/security/ir.model.access.csv
Labels: needs review

#739 [10.0] FIX l10n_it_fatturapa_out when decimal precision is < 2
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#741 [10.0] FIX l10n_it_fatturapa_out when using an invoice address: cessionario …
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#751 [11.0] ADD TD20 doc type - set default document type in invoice
  l10n_it_fiscal_document_type/__manifest__.py
  l10n_it_fiscal_document_type/data/fiscal.document.type.csv
  l10n_it_fiscal_document_type/models/account_invoice.py
  l10n_it_fiscal_document_type/tests/test_doc_type.py
Labels: approved

#730 [10.0][FIX] l10n_it_rea summary translation and source strings
  l10n_it_rea/README.rst
  l10n_it_rea/__manifest__.py
  l10n_it_rea/models/res_company.py
  l10n_it_rea/models/res_partner.py
  l10n_it_rea/readme/CONTRIBUTORS.rst
  l10n_it_rea/readme/DESCRIPTION.rst
  l10n_it_rea/static/description/index.html
  l10n_it_rea/views/company_view.xml
Labels: approved
