Repository OCA/l10n-italy, pull requests merged in 2018-07, with the labels that each got.

#522 [11.0][MIG] l10n it account: Migration to 11.0
  l10n_it_account/README.rst
  l10n_it_account/__init__.py
  l10n_it_account/__manifest__.py
  l10n_it_account/i18n/es_AR.po
  l10n_it_account/i18n/it.po
  l10n_it_account/i18n/l10n_it_account.pot
  l10n_it_account/i18n/sl.po
  l10n_it_account/models/__init__.py
  l10n_it_account/models/account_tax.py
  l10n_it_account/reports/account_reports_view.xml
  l10n_it_account/static/description/icon.png
  l10n_it_account/views/account_setting.xml
  l10n_it_account/views/account_view.xml
  oca_dependencies.txt
Labels: 11.0

#530 Porting from v10 to v11 l10n_it_esigibilita_iva
  l10n_it_esigibilita_iva/README.rst
  l10n_it_esigibilita_iva/__init__.py
  l10n_it_esigibilita_iva/__manifest__.py
  l10n_it_esigibilita_iva/i18n/es_AR.po
  l10n_it_esigibilita_iva/i18n/it.po
  l10n_it_esigibilita_iva/i18n/l10n_it_esigibilita_iva.pot
  l10n_it_esigibilita_iva/models/__init__.py
  l10n_it_esigibilita_iva/models/account.py
  l10n_it_esigibilita_iva/static/description/icon.png
  l10n_it_esigibilita_iva/views/account_view.xml
Labels: 11.0, needs review

#559 FIX l10n_it_reverse_charge RC payment move should be posted
  l10n_it_reverse_charge/__manifest__.py
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/tests/test_rc.py
Labels: needs review
