Repository OCA/l10n-italy, pull requests merged in 2019-01, with the labels that each got.

#756 [12.0] mig l10n_it_account_stamp
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__init__.py
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/i18n/it.po
  l10n_it_account_stamp/models/__init__.py
  l10n_it_account_stamp/models/company.py
  l10n_it_account_stamp/models/invoice.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp/readme/DESCRIPTION.rst
  l10n_it_account_stamp/readme/USAGE.rst
  l10n_it_account_stamp/static/description/icon.png
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/views/company_view.xml
  l10n_it_account_stamp/views/invoice_view.xml
  l10n_it_account_stamp/views/product_view.xml
  l10n_it_fatturapa_out_stamp/README.rst
  l10n_it_fatturapa_out_stamp/__init__.py
  l10n_it_fatturapa_out_stamp/__manifest__.py
  l10n_it_fatturapa_out_stamp/i18n/it.po
  l10n_it_fatturapa_out_stamp/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_stamp/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_stamp/static/description/index.html
  l10n_it_fatturapa_out_stamp/wizard/__init__.py
  l10n_it_fatturapa_out_stamp/wizard/wizard_export_fatturapa.py
  setup/l10n_it_account_stamp/odoo/addons/l10n_it_account_stamp
  setup/l10n_it_account_stamp/setup.py
  setup/l10n_it_fatturapa_out_stamp/odoo/addons/l10n_it_fatturapa_out_stamp
  setup/l10n_it_fatturapa_out_stamp/setup.py
Labels: needs review

#774 [10.0][FIX] l10n_it_fatturapa_out_stamp: Bollo precision must be 2
  l10n_it_fatturapa_out_stamp/__manifest__.py
  l10n_it_fatturapa_out_stamp/wizard/wizard_export_fatturapa.py
Labels: approved

#733 [12.0] IMP l10n_it_fatturapa_pec allowing user to configure contacts to be n…
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
Labels: needs review

#743 [12.0] FIX l10n_it_fatturapa_pec: sending PEC with invoicing user raises per…
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/security/ir.model.access.csv
Labels: needs review

#757 [12.0] FIX l10n_it_fatturapa_in: do not automatically add Bollo and cassa previdenziale as invoice line
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#742 [12.0] FIX l10n_it_fatturapa_out when using an invoice address: cessionario …
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#740 [12.0] FIX l10n_it_fatturapa_out when decimal precision is < 2
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#587 11.0 mig l10n it ddt delivery
  l10n_it_ddt_delivery/README.rst
  l10n_it_ddt_delivery/__init__.py
  l10n_it_ddt_delivery/__manifest__.py
  l10n_it_ddt_delivery/i18n/it.po
  l10n_it_ddt_delivery/i18n/l10n_it_ddt_delivery.pot
  l10n_it_ddt_delivery/i18n/sl.po
  l10n_it_ddt_delivery/models/__init__.py
  l10n_it_ddt_delivery/models/sale_order.py
  l10n_it_ddt_delivery/readme/CONTRIBUTORS.rst
  l10n_it_ddt_delivery/readme/DESCRIPTION.rst
  l10n_it_ddt_delivery/static/description/icon.png
  l10n_it_ddt_delivery/static/description/index.html
  l10n_it_ddt_delivery/tests/__init__.py
  l10n_it_ddt_delivery/tests/test_ddt_delivery.py
  l10n_it_ddt_delivery/wizards/__init__.py
  l10n_it_ddt_delivery/wizards/ddt_from_pickings.py
  oca_dependencies.txt
Labels: approved, ready to merge

#732 [12.0][FIX] l10n_it_rea summary translation and source strings
  l10n_it_rea/README.rst
  l10n_it_rea/__manifest__.py
  l10n_it_rea/models/res_company.py
  l10n_it_rea/models/res_partner.py
  l10n_it_rea/readme/CONTRIBUTORS.rst
  l10n_it_rea/readme/DESCRIPTION.rst
  l10n_it_rea/static/description/index.html
  l10n_it_rea/tests/test_rea.py
  l10n_it_rea/views/company_view.xml
Labels: approved, ready to merge

#795 [11.0] Se la causale su fattura è composta da più di 200 caratteri, ora fa l…
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#818 [12.0] FIX l10n_it_account_stamp: recompute taxes when adding stamp to lines
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/models/invoice.py
Labels: approved, needs review

#828 [11.0] FIX l10n_it_fatturapa_out when using an invoice address
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#798 [10.0] "mancata consegna" is the correct notification for invoices sent to i…
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/account.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_mancata_consegna.txt
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: needs review

#813 [12.0] "mancata consegna" is the correct notification for invoices sent to individual without PEC or codice destinatario, so it sould not be an error
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/account.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_mancata_consegna.txt
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
Labels: approved, needs review, ready to merge

#814 [11.0] FIX l10n_it_account - stampa fatture multiple
  l10n_it_account/__init__.py
  l10n_it_account/__manifest__.py
  l10n_it_account/models/__init__.py
  l10n_it_account/models/account_tax.py
  l10n_it_account/reports/account_reports_view.xml
  l10n_it_account/static/src/css/l10n_it_account.css
  l10n_it_account/views/account_view.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#809 [12.0] IMP l10n_it_fatturapa_in do not block import in case of missing VAT exemption configuration
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#862 [8.0] FIX l10n_it_withholding_tax: invoicing user can't open nor create invoices with wh tax
  l10n_it_withholding_tax/security/ir.model.access.csv
Labels: approved, needs review

#855 [11.0] FIX l10n_it fattuapa: translation, importing XML;(signed with CAdES - elements with blank spac)
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/bindings/fatturapa_v_1_2.py
  l10n_it_fatturapa/data/fatturapa_data.xml
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa/views/account_view.xml
  l10n_it_fatturapa/views/company_view.xml
  l10n_it_fatturapa/views/invoice_view.xml
Labels: approved

#856 [8.0][FIX]"mancata consegna" is the correct notification for invoices sent to i…
  l10n_it_fatturapa_pec/__openerp__.py
  l10n_it_fatturapa_pec/models/account.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
Labels: approved, ready to merge

#851 [10.0] e-invoice multi company
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/security/rules.xml
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/security/rules.xml
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/__init__.py
  l10n_it_fatturapa_pec/models/company.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/views/company_view.xml
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/models/sdi.py
  l10n_it_sdi_channel/views/sdi_view.xml
Labels: approved

#885 [12.0] [FIX] move stamp checkbox to avoid misleading
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/DESCRIPTION.rst
  l10n_it_account_stamp/readme/USAGE.rst
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/views/invoice_view.xml
Labels: approved

#731 [11.0][FIX] l10n_it_rea summary translation and source strings
  l10n_it_rea/README.rst
  l10n_it_rea/__manifest__.py
  l10n_it_rea/models/res_company.py
  l10n_it_rea/models/res_partner.py
  l10n_it_rea/readme/CONTRIBUTORS.rst
  l10n_it_rea/readme/DESCRIPTION.rst
  l10n_it_rea/static/description/index.html
  l10n_it_rea/views/company_view.xml
Labels: approved

#777 [11.0][MIG] l10n_it_account_stamp
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__init__.py
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/i18n/it.po
  l10n_it_account_stamp/i18n/l10n_it_account_stamp.pot
  l10n_it_account_stamp/models/__init__.py
  l10n_it_account_stamp/models/company.py
  l10n_it_account_stamp/models/invoice.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/models/res_config_settings.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp/readme/DESCRIPTION.rst
  l10n_it_account_stamp/readme/USAGE.rst
  l10n_it_account_stamp/static/description/icon.png
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/views/invoice_view.xml
  l10n_it_account_stamp/views/product_view.xml
  l10n_it_account_stamp/views/res_config_settings_view.xml
Labels: approved

#881 [8.0][FIX] fill supplier_invoice_number
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: work in progress

#888 [10.0] foreign customers
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/readme/USAGE.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/tests/data/IT06363391001_00009.xml
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: 10.0, approved, needs review

#901 [12.0] foreign customers
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/readme/USAGE.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/tests/data/IT06363391001_00009.xml
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#844 [12.0] IMP l10n_it_fiscalcode company view: allow to specify company fiscal code
  l10n_it_fiscalcode/__manifest__.py
  l10n_it_fiscalcode/model/__init__.py
  l10n_it_fiscalcode/model/res_company.py
  l10n_it_fiscalcode/view/company_view.xml
Labels: needs review

#912 [11.0] foreign customers
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/readme/USAGE.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/tests/data/IT06363391001_00009.xml
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: 11.0, approved, needs review

#909 [10.0] FIX import XML with invalid URI
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml
Labels: approved

#891 [12.0] [IMP] l10n_account_stamp add manual mode
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/models/invoice.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/static/description/icon.png
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/views/invoice_view.xml
  l10n_it_account_stamp/views/product_view.xml
Labels: approved
