Repository OCA/l10n-italy, pull requests merged in 2019-08, with the labels that each got.

#1400 [11.0][IMP] l10n_it_fiscal_document_type: nome e codice obbligatori
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
Labels: merged 🎉

#1348 [10.0][fix] withholding tax duplication
  l10n_it_withholding_tax/models/account.py
Labels: approved, ready to merge

#1402 [8.0][IMP] l10n_it_fiscal_document_type: nome e codice obbligatori
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
Labels: merged 🎉

#1422 FIX l10n_it_fiscal_document_type: when "Fiscal Document Type" is set …
  l10n_it_fiscal_document_type/models/account_invoice.py
Labels: approved, needs review

#1437 [12.0] FIX l10n_it_fatturapa_out: remove duplicate code
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review
