Repository OCA/l10n-italy, pull requests merged in 2019-02, with the labels that each got.

#914 [10.0] IMP l10n_it_fatturapa_pec avoiding to block fetchmail server in case of temporary errors
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/data/fetchmail_data.xml
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
Labels: approved, needs review

#920 [12.0] IMP l10n_it_fatturapa_pec avoiding to block fetchmail server in case of temporary errors
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/data/fetchmail_data.xml
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
Labels: needs review

#935 [12.0] IMP l10n_it_fatturapa_pec allowing to force the XML export state.
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/security/groups.xml
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
Labels: approved, needs review

#867 [10.0][ADD] l10n_it_website_portal_fiscalcode
  l10n_it_website_portal_fiscalcode/README.rst
  l10n_it_website_portal_fiscalcode/__init__.py
  l10n_it_website_portal_fiscalcode/__manifest__.py
  l10n_it_website_portal_fiscalcode/controllers/__init__.py
  l10n_it_website_portal_fiscalcode/controllers/main.py
  l10n_it_website_portal_fiscalcode/i18n/it.po
  l10n_it_website_portal_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_website_portal_fiscalcode/static/description/index.html
  l10n_it_website_portal_fiscalcode/views/l10n_it_website_portal_fiscalcode_templates.xml
Labels: needs fixing

#930 [12.0] FIX: l10n_it_fatturapa_in parsing DatiFattureCollegate
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT05979361218_010.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#640 [11.0] mig l10n_it_fatturapa_in
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__init__.py
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/i18n/it.po
  l10n_it_fatturapa_in/i18n/l10n_it_fatturapa_in.pot
  l10n_it_fatturapa_in/models/__init__.py
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/models/partner.py
  l10n_it_fatturapa_in/readme/CONFIGURE.rst
  l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in/readme/INSTALL.rst
  l10n_it_fatturapa_in/readme/USAGE.rst
  l10n_it_fatturapa_in/security/ir.model.access.csv
  l10n_it_fatturapa_in/security/rules.xml
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/static/src/img/icon.png
  l10n_it_fatturapa_in/tests/__init__.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.xml
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.xml.p7m
  l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml
  l10n_it_fatturapa_in/tests/data/IT02780790107_11005.xml
  l10n_it_fatturapa_in/tests/data/IT02780790107_11006.xml
  l10n_it_fatturapa_in/tests/data/IT02780790107_11007.xml
  l10n_it_fatturapa_in/tests/data/IT03638121008_X11111.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_002.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_002.xml.p7m
  l10n_it_fatturapa_in/tests/data/IT05979361218_003.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_004.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_005.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_006.XML
  l10n_it_fatturapa_in/tests/data/IT05979361218_007.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_008.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_009.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_010.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_fake.xml.p7m
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/views/partner_view.xml
  l10n_it_fatturapa_in/wizard/__init__.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml
Labels: work in progress

#926 [10.0] FIX: l10n_it_fatturapa_in parsing DatiFattureCollegate
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT05979361218_010.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#943 [10.0] FIX l10n_it_fatturapa_out for invoices with payment term and total = 0
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#864 11.0 mig l10n it fatturapa out ddt
  l10n_it_fatturapa_out_ddt/README.rst
  l10n_it_fatturapa_out_ddt/__init__.py
  l10n_it_fatturapa_out_ddt/__manifest__.py
  l10n_it_fatturapa_out_ddt/i18n/it.po
  l10n_it_fatturapa_out_ddt/i18n/l10n_it_fatturapa_out_ddt.pot
  l10n_it_fatturapa_out_ddt/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_ddt/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_ddt/readme/USAGE.rst
  l10n_it_fatturapa_out_ddt/static/description/index.html
  l10n_it_fatturapa_out_ddt/tests/__init__.py
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00006.xml
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml
  l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py
  l10n_it_fatturapa_out_ddt/wizard/__init__.py
  l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa_view.xml
Labels: approved, ready to merge

#929 [8.0][IMP] extract pdf if in e-invoice if only linked
  l10n_it_fatturapa_in/__openerp__.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#845 [10.0] IMP l10n_it_fiscalcode company view: allow to specify company fiscal code
  l10n_it_fiscalcode/__manifest__.py
  l10n_it_fiscalcode/model/__init__.py
  l10n_it_fiscalcode/model/res_company.py
  l10n_it_fiscalcode/view/company_view.xml
Labels: approved, needs review, ready to merge

#924 [10.0][ADD] l10n_it_account_stamp_sale module
  l10n_it_account_stamp_sale/README.rst
  l10n_it_account_stamp_sale/__init__.py
  l10n_it_account_stamp_sale/__manifest__.py
  l10n_it_account_stamp_sale/models/__init__.py
  l10n_it_account_stamp_sale/models/sale_order.py
  l10n_it_account_stamp_sale/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp_sale/readme/DESCRIPTION.rst
  l10n_it_account_stamp_sale/static/description/icon.png
  l10n_it_account_stamp_sale/static/description/index.html
Labels: 10.0, approved, needs review, ready to merge

#945 [12.0] [IMP] show e-invoice payment term and method columns
  l10n_it_fiscal_payment_term/README.rst
  l10n_it_fiscal_payment_term/__manifest__.py
  l10n_it_fiscal_payment_term/readme/CONFIGURE.rst
  l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_payment_term/readme/DESCRIPTION.rst
  l10n_it_fiscal_payment_term/static/description/index.html
  l10n_it_fiscal_payment_term/views/account_view.xml
Labels: approved, needs review

#951 [11.0] l10n_it_fatturapa_out: use company_name for Denominazione, when present
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#927 [10.0] l10n_it_fatturapa: use asn1crypto instead of openssl
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/readme/INSTALL.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.base64.xml.p7m
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, needs fixing

#919 [10.0][ADD] l10n_it_account_stamp_ddt module
  l10n_it_account_stamp_ddt/README.rst
  l10n_it_account_stamp_ddt/__init__.py
  l10n_it_account_stamp_ddt/__manifest__.py
  l10n_it_account_stamp_ddt/models/__init__.py
  l10n_it_account_stamp_ddt/models/stock_picking_package_preparation.py
  l10n_it_account_stamp_ddt/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp_ddt/readme/DESCRIPTION.rst
  l10n_it_account_stamp_ddt/static/description/icon.png
  l10n_it_account_stamp_ddt/static/description/index.html
Labels: 10.0, approved, needs review

#947 [12.0] FIX l10n_it_fiscalcode check when e-commerce user sets 'company_name'
  l10n_it_fiscalcode/__manifest__.py
  l10n_it_fiscalcode/model/res_partner.py
  l10n_it_fiscalcode/tests/test_fiscalcode.py
Labels: approved, needs review

#931 [10.0] IMP l10n_it_fatturapa_pec allowing to force the XML export state.
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/security/groups.xml
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
Labels: approved, needs review

#869 [12.0][MIG] l10n_it_website_sale_fiscalcode
  l10n_it_fatturapa/models/account.py
  l10n_it_website_sale_fiscalcode/README.rst
  l10n_it_website_sale_fiscalcode/__init__.py
  l10n_it_website_sale_fiscalcode/__manifest__.py
  l10n_it_website_sale_fiscalcode/controllers/__init__.py
  l10n_it_website_sale_fiscalcode/controllers/main.py
  l10n_it_website_sale_fiscalcode/i18n/de.po
  l10n_it_website_sale_fiscalcode/i18n/es.po
  l10n_it_website_sale_fiscalcode/i18n/it.po
  l10n_it_website_sale_fiscalcode/i18n/l10n_it_website_sale_fiscalcode.pot
  l10n_it_website_sale_fiscalcode/i18n/sl.po
  l10n_it_website_sale_fiscalcode/readme/CONTRIBUTORS.rst
  l10n_it_website_sale_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_website_sale_fiscalcode/readme/USAGE.rst
  l10n_it_website_sale_fiscalcode/static/description/index.html
  l10n_it_website_sale_fiscalcode/views/templates.xml
Labels: approved, needs review

#562 FIX l10n_it_esigibilita_iva: corretto target nel README, cambiato qui…
  l10n_it_esigibilita_iva/README.rst
  l10n_it_esigibilita_iva/readme/CONTRIBUTORS.rst
  l10n_it_esigibilita_iva/readme/DESCRIPTION.rst
  l10n_it_esigibilita_iva/static/description/index.html
Labels: needs review

#895 [8.0] add fiscal note for autoinvoices
  l10n_it_fiscal_document_type/README.rst
  l10n_it_fiscal_document_type/readme/CONFIGURE.rst
  l10n_it_fiscal_document_type/static/description/index.html
Labels: needs review

#917 [10.0] add fiscal note for autoinvoices
  l10n_it_fiscal_document_type/README.rst
  l10n_it_fiscal_document_type/readme/CONFIGURE.rst
  l10n_it_fiscal_document_type/static/description/index.html
Labels: needs review

#962 [10.0] [FIX] l10n_it_fatturapa: allow xml files without xml declaration
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT05979361218_no_decl.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved

#986 [12.0] l10n_it_fatturapa: use asn1crypto instead of openssl
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/readme/INSTALL.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.base64.xml.p7m
  l10n_it_fatturapa_in/tests/data/IT05979361218_no_decl.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved

#955 [11.0] [IMP] Backport from 12.0 show e-invoice payment term and method columns (#945)
  l10n_it_fiscal_payment_term/README.rst
  l10n_it_fiscal_payment_term/__manifest__.py
  l10n_it_fiscal_payment_term/readme/CONFIGURE.rst
  l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_payment_term/readme/DESCRIPTION.rst
  l10n_it_fiscal_payment_term/static/description/index.html
  l10n_it_fiscal_payment_term/views/account_view.xml
Labels: approved, needs review

#977 [12.0][ADD] l10n_it_corrispettivi_fatturapa_out
  l10n_it_corrispettivi_fatturapa_out/README.rst
  l10n_it_corrispettivi_fatturapa_out/__init__.py
  l10n_it_corrispettivi_fatturapa_out/__manifest__.py
  l10n_it_corrispettivi_fatturapa_out/readme/DESCRIPTION.rst
  l10n_it_corrispettivi_fatturapa_out/static/description/index.html
  l10n_it_corrispettivi_fatturapa_out/views/account_invoice_view.xml
Labels: approved, needs review

#999 [12.0] FIX l10n_it_fatturapa_pec when user removes file content and tries to send PEC
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
Labels: needs review

#953 [10.0] FIX l10n_it_fatturapa_pec when user removes file content and tries to send PEC
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
Labels: needs review

#991 [10.0] FIX If there are characters '\t' (tab) on description of invoice line, the invoice can't be exported
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#933 12.0 mig l10n it pec
  l10n_it_pec/README.rst
  l10n_it_pec/__init__.py
  l10n_it_pec/__manifest__.py
  l10n_it_pec/i18n/am.po
  l10n_it_pec/i18n/ar.po
  l10n_it_pec/i18n/bg.po
  l10n_it_pec/i18n/bs.po
  l10n_it_pec/i18n/ca.po
  l10n_it_pec/i18n/cs.po
  l10n_it_pec/i18n/da.po
  l10n_it_pec/i18n/de.po
  l10n_it_pec/i18n/el_GR.po
  l10n_it_pec/i18n/en_GB.po
  l10n_it_pec/i18n/es.po
  l10n_it_pec/i18n/es_AR.po
  l10n_it_pec/i18n/es_CR.po
  l10n_it_pec/i18n/es_EC.po
  l10n_it_pec/i18n/es_MX.po
  l10n_it_pec/i18n/es_VE.po
  l10n_it_pec/i18n/et.po
  l10n_it_pec/i18n/fi.po
  l10n_it_pec/i18n/fr.po
  l10n_it_pec/i18n/fr_CA.po
  l10n_it_pec/i18n/fr_CH.po
  l10n_it_pec/i18n/gl.po
  l10n_it_pec/i18n/hr.po
  l10n_it_pec/i18n/hr_HR.po
  l10n_it_pec/i18n/hu.po
  l10n_it_pec/i18n/it.po
  l10n_it_pec/i18n/ja.po
  l10n_it_pec/i18n/l10n_it_pec.pot
  l10n_it_pec/i18n/lt.po
  l10n_it_pec/i18n/lv.po
  l10n_it_pec/i18n/mk.po
  l10n_it_pec/i18n/mn.po
  l10n_it_pec/i18n/nb.po
  l10n_it_pec/i18n/nb_NO.po
  l10n_it_pec/i18n/nl.po
  l10n_it_pec/i18n/nl_BE.po
  l10n_it_pec/i18n/pl.po
  l10n_it_pec/i18n/pt.po
  l10n_it_pec/i18n/pt_BR.po
  l10n_it_pec/i18n/pt_PT.po
  l10n_it_pec/i18n/ro.po
  l10n_it_pec/i18n/ru.po
  l10n_it_pec/i18n/sl.po
  l10n_it_pec/i18n/sr@latin.po
  l10n_it_pec/i18n/sv.po
  l10n_it_pec/i18n/th.po
  l10n_it_pec/i18n/tr.po
  l10n_it_pec/i18n/vi.po
  l10n_it_pec/i18n/zh_CN.po
  l10n_it_pec/i18n/zh_TW.po
  l10n_it_pec/models/__init__.py
  l10n_it_pec/models/partner.py
  l10n_it_pec/readme/CONTRIBUTORS.rst
  l10n_it_pec/readme/DESCRIPTION.rst
  l10n_it_pec/static/description/icon.png
  l10n_it_pec/static/description/index.html
  l10n_it_pec/views/partner_view.xml
Labels: approved, ready to merge

#1004 [11.0][FIX] l10n_it_corrispettivi - fix report
  l10n_it_corrispettivi/__manifest__.py
  l10n_it_corrispettivi/models/account.py
  l10n_it_corrispettivi/readme/CONFIGURE.rst
  l10n_it_corrispettivi/views/account_report.xml
Labels: approved

#970 [8.0] l10n_it_fatturapa: use asn1crypto instead of openssl
  l10n_it_fatturapa/__openerp__.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.base64.xml.p7m
  l10n_it_fatturapa_in/tests/data/IT05979361218_no_decl.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved

#975 [10.0] IMP l10n_it_fatturapa_in using supplier payment term to compute due date
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review, ready to merge

#1000 [12.0] [FIX] l10n_it_corrispettivi use correct term 'receipt'
  l10n_it_corrispettivi/README.rst
  l10n_it_corrispettivi/__manifest__.py
  l10n_it_corrispettivi/data/account_journal_data.xml
  l10n_it_corrispettivi/models/account.py
  l10n_it_corrispettivi/readme/CONFIGURE.rst
  l10n_it_corrispettivi/readme/CONTRIBUTORS.rst
  l10n_it_corrispettivi/static/description/index.html
  l10n_it_corrispettivi/tests/test_corrispettivi.py
  l10n_it_corrispettivi/views/account_report.xml
  l10n_it_corrispettivi/views/account_view.xml
Labels: approved, needs review, ready to merge

#916 [8.0][FIX] domain in create invoice wizard
  l10n_it_ddt/wizard/ddt_create_invoice.py
Labels: needs review

#972 [11.0] l10n_it_fatturapa: use asn1crypto instead of openssl
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/readme/INSTALL.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.base64.xml.p7m
  l10n_it_fatturapa_in/tests/data/IT05979361218_no_decl.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: needs review

#1013 [12.0][FIX]l10n_it_account: fix https://github.com/OCA/l10n-italy/issues/966
  l10n_it_account/__manifest__.py
  l10n_it_account/views/res_config_settings_views.xml
Labels: approved, needs review

#1022 [10.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#1007 [8.0][FIX] only cancelled invoices are not linkable
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
Labels: needs review

#1032 [10.0] FIX l10n_it_fatturapa_out AttributeError: 'res.company' object has no attribute 'company'
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#1023 [11.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#1024 [12.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#781 [8.0][FIX] If there are characters '\t' (tab) or '\r' (cr) on description of invoice li…
  l10n_it_fatturapa_out/__openerp__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#1034 8.0 IMP Add xml supplier in search xml
  l10n_it_fatturapa_in/__openerp__.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: needs review

#1038 [FIX] l10n_it_fatturapa_pec: https://github.com/OCA/l10n-italy/issues/1037
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/views/company_view.xml
Labels: approved

#1035 10.0 IMP Add xml supplier in search xml
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: needs review
