Repository OCA/l10n-italy, pull requests merged in 2019-07, with the labels that each got.

#1060 [10.0] [FIX] l10n_it_fatturapa_in: OCA#1029 (avoid unique REA Code constraint)
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs fixing

#1288 [10][l10n_it_ddt] fatturazione servizi da DDT
  l10n_it_ddt/README.rst
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/models/__init__.py
  l10n_it_ddt/models/partner.py
  l10n_it_ddt/models/product.py
  l10n_it_ddt/models/sale.py
  l10n_it_ddt/models/stock.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/tests/test_ddt.py
  l10n_it_ddt/views/partner.xml
  l10n_it_ddt/views/product.xml
  l10n_it_ddt/views/sale.xml
  l10n_it_ddt/wizard/ddt_from_picking.py
Labels: approved

#1331 [10.0][IMP] l10n_it_vat_registries: Allow to print reports with no account moves
  l10n_it_vat_registries/README.rst
  l10n_it_vat_registries/__manifest__.py
  l10n_it_vat_registries/readme/CONFIGURE.rst
  l10n_it_vat_registries/static/description/index.html
  l10n_it_vat_registries/wizard/print_registro_iva.py
Labels: approved

#1343 [FIX] Rinominata directory per script di migrazione
  l10n_it_account/__manifest__.py
  l10n_it_account/migrations/11.0.1.3.1/post-migration.py
Labels: approved, merged 🎉

#1313 [10.0][FIX] l10n_it_fatturapa: Do not strip XML elements.
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/bindings/README.md
  l10n_it_fatturapa/bindings/_ds.py
  l10n_it_fatturapa/bindings/binding.py
  l10n_it_fatturapa/bindings/fatturapa.py
  l10n_it_fatturapa/bindings/xsd/FatturaPA_versione_1.2.1.xsd.diff
  l10n_it_fatturapa/bindings/xsd/Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/tests/data/IT02780790107_11007.xml
  l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml
Labels: needs review

#1350 [12.0] Fix withholding tax duplication
  l10n_it_withholding_tax/__manifest__.py
  l10n_it_withholding_tax/models/account.py
Labels: approved

#1361 [12.0] fix number page in footer when print report with more page
  l10n_it_account/reports/account_reports_view.xml
Labels: approved, needs review

#1337 [10][l10n-italy] ddt line is invoiced based on new method, in order to…
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
Labels: approved

#1322 FIX l10n_it_fatturapa_in_purchase: allow to set PO line in invoice line
  l10n_it_fatturapa_in_purchase/views/invoice_view.xml
Labels: needs review

#1379 FIX Assertion failed on job for postgresql@9.2-main.service.
  .travis.yml
Labels: approved
