Repository OCA/l10n-italy, pull requests merged in 2019-06, with the labels that each got.

#1252 [8.0] l10n_it_fatturapa_in: Correct _get_tax_amount() function
  l10n_it_fatturapa_in/__openerp__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1244 [12.0] IMP l10n_it_ddt interfaccia e stampa
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/views/report_ddt.xml
  l10n_it_ddt/views/stock_picking_package_preparation.xml
Labels: approved, needs review, ready to merge

#1087 [12.0] REF moduli e-fattura per poter generare più di 99999 fatture
  l10n_it_fatturapa/data/fatturapa_data.xml
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/views/company_view.xml
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/models/attachment.py
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: needs review

#1269 l10n_it_ddt: add TD Info to incoming picking
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/models/stock.py
  l10n_it_ddt/views/stock_picking.xml
Labels: approved

#1265 [12.0] [FIX] l10n_it_fatturapa_out: DettaglioPagamento creation (#1246)
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#1280 [12.0] Migration: l10n_it_vat_registries_split_payment
  l10n_it_vat_registries_split_payment/README.rst
  l10n_it_vat_registries_split_payment/__init__.py
  l10n_it_vat_registries_split_payment/__manifest__.py
  l10n_it_vat_registries_split_payment/i18n/l10n_it_vat_registries_split_payment.pot
  l10n_it_vat_registries_split_payment/models/__init__.py
  l10n_it_vat_registries_split_payment/models/account_tax.py
  l10n_it_vat_registries_split_payment/readme/CONTRIBUTORS.rst
  l10n_it_vat_registries_split_payment/readme/DESCRIPTION.rst
  l10n_it_vat_registries_split_payment/static/description/icon.png
  l10n_it_vat_registries_split_payment/static/description/index.html
  l10n_it_vat_registries_split_payment/tests/__init__.py
  l10n_it_vat_registries_split_payment/tests/test_sp.py
Labels: approved

#1229 [10.0] Fattura elettronica per indirizzi di fatturazione
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/account.py
Labels: approved, needs review

#1066 [12.0][l10n_it_fatturapa] Add support to multiple invoice preview formats
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/readme/CONFIGURE.rst
  l10n_it_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa/views/company_view.xml
Labels: approved, needs review

#1059 [11.0] [FIX] l10n_it_fatturapa_in: OCA#1029 (avoid unique REA Code constraint)
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_rea/__manifest__.py
  l10n_it_rea/models/res_partner.py
Labels: approved

#1292 [12.0][IMP] add pyxb version dependency
  setup/l10n_it_fatturapa/setup.py
Labels: approved

#1010 [12.0] Restore DatiCassaPrevidenziale handling: when present, add it as invoice line
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#928 [10.0][l10n_it_ricevute_bancarie] Add support to setup RiBa payment result …
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/models/account_config.py
  l10n_it_ricevute_bancarie/views/account_config_view.xml
  l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
Labels: approved, needs review

#1294 [12.0] FIX l10n_it_vat_statement_communication CodiceFornitura is fixed IVP18
  l10n_it_vat_statement_communication/README.rst
  l10n_it_vat_statement_communication/__manifest__.py
  l10n_it_vat_statement_communication/migrations/12.0.1.1.0/post-migrate.py
  l10n_it_vat_statement_communication/models/__init__.py
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
  l10n_it_vat_statement_communication/models/config.py
  l10n_it_vat_statement_communication/readme/CONTRIBUTORS.rst
  l10n_it_vat_statement_communication/security/security.xml
  l10n_it_vat_statement_communication/static/description/index.html
  l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
  l10n_it_vat_statement_communication/views/config.xml
Labels: needs review

#1261 [10.0][FIX] l10n_it_fatturapa_in: Regex is not matching an encoded file
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.base64.xml.p7m
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved

#1279 [11.0] Migration: l10n_it_vat_registries_split_payment
  l10n_it_vat_registries_split_payment/README.rst
  l10n_it_vat_registries_split_payment/__init__.py
  l10n_it_vat_registries_split_payment/__manifest__.py
  l10n_it_vat_registries_split_payment/i18n/l10n_it_vat_registries_split_payment.pot
  l10n_it_vat_registries_split_payment/readme/CONTRIBUTORS.rst
  l10n_it_vat_registries_split_payment/readme/DESCRIPTION.rst
  l10n_it_vat_registries_split_payment/report/__init__.py
  l10n_it_vat_registries_split_payment/report/report_vat_registry.py
  l10n_it_vat_registries_split_payment/static/description/icon.png
  l10n_it_vat_registries_split_payment/static/description/index.html
  l10n_it_vat_registries_split_payment/tests/__init__.py
  l10n_it_vat_registries_split_payment/tests/test_sp.py
Labels: approved

#1308 [8.0][FIX] l10n_it_fatturapa: Remove newlines from base64 file before decoding
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.base64.xml.p7m
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved

#1311 [10.0][IMP] l10n_it_fatturapa_in: When linking an e-invoice to an invoice, set reference and invoice date in the invoice if empty
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_out_wt/models/withholding_tax.py
Labels: approved, needs review
