Repository OCA/l10n-italy, pull requests merged in 2019-04, with the labels that each got.

#1009 [10.0] Restore DatiCassaPrevidenziale handling: when present, add it as invoice line
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1157 [10.0][FIX] l10n_it_corrispettivi: Find fiscal positions without company
  l10n_it_corrispettivi/__manifest__.py
  l10n_it_corrispettivi/models/account.py
Labels: approved

#1164 [12.0] FIX l10n_it_corrispettivi_sale auto_install
  l10n_it_corrispettivi_sale/__manifest__.py
Labels: approved, needs review

#1163 Link to new contribuire pages
  README.md
Labels: approved

#1112 [12.0][IMP][l10n_it_fatturapa_in] Format Italian VAT ID to always have 11 chars
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT05979361218_011.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1159 [10.0][IMP] l10n_it_corrispettivi: Show the corrispettivi tree view as a result of refund wizard
  l10n_it_corrispettivi/__init__.py
  l10n_it_corrispettivi/__manifest__.py
  l10n_it_corrispettivi/wizards/__init__.py
  l10n_it_corrispettivi/wizards/account_invoice_refund.py
Labels: approved

#1155 [10.0][FIX] l10n_it_reverse_charge: Check RC flag in lines of brand new vendor bill refund
  l10n_it_reverse_charge/__manifest__.py
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/tests/test_rc.py
Labels: approved

#1166 [12.0] auto_install e-commerce modules
  l10n_it_website_sale_fatturapa/__manifest__.py
  l10n_it_website_sale_fiscalcode/__manifest__.py
Labels: needs review

#1149 [8.0] duplica ddt set copy=False on invoice_id
  l10n_it_ddt/__openerp__.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
Labels: approved, ready to merge

#998 [10.0] pyxb 1.2.6
  .travis.yml
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/bindings/FatturaPA_versione_1.2.1.xsd.diff
  l10n_it_fatturapa/bindings/README.md
  l10n_it_fatturapa/bindings/__init__.py
  l10n_it_fatturapa/bindings/_ds.py
  l10n_it_fatturapa/bindings/fatturapa_v_1_2.py
  l10n_it_fatturapa/readme/INSTALL.rst
  l10n_it_fatturapa/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.xml
Labels: needs review

#871 [12.0][MIG] l10n_it_website_sale_corrispettivi
  l10n_it_website_sale_corrispettivi/README.rst
  l10n_it_website_sale_corrispettivi/__init__.py
  l10n_it_website_sale_corrispettivi/__manifest__.py
  l10n_it_website_sale_corrispettivi/controllers/__init__.py
  l10n_it_website_sale_corrispettivi/controllers/main.py
  l10n_it_website_sale_corrispettivi/i18n/it.po
  l10n_it_website_sale_corrispettivi/i18n/l10n_it_website_sale_corrispettivi.pot
  l10n_it_website_sale_corrispettivi/models/__init__.py
  l10n_it_website_sale_corrispettivi/models/website.py
  l10n_it_website_sale_corrispettivi/readme/CONFIGURE.rst
  l10n_it_website_sale_corrispettivi/readme/CONTRIBUTORS.rst
  l10n_it_website_sale_corrispettivi/readme/DESCRIPTION.rst
  l10n_it_website_sale_corrispettivi/readme/ROADMAP.rst
  l10n_it_website_sale_corrispettivi/static/description/index.html
  l10n_it_website_sale_corrispettivi/static/src/js/l10n_it_website_sale_corrispettivi.js
  l10n_it_website_sale_corrispettivi/tests/__init__.py
  l10n_it_website_sale_corrispettivi/tests/test_website_sale_no_corrispettivi.py
  l10n_it_website_sale_corrispettivi/views/templates.xml
  setup/l10n_it_website_sale_corrispettivi/odoo/addons/l10n_it_website_sale_corrispettivi
  setup/l10n_it_website_sale_corrispettivi/setup.py
Labels: approved, needs review

#1133 [FIX] valid other countries intermediary filename
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: needs review

#1173 FIX l10n_it_website_portal_fatturapa: Cannot read property 'checked' of undefined
  l10n_it_website_portal_fatturapa/__manifest__.py
  l10n_it_website_portal_fatturapa/readme/ROADMAP.rst
  l10n_it_website_portal_fatturapa/static/src/js/l10n_it_website_portal_fatturapa.js
Labels: approved, needs review

#1178 [12.0] [FIX] parse e-invoice filename from intermediary from other countries (#1133)
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: needs review

#1008 [8.0] FIX l10n_it_fatturapa_pec when user removes file content and tries to…
  l10n_it_fatturapa_pec/__openerp__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
Labels: needs review

#1153 [FIX] l10n_it_fatturapa: Add cross check pec_destinatario and codice_destinatario
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/partner.py
Labels: needs review

#1161 [12.0] mig l10n_it_website_portal_fatturapa and l10n_it_website_portal_fiscalcode
  l10n_it_website_portal_fatturapa/README.rst
  l10n_it_website_portal_fatturapa/__init__.py
  l10n_it_website_portal_fatturapa/__manifest__.py
  l10n_it_website_portal_fatturapa/controllers/__init__.py
  l10n_it_website_portal_fatturapa/controllers/main.py
  l10n_it_website_portal_fatturapa/i18n/l10n_it_website_portal_fatturapa.pot
  l10n_it_website_portal_fatturapa/readme/DESCRIPTION.rst
  l10n_it_website_portal_fatturapa/readme/ROADMAP.rst
  l10n_it_website_portal_fatturapa/static/description/icon.png
  l10n_it_website_portal_fatturapa/static/description/index.html
  l10n_it_website_portal_fatturapa/static/src/js/l10n_it_website_portal_fatturapa.js
  l10n_it_website_portal_fatturapa/views/l10n_it_website_portal_fatturapa_templates.xml
  l10n_it_website_portal_fiscalcode/README.rst
  l10n_it_website_portal_fiscalcode/__init__.py
  l10n_it_website_portal_fiscalcode/__manifest__.py
  l10n_it_website_portal_fiscalcode/controllers/__init__.py
  l10n_it_website_portal_fiscalcode/controllers/main.py
  l10n_it_website_portal_fiscalcode/i18n/it.po
  l10n_it_website_portal_fiscalcode/i18n/l10n_it_website_portal_fiscalcode.pot
  l10n_it_website_portal_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_website_portal_fiscalcode/static/description/icon.png
  l10n_it_website_portal_fiscalcode/static/description/index.html
  l10n_it_website_portal_fiscalcode/views/l10n_it_website_portal_fiscalcode_templates.xml
  setup/l10n_it_website_portal_fatturapa/odoo/addons/l10n_it_website_portal_fatturapa
  setup/l10n_it_website_portal_fatturapa/setup.py
  setup/l10n_it_website_portal_fiscalcode/odoo/addons/l10n_it_website_portal_fiscalcode
  setup/l10n_it_website_portal_fiscalcode/setup.py
Labels: needs review

#1190 [10.0] Fix FATTURAPA_IN_REGEX to allow signed incoming invoices
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: needs review

#1191 [12.0] Fix FATTURAPA_IN_REGEX to allow signed incoming invoices
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: needs review

#1170 [12.0] [FIX] l10n_it_corrispettivi: Find fiscal positions without company
  l10n_it_corrispettivi/__manifest__.py
  l10n_it_corrispettivi/models/account.py
Labels: approved, needs review

#1003 [10.0] Fix multicurrency in reverse charge + handle discount + improve performance
  l10n_it_reverse_charge/__manifest__.py
  l10n_it_reverse_charge/data/rc_type.xml
  l10n_it_reverse_charge/models/account_invoice.py
Labels: approved, needs review

#1194 [10.0][IMP] l10n_it_fatturapa_in: Add total in attachment's tree view
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved

#1011 [11.0] Restore DatiCassaPrevidenziale handling: when present, add it as invoice line
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1005 [10.0] l10n_it_invoices_data_communication
  l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py
  l10n_it_invoices_data_communication/README.rst
  l10n_it_invoices_data_communication/__init__.py
  l10n_it_invoices_data_communication/__manifest__.py
  l10n_it_invoices_data_communication/i18n/it.po
  l10n_it_invoices_data_communication/models/__init__.py
  l10n_it_invoices_data_communication/models/account.py
  l10n_it_invoices_data_communication/models/account_invoice.py
  l10n_it_invoices_data_communication/models/communication.py
  l10n_it_invoices_data_communication/readme/CONTRIBUTORS.rst
  l10n_it_invoices_data_communication/readme/CREDITS.rst
  l10n_it_invoices_data_communication/readme/DESCRIPTION.rst
  l10n_it_invoices_data_communication/readme/ROADMAP.rst
  l10n_it_invoices_data_communication/security/ir.model.access.csv
  l10n_it_invoices_data_communication/security/security.xml
  l10n_it_invoices_data_communication/static/description/index.html
  l10n_it_invoices_data_communication/views/account.xml
  l10n_it_invoices_data_communication/views/account_invoice_view.xml
  l10n_it_invoices_data_communication/views/comunicazione.xml
  l10n_it_invoices_data_communication/wizard/__init__.py
  l10n_it_invoices_data_communication/wizard/compute_fiscal_document_type.py
  l10n_it_invoices_data_communication/wizard/compute_fiscal_document_type_view.xml
  l10n_it_invoices_data_communication/wizard/export_file.py
  l10n_it_invoices_data_communication/wizard/export_file_view.xml
  l10n_it_invoices_data_communication/wizard/split_big_communication.py
  l10n_it_invoices_data_communication/wizard/split_big_communication_view.xml
  l10n_it_invoices_data_communication_fatturapa/README.rst
  l10n_it_invoices_data_communication_fatturapa/__init__.py
  l10n_it_invoices_data_communication_fatturapa/__manifest__.py
  l10n_it_invoices_data_communication_fatturapa/models/__init__.py
  l10n_it_invoices_data_communication_fatturapa/models/communication.py
  l10n_it_invoices_data_communication_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_invoices_data_communication_fatturapa/readme/DESCRIPTION.rst
  l10n_it_invoices_data_communication_fatturapa/static/description/index.html
  l10n_it_invoices_data_communication_fatturapa/views/communication_view.xml
  setup/l10n_it_invoices_data_communication/odoo/__init__.py
  setup/l10n_it_invoices_data_communication/odoo/addons/__init__.py
  setup/l10n_it_invoices_data_communication/odoo/addons/l10n_it_invoices_data_communication
  setup/l10n_it_invoices_data_communication/setup.py
  setup/l10n_it_invoices_data_communication_fatturapa/odoo/__init__.py
  setup/l10n_it_invoices_data_communication_fatturapa/odoo/addons/__init__.py
  setup/l10n_it_invoices_data_communication_fatturapa/odoo/addons/l10n_it_invoices_data_communication_fatturapa
  setup/l10n_it_invoices_data_communication_fatturapa/setup.py
Labels: approved, needs review

#1200 [12.0] FIX l10n_it_website_portal_fatturapa view dependency
  l10n_it_website_portal_fatturapa/__manifest__.py
  l10n_it_website_portal_fatturapa/views/l10n_it_website_portal_fatturapa_templates.xml
Labels: needs review
