Repository OCA/l10n-italy, pull requests merged in 2019-09, with the labels that each got.

#1443 [12.0] FIX l10n_it_central_journal: msgmerge error
  l10n_it_central_journal/i18n/it.po
Labels: approved, needs review

#1442 [11.0][FIX] l10n_it_fatturapa_out: remove duplicate code
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, ready to merge

#1445 [12.0] FIX l10n_it_ddt: ddt.invoicing wizard
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/tests/test_ddt.py
Labels: approved, needs review

#1432 [11.0][l10n_fatturapa_in] [fix] get fiscal_position_id from partner if set
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review, ready to merge

#1448 [12.0] FIX l10n_it_fatturapa_in when importing XML with 100% discount. See test case
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR05.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#984 [10.0][IMP][l10n_it_fatturapa_in] Format Italian VAT ID to always have 11 chars
  l10n_it_fatturapa_in/tests/data/IT05979361218_012.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1449 [12.0] IMP l10n_it_reverse_charge: write supplier invoice data in self invoice comments
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/tests/test_rc.py
Labels: approved, needs review, ready to merge

#1455 [10.0][FIX] l10n_it_website_portal_fatturapa: Fix electronic invoice label
  l10n_it_website_portal_fatturapa/views/l10n_it_website_portal_fatturapa_templates.xml
Labels: approved

#1468 [12.0] IMP l10n_it_reverse_charge supporting multi company
  l10n_it_reverse_charge/__manifest__.py
  l10n_it_reverse_charge/models/account_rc_type.py
  l10n_it_reverse_charge/security/reverse_charge_security.xml
  l10n_it_reverse_charge/views/account_rc_type_view.xml
Labels: approved, needs review

#1453 [10.0][FIX] l10n_it_fiscal_document_type: Fiscal document type should be al…
  l10n_it_fiscal_document_type/models/account_invoice.py
  l10n_it_fiscal_document_type/tests/test_doc_type.py
Labels: approved, needs review

#1474 [12.0] FIX account_invoice_report_ddt_group ValueError: Expected singleton
  account_invoice_report_ddt_group/models/account_invoice.py
Labels: approved, needs review

#1431 [10.0][IMP] l10n_it_fatturapa_pec: Always e-mail contacts about pec errors
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/company.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA: Invio File 7339338 (broken XML).txt
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: approved, needs review, ready to merge

#1472 [12.0] FIX account_invoice_report_ddt_group when invoicing services
  account_invoice_report_ddt_group/models/account_invoice.py
Labels: approved, needs review
