Repository OCA/l10n-italy, pull requests merged in 2019-11, with the labels that each got.

#1529 [12.0] FIX l10n_it_fiscalcode_crm tests
  l10n_it_fiscalcode_crm/models/crm_lead.py
  l10n_it_fiscalcode_crm/tests/test_lead.py
Labels: approved, needs review

#1532 [FIX] autoinstall
  l10n_it_fatturapa_in_rc/__manifest__.py
Labels: approved

#1535 l10n_it_fatturapa_in_rc: fix auto_install key
  l10n_it_fatturapa_in_rc/__manifest__.py
Labels: approved

#1534 [FIX][l10n_it_withholding_tax] Fixed inaccurate xpath definitions
  l10n_it_withholding_tax/views/account.xml
Labels: approved

#1517 [IMP] Add pyxb version dependency
  setup/l10n_it_fatturapa/setup.py
Labels: approved

#1391 [10.0][l10n_it_fatturapa_in] Fix supporto per la rilevazione degli ar…
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/readme/ROADMAP.rst
  l10n_it_fatturapa_in/tests/data/IT05979361218_013.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge

#1524 [12.0] IMP l10n_it_fatturapa prevent user to create fatturapa.fiscal_position records
  l10n_it_fatturapa/views/company_view.xml
Labels: approved, needs review, ready to merge

#1514 [12.0] ADD l10n_it_pos_fiscalcode
  l10n_it_pos_fiscalcode/__init__.py
  l10n_it_pos_fiscalcode/__manifest__.py
  l10n_it_pos_fiscalcode/readme/CONTRIBUTORS.rst
  l10n_it_pos_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_pos_fiscalcode/static/src/js/models.js
  l10n_it_pos_fiscalcode/static/src/xml/pos.xml
  l10n_it_pos_fiscalcode/views/assets.xml
Labels: approved, needs review

#1516 [IMP] Add pyxb version dependency
  setup/l10n_it_fatturapa/setup.py
Labels: approved, ready to merge

#1537 [12.0] IMP l10n_it_fatturapa_in: use last due date for invoice due date, if supplier payment term is not set
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review, ready to merge
