Repository OCA/l10n-italy, pull requests merged in 2019-05, with the labels that each got.

#1180 [10.0][IMP] add pyxb version dependency
  setup/l10n_it_fatturapa/setup.py
Labels: approved, needs review

#1210 [12.0] IMP l10n_it_ddt error messages and do not block if SO has not shipping info
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/wizard/add_picking_to_ddt.py
Labels: approved, needs review

#1213 [12.0] FIX l10n_it_ddt: send by email
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/data/mail_template_data.xml
  l10n_it_ddt/models/stock_picking_package_preparation.py
Labels: approved, needs review

#1036 [10.0][l10n_it_fatturapa] Add support to multiple invoice preview formats
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/readme/CONFIGURE.rst
  l10n_it_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa/views/company_view.xml
Labels: approved, needs review

#1214 [12.0] IMP account_vat_period_end_statement report: do not print rows with zero values
  account_vat_period_end_statement/__manifest__.py
  account_vat_period_end_statement/views/report_vatperiodendstatement.xml
Labels: approved, needs review

#1205 [10.0][FIX] l10n_it_fatturapa_out: DatiRiepilogo is mandatory but tax_line_ids is not required
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review

#1234 [10.0] [FIX] l10n_it_central_journal: Use journals to filter move lines
  l10n_it_central_journal/__manifest__.py
  l10n_it_central_journal/wizard/print_giornale.py
Labels: approved

#1050 [12.0] l10n_it_fattura: migration to pyxb 1.2.6
  .travis.yml
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/bindings/FatturaPA_versione_1.2.1.xsd.diff
  l10n_it_fatturapa/bindings/README.md
  l10n_it_fatturapa/bindings/__init__.py
  l10n_it_fatturapa/bindings/_ds.py
  l10n_it_fatturapa/bindings/fatturapa_v_1_2.py
  l10n_it_fatturapa/readme/INSTALL.rst
  l10n_it_fatturapa/static/description/index.html
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.xml
Labels: approved, needs review, ready to merge

#1237 [FIX] l10n_it_ddt: fix https://github.com/OCA/l10n-italy/issues/1236
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/views/report_ddt.xml
Labels: approved

#1235 [12.0] FIX l10n_it_ddt: in DDT report, partner addresses are not printed
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/views/report_ddt.xml
Labels: approved, needs review

#1142 IMP l10n_it_fatturapa allowing to specify 'ODOO' code prefix in XML, fixed version and readme
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/readme/CONFIGURE.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#1197 [12.0] ADD l10n_it_vat_statement_communication
  l10n_it_vat_statement_communication/README.rst
  l10n_it_vat_statement_communication/__init__.py
  l10n_it_vat_statement_communication/__manifest__.py
  l10n_it_vat_statement_communication/data/comunicazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornituraIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornitura_v3.xsd
  l10n_it_vat_statement_communication/data/intestazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/typesDati_v3.xsd
  l10n_it_vat_statement_communication/data/typesProvincie_v3.xsd
  l10n_it_vat_statement_communication/i18n/it.po
  l10n_it_vat_statement_communication/models/__init__.py
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
  l10n_it_vat_statement_communication/readme/CONTRIBUTORS.rst
  l10n_it_vat_statement_communication/readme/DESCRIPTION.rst
  l10n_it_vat_statement_communication/readme/USAGE.rst
  l10n_it_vat_statement_communication/security/ir.model.access.csv
  l10n_it_vat_statement_communication/security/security.xml
  l10n_it_vat_statement_communication/static/description/index.html
  l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
  l10n_it_vat_statement_communication/wizard/__init__.py
  l10n_it_vat_statement_communication/wizard/export_file.py
  l10n_it_vat_statement_communication/wizard/export_file_view.xml
  setup/l10n_it_vat_statement_communication/odoo/addons/l10n_it_vat_statement_communication
  setup/l10n_it_vat_statement_communication/setup.py
Labels: needs review

#1065 [12.0] mig l10n_it_fatturapa_export_zip
  l10n_it_fatturapa_export_zip/README.rst
  l10n_it_fatturapa_export_zip/__init__.py
  l10n_it_fatturapa_export_zip/__manifest__.py
  l10n_it_fatturapa_export_zip/models/__init__.py
  l10n_it_fatturapa_export_zip/models/attachment.py
  l10n_it_fatturapa_export_zip/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_export_zip/readme/DESCRIPTION.rst
  l10n_it_fatturapa_export_zip/static/description/index.html
  l10n_it_fatturapa_export_zip/views/attachment_view.xml
  l10n_it_fatturapa_export_zip/wizard/__init__.py
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa_view.xml
Labels: needs review

#946 [8.0][BKP] l10n_it_fatturapa_out_triple_discount
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_triple_discount/README.rst
  l10n_it_fatturapa_out_triple_discount/__init__.py
  l10n_it_fatturapa_out_triple_discount/__openerp__.py
  l10n_it_fatturapa_out_triple_discount/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_triple_discount/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_triple_discount/static/description/index.html
  l10n_it_fatturapa_out_triple_discount/tests/__init__.py
  l10n_it_fatturapa_out_triple_discount/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_triple_discount/tests/test_fatturapa_triple_discount.py
  l10n_it_fatturapa_out_triple_discount/wizard/__init__.py
  l10n_it_fatturapa_out_triple_discount/wizard/wizard_export_fatturapa.py
  oca_dependencies.txt
Labels: needs review

#1242 [10.0][FIX] l10n_it_invoices_data_communication: cessionario cedente
  l10n_it_invoices_data_communication/__manifest__.py
  l10n_it_invoices_data_communication/models/communication.py
Labels: approved, needs review

#965 [8.0][IMP] add module to create automatically sale order related docs…
  l10n_it_fatturapa_out_sale/README.rst
  l10n_it_fatturapa_out_sale/__init__.py
  l10n_it_fatturapa_out_sale/__openerp__.py
  l10n_it_fatturapa_out_sale/models/__init__.py
  l10n_it_fatturapa_out_sale/models/account_invoice.py
  l10n_it_fatturapa_out_sale/models/partner.py
  l10n_it_fatturapa_out_sale/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_sale/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_sale/static/description/index.html
  l10n_it_fatturapa_out_sale/views/account_view.xml
  l10n_it_fatturapa_out_sale/views/partner_view.xml
  l10n_it_fatturapa_out_sale/wizard/__init__.py
  l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
Labels: approved

#1246 [10.0][FIX] l10n_it_fatturapa_out: DettaglioPagamento creation
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved

#1121 [10.0][FIX][l10n_it_fatturapa_in] Set the supplier flag only where necessary
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#1168 [11.0][FIX][l10n_it_fatturapa_in] Set the supplier flag only where necessary
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, needs review

#1226 [FIX] l10n_it_fatturapa_out: DatiRiepilogo is mandatory but tax_line_…
  l10n_it_fatturapa_out/__openerp__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: needs review

#1209 [10.0][IMP] l10n_it_fatturapa_in: Overwrite supplier invoice data when importing
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1181 [10.0] [l10n_it_rea] Use rea_office in sql_constraints to avoid 'false' uniqueness
  l10n_it_rea/__manifest__.py
  l10n_it_rea/models/res_partner.py
Labels: approved

#1239 [12.0] IMP account_vat_period_end_statement preventing to manually add lines to debit and credit VAT
  account_vat_period_end_statement/__manifest__.py
  account_vat_period_end_statement/models/account.py
Labels: approved, needs review, ready to merge
