Repository OCA/l10n-italy, pull requests merged in 2020-12, with the labels that each got.

#1751 [12.0][FIX] l10n_it_intrastat_statement: Different statement produced for month/quarter, refactoring
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat_statement/__manifest__.py
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_section.py
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
  l10n_it_intrastat_statement/tests/__init__.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
Labels: approved, bot is merging ⏳, ready to merge

#1966 [12.0] [FIX] spazi finali in PECDestinatario
  l10n_it_fatturapa/bindings/fatturapa.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20005.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, bot is merging ⏳, ready to merge

#1723 [11.0][MIG] l10n_it_vat_statement_communication: backport from 12
  l10n_it_vat_statement_communication/README.rst
  l10n_it_vat_statement_communication/__init__.py
  l10n_it_vat_statement_communication/__manifest__.py
  l10n_it_vat_statement_communication/data/comunicazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornituraIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornitura_v3.xsd
  l10n_it_vat_statement_communication/data/intestazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/typesDati_v3.xsd
  l10n_it_vat_statement_communication/data/typesProvincie_v3.xsd
  l10n_it_vat_statement_communication/i18n/it.po
  l10n_it_vat_statement_communication/i18n/l10n_it_vat_statement_communication.pot
  l10n_it_vat_statement_communication/migrations/12.0.1.1.0/post-migrate.py
  l10n_it_vat_statement_communication/models/__init__.py
  l10n_it_vat_statement_communication/models/account.py
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
  l10n_it_vat_statement_communication/models/config.py
  l10n_it_vat_statement_communication/readme/CONFIGURE.rst
  l10n_it_vat_statement_communication/readme/CONTRIBUTORS.rst
  l10n_it_vat_statement_communication/readme/DESCRIPTION.rst
  l10n_it_vat_statement_communication/readme/USAGE.rst
  l10n_it_vat_statement_communication/security/ir.model.access.csv
  l10n_it_vat_statement_communication/security/security.xml
  l10n_it_vat_statement_communication/static/description/icon.png
  l10n_it_vat_statement_communication/static/description/index.html
  l10n_it_vat_statement_communication/views/account.xml
  l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
  l10n_it_vat_statement_communication/views/config.xml
  l10n_it_vat_statement_communication/wizard/__init__.py
  l10n_it_vat_statement_communication/wizard/export_file.py
  l10n_it_vat_statement_communication/wizard/export_file_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1976 [FIX] double attach in fatturapa out xml
  l10n_it_fatturapa_out/models/attachment.py
Labels: approved, bot is merging ⏳

#1964 [FIX][l10n_it_vat_statement_split_payment]
  l10n_it_vat_statement_split_payment/models/statement.py
  l10n_it_vat_statement_split_payment/tests/test_vat_statement_split.py
Labels: approved, bot is merging ⏳, ready to merge

#1914 [12.0][FIX] migration e-invoice 1.6
  l10n_it_fatturapa_in/migrations/12.0.1.19.0/post-migration.py
  l10n_it_fatturapa_in/migrations/12.0.2.0.0/post-migration.py
  l10n_it_fatturapa_in/migrations/12.0.2.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, ready to merge

#1895 [12.0][IMP] Add cig-cup compatibility for riba
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/models/riba.py
  l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
  l10n_it_ricevute_bancarie/tests/riba_common.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/riba_detail_view.xml
  l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
  l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py
Labels: bot is merging ⏳

#1981 [12.0][FIX] l10n_it_fatturapa_pec: Fix test_sender_error
  l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
Labels: approved, bot is merging ⏳

#1970 [8.0][REF] l10n_it_fatturapa_in: correctly handling new Ritenuta codes
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR13.xml
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20001.xml
  l10n_it_fatturapa_in/tests/data/ITNREGCM80H30D612D_20003.xml
  l10n_it_fatturapa_in/tests/data/ITNREGCM80H30D612D_20004.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: merged 🎉

#1977 [12.0] [FIX] show stamp duty parameters in manual mode
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/views/product_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1911 [12.0][IMP] add tracking ref carrier and dimension
  l10n_it_ddt/models/account.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/tests/test_ddt.py
  l10n_it_ddt/views/account.xml
  l10n_it_ddt/views/stock_picking_package_preparation.xml
Labels: approved, bot is merging ⏳, ready to merge

#1994 [12.0][IMP] ability to link already open vendor invoices from xml received
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
Labels: bot is merging ⏳

#1995 [UPD][l10n_it_invoices_data_communication] remove intrastat dependance
  l10n_it_invoices_data_communication/__manifest__.py
  l10n_it_invoices_data_communication/data/res_country_data.xml
  l10n_it_invoices_data_communication/models/__init__.py
  l10n_it_invoices_data_communication/models/res_country.py
  l10n_it_invoices_data_communication/views/res_country_view.xml
Labels: approved, bot is merging ⏳

#1980 [12.0][IMP] l10n_it_account: Fix multi-locations installed
  l10n_it_account/models/__init__.py
  l10n_it_account/models/account_group.py
  l10n_it_account/models/res_company.py
  l10n_it_account/readme/CONTRIBUTORS.rst
  l10n_it_account/tests/test_l10n_it_account.py
Labels: approved, bot is merging ⏳, ready to merge

#2004 [8.0][FIX] l10n_it_fatturapa: electronic_invoice_no_contact_update field view
  l10n_it_fatturapa/views/partner_view.xml
Labels: bot is merging ⏳

#2000 [12.0][FIX] vat with extra chars
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2008 [8.0][FIX] l10n_it_fatturapa_in: remove spaces into Email and PECDestinatario tags
  l10n_it_fatturapa/bindings/fatturapa.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20005.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: bot is merging ⏳
