Repository OCA/l10n-italy, pull requests merged in 2020-11, with the labels that each got.

#1920 [10.0 fix] l10n_it_intrastat_statement: ValueError: External ID not found in the system: web.internal_layout
  l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
  l10n_it_intrastat_statement/report/intrastat_mod1_ter.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod1.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
Labels: approved, bot is merging ⏳, ready to merge

#1811 [10.0][BKP] l10n_it_dichiarazione_intento: Backporting da 12.0
  l10n_it_dichiarazione_intento/README.rst
  l10n_it_dichiarazione_intento/__init__.py
  l10n_it_dichiarazione_intento/__manifest__.py
  l10n_it_dichiarazione_intento/data/sequence.xml
  l10n_it_dichiarazione_intento/i18n/it.po
  l10n_it_dichiarazione_intento/i18n/l10n_it_dichiarazione_intento.pot
  l10n_it_dichiarazione_intento/models/__init__.py
  l10n_it_dichiarazione_intento/models/account.py
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/models/company.py
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
  l10n_it_dichiarazione_intento/models/product.py
  l10n_it_dichiarazione_intento/models/sale.py
  l10n_it_dichiarazione_intento/readme/CONFIGURE.rst
  l10n_it_dichiarazione_intento/readme/CONTRIBUTORS.rst
  l10n_it_dichiarazione_intento/readme/DESCRIPTION.rst
  l10n_it_dichiarazione_intento/readme/USAGE.rst
  l10n_it_dichiarazione_intento/security/ir.model.access.csv
  l10n_it_dichiarazione_intento/static/description/icon.png
  l10n_it_dichiarazione_intento/static/description/index.html
  l10n_it_dichiarazione_intento/tests/__init__.py
  l10n_it_dichiarazione_intento/tests/test_account.py
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
  l10n_it_dichiarazione_intento/views/account_invoice_view.xml
  l10n_it_dichiarazione_intento/views/account_view.xml
  l10n_it_dichiarazione_intento/views/company_view.xml
  l10n_it_dichiarazione_intento/views/dichiarazione_intento_view.xml
  l10n_it_dichiarazione_intento/wizard/__init__.py
  l10n_it_dichiarazione_intento/wizard/manually_declarations.py
  l10n_it_dichiarazione_intento/wizard/manually_declarations_view.xml
Labels: bot is merging ⏳

#1947 [12.0][FIX][l10n_it_fatturapa] URL in Readme doesn't work
  l10n_it_fatturapa/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1944 [12.0] Aggiunto livello importazione XML fattura elettronica basato sul riepilogo
  l10n_it_fatturapa_in/models/partner.py
  l10n_it_fatturapa_in/tests/data/IT05979361218_ripilogoiva.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#1565 [IMP][10.0] Ottimizza il metodo di generazione fatture elettroniche
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/models/__init__.py
  l10n_it_fatturapa_out/models/company.py
  l10n_it_fatturapa_out/models/partner.py
  l10n_it_fatturapa_out/views/account_view.xml
  l10n_it_fatturapa_out/views/company_view.xml
  l10n_it_fatturapa_out/views/partner_view.xml
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/tests/e_invoice_common.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
  l10n_it_fatturapa_pec/views/account.xml
  l10n_it_fatturapa_pec/wizard/__init__.py
  l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa_view.xml
Labels: approved, bot is merging ⏳, needs review

#1953 [FIX] l10n_it_ipa: fix REAME file
  l10n_it_ipa/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#1940 [12.0] REF l10n_it_fatturapa_in correctly handling new Ritenuta codes
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR13.xml
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20001.xml
  l10n_it_fatturapa_in/tests/data/ITNREGCM80H30D612D_20003.xml
  l10n_it_fatturapa_in/tests/data/ITNREGCM80H30D612D_20004.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳, ready to merge

#1954 [IMP] l10n_it_ipa: adapt module to https://www.odoo-italia.org/documentazione/12.0/sviluppo/guidelines.html
  l10n_it_ipa/__manifest__.py
  l10n_it_ipa/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#1859 [12.0] Permettere di rigenerare il file XML per le fatture elettroniche in stato di errore
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/models/__init__.py
  l10n_it_fatturapa_out/models/company.py
  l10n_it_fatturapa_out/models/partner.py
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/views/company_view.xml
  l10n_it_fatturapa_out/views/partner_view.xml
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/tests/e_invoice_common.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
  l10n_it_fatturapa_pec/views/account.xml
  l10n_it_fatturapa_pec/wizard/__init__.py
  l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa_view.xml
Labels: bot is merging ⏳

#1948 [12.0][FIX] l10n_it_fatturapa_sale access groups
  l10n_it_fatturapa_sale/models/sale_order.py
  l10n_it_fatturapa_sale/models/sale_order_line.py
  l10n_it_fatturapa_sale/views/sale_order_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1961 [12.0] [FIX] fiscal_epos_print wrong computation of manual discount
  fiscal_epos_print/static/src/js/epson_epos_print.js
Labels: approved, bot is merging ⏳, ready to merge
