Repository OCA/l10n-italy, pull requests merged in 2020-09, with the labels that each got.

#1852 [12.0] IMP l10n_it_fiscal_payment_term preventing user to create new fatturapa.payment_method or fatturapa.payment_term
  l10n_it_fiscal_payment_term/views/account_view.xml
Labels: approved, bot is merging ⏳, needs review

#1844 [FIX] l10n_it_ddt: ddt_show_price did not spread in TD
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/migrations/12.0.1.7.1/pre-migrate.py
  l10n_it_ddt/models/partner.py
  l10n_it_ddt/models/sale.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/tests/test_ddt.py
  l10n_it_ddt/views/report_ddt.xml
  l10n_it_ddt/views/sale.xml
  l10n_it_ddt/views/stock_picking_package_preparation.xml
  l10n_it_ddt/wizard/ddt_from_picking.py
Labels: approved, bot is merging ⏳, ready to merge

#1829 [FIX] [12.0] l10n_it_dichiarazione_intento - gestione assegnazione automatica posizione fiscale in fattura
  l10n_it_dichiarazione_intento/__manifest__.py
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
  l10n_it_dichiarazione_intento/readme/CONTRIBUTORS.rst
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
  l10n_it_dichiarazione_intento/views/account_invoice_view.xml
  l10n_it_dichiarazione_intento/wizard/manually_declarations.py
Labels: approved, bot is merging ⏳

#1846 [IMP] l10n_it_ddt: show number of TDs linked to the sale order
  l10n_it_ddt/models/sale.py
  l10n_it_ddt/views/sale.xml
Labels: bot is merging ⏳

#1708 [12.0][ADD] l10n_it_fatturapa_sale
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/tests/test_ddt.py
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa/views/account_view.xml
  l10n_it_fatturapa/views/related_document_type_views.xml
  l10n_it_fatturapa_sale/__init__.py
  l10n_it_fatturapa_sale/__manifest__.py
  l10n_it_fatturapa_sale/i18n/it.po
  l10n_it_fatturapa_sale/models/__init__.py
  l10n_it_fatturapa_sale/models/account_invoice.py
  l10n_it_fatturapa_sale/models/account_invoice_line.py
  l10n_it_fatturapa_sale/models/related_document.py
  l10n_it_fatturapa_sale/models/sale_order.py
  l10n_it_fatturapa_sale/models/sale_order_line.py
  l10n_it_fatturapa_sale/readme/DESCRIPTION.rst
  l10n_it_fatturapa_sale/tests/__init__.py
  l10n_it_fatturapa_sale/tests/test_fatturapa_sale.py
  l10n_it_fatturapa_sale/views/related_document_type_views.xml
  l10n_it_fatturapa_sale/views/sale_order_line_views.xml
  l10n_it_fatturapa_sale/views/sale_order_views.xml
  setup/l10n_it_fatturapa_sale/odoo/addons/l10n_it_fatturapa_sale
  setup/l10n_it_fatturapa_sale/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1865 [12.0][IMP] l10n it account tax kind fatturapa 1.6
  l10n_it_account_tax_kind/data/account.tax.kind.csv
  l10n_it_account_tax_kind/model/account_tax_kind.py
  l10n_it_fatturapa/models/account.py
Labels: e-invoice 1.6

#1866 [12.0][IMP] importo bollo non più obbligatorio e-invoice 1.6
  l10n_it_fatturapa_out_stamp/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_stamp/wizard/wizard_export_fatturapa.py
Labels: e-invoice 1.6

#1864 [12.0][IMP] aggiunti fiscal document types fatturapa 1.6
  l10n_it_fiscal_document_type/data/fiscal.document.type.csv
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
Labels: e-invoice 1.6

#1871 [10.0][FIX] l10n_it_intrastat_statement: Different statement produced for month/quarter, refactoring
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat_statement/__manifest__.py
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_section.py
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
Labels: bot is merging ⏳

#1883 [12.0] Eccezione durante l'esecuzione dei test
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: approved, bot is merging ⏳

#1885 [12.0] [FIX] l10n_it_fatturapa_in: IstitutoFinanziario and BIC are not mandatory in XML
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳, needs review

#1886 [12.0] FIX l10n_it_fatturapa_out: when bank account is not an IBAN, don't write in XML; otherwise XML is not valid
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳, needs review

#1889 fixed fpdeptax field in fiscal_epos_print module to accept 2 digits
  fiscal_epos_print/__manifest__.py
  fiscal_epos_print/models/account.py
Labels: approved, bot is merging ⏳

#1892 [12.0] FIX license LGPL-3 conflicts
  fiscal_epos_print/__manifest__.py
  l10n_it_central_journal/__init__.py
  l10n_it_central_journal/models/__init__.py
  l10n_it_central_journal/models/account.py
  l10n_it_central_journal/models/central_journal.py
  l10n_it_central_journal/wizard/__init__.py
  l10n_it_central_journal/wizard/print_giornale.py
  l10n_it_codici_carica/models/codice_carica.py
  l10n_it_corrispettivi/__init__.py
  l10n_it_corrispettivi/controllers/__init__.py
  l10n_it_corrispettivi/controllers/main.py
  l10n_it_corrispettivi/data/account_journal_data.xml
  l10n_it_corrispettivi/models/__init__.py
  l10n_it_corrispettivi/models/account.py
  l10n_it_corrispettivi/tests/__init__.py
  l10n_it_corrispettivi/tests/test_corrispettivi.py
  l10n_it_corrispettivi/views/account_report.xml
  l10n_it_corrispettivi/views/account_view.xml
  l10n_it_corrispettivi/wizards/__init__.py
  l10n_it_corrispettivi/wizards/account_invoice_refund.py
  l10n_it_fatturapa_out_triple_discount/__init__.py
  l10n_it_fatturapa_out_triple_discount/wizards/__init__.py
  l10n_it_fiscal_document_type/__init__.py
  l10n_it_fiscal_document_type/__manifest__.py
  l10n_it_fiscal_document_type/tests/__init__.py
  l10n_it_fiscal_document_type/tests/test_doc_type.py
  l10n_it_reverse_charge/__init__.py
  l10n_it_reverse_charge/models/__init__.py
  l10n_it_reverse_charge/models/account_fiscal_position.py
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/models/account_rc_type.py
  l10n_it_reverse_charge/tests/__init__.py
  l10n_it_reverse_charge/tests/test_rc.py
  l10n_it_reverse_charge/views/account_fiscal_position_view.xml
  l10n_it_reverse_charge/views/account_invoice_view.xml
  l10n_it_reverse_charge/views/account_rc_type_view.xml
  l10n_it_vat_statement_communication/__manifest__.py
  l10n_it_website_sale_fiscalcode/__init__.py
  l10n_it_website_sale_fiscalcode/__manifest__.py
  l10n_it_website_sale_fiscalcode/controllers/__init__.py
  l10n_it_website_sale_fiscalcode/controllers/main.py
  l10n_it_website_sale_fiscalcode/views/templates.xml
Labels: approved, bot is merging ⏳

#1890 [12.0][FIX] sale order is a datetime but dichiarazione d'intento dates are date
  l10n_it_dichiarazione_intento/models/sale.py
Labels: approved, bot is merging ⏳
