Repository OCA/l10n-italy, pull requests merged in 2020-08, with the labels that each got.

#1842 FIX l10n_it_vat_statement_communication when setting declarant_fiscalcode_company
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, bot is merging ⏳, needs review

#1847 [12.0][IMP] add invoices date to fatturapa in view
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, bot is merging ⏳

#1832 [12.0] IMP l10n_it_fatturapa_pec seding notifications of errors immediatly.
  l10n_it_fatturapa_pec/models/fetchmail.py
Labels: bot is merging ⏳, needs review

#1850 [12.0][FIX] trailing whitespaces in xml data
  l10n_it_fatturapa/bindings/fatturapa.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR05.xml
Labels: approved, bot is merging ⏳, bugfix, help wanted

#1853 [12.0][FIX] italian date format
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, bot is merging ⏳, ready to merge

#1854 [12.0][FIX] Dichiarazione intento multipla
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
  l10n_it_dichiarazione_intento/models/sale.py
Labels: approved, bot is merging ⏳
