Repository OCA/l10n-italy, pull requests merged in 2020-02, with the labels that each got.

#1363 [10.0][IMP][l10n_it_fatturapa_in] Set the supplier invoice bill regis…
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: approved, ready to merge

#1620 [12.0] FIX l10n_it_ddt: accessing to invoice without inventory permissions
  l10n_it_ddt/security/ir.model.access.csv
Labels: approved, needs review

#1627 [12.0][FIX] l10n_it_corrispettivi_sale - prevent update corrispettivi if fiscal_position doesn't exists
  l10n_it_corrispettivi_sale/models/sale.py
  l10n_it_corrispettivi_sale/readme/CONTRIBUTORS.rst
Labels: approved

#1456 [8.0][FIX] get fiscal_position_id from partner if set
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved

#1404 [11.0][FIX] l10n_it_fatturapa: Remove newlines from base64 file before decoding
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.base64.xml.p7m
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, ready to merge

#1626 12.0 [FIX][l10n_it_account] Lesser fix to account.group 'get_group_parents' method (now correctly checking for parenting recursion)
  l10n_it_account/models/account_group.py
Labels: approved

#1638 [12.0][ADD]column invoice_id in riba tree view
  l10n_it_ricevute_bancarie/views/account_view.xml
Labels: approved

#1636 12.0 - Fix in query sql
  l10n_it_central_journal/wizard/print_giornale.py
Labels: 12.0, approved

#1631 [12.0][FIX] l10n_it_corrispettivi, fix journal on partner change
  l10n_it_corrispettivi/models/account.py
  l10n_it_corrispettivi/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge

#1635 [12.0][FIX] fiscal_epos_print: Formato data del reso
  fiscal_epos_print/__manifest__.py
  fiscal_epos_print/static/src/js/popups.js
Labels: approved, ready to merge

#1624 [12.0] IMP l10n_it_fatturapa_in when XML contains DatiRitenuta but suppliers did not set Ritenuta for any line
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR08.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: needs review

#1648 [12.0][FIX] intrastat_statement: transport code value in purchase section
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
Labels: approved

#1436 [10.0][IMP][l10n_it_central_journal]
  l10n_it_central_journal/views/report_account_central_journal.xml
  l10n_it_central_journal/wizard/print_giornale.py
Labels: approved

#1634 [10.0] Aggiunta possibilità di scelta della data di default in cui registrare le fatture di acquisto generate da xml
  l10n_it_fatturapa_in/models/company.py
  l10n_it_fatturapa_in/views/company_view.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: needs review

#1647 [12.0] gestione acconto in liquidazione IVA + VP14 non compilato per trimestrali nel 4° trimestre
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/tests/test_vat_statement.py
  account_vat_period_end_statement/views/account_view.xml
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, needs review, ready to merge

#1655 [12.0] IMP fiscal_epos_print removing lines with quantity = 0, as not allowed by fiscal printer
  fiscal_epos_print/static/src/js/models.js
Labels: approved, needs review

#1641 [IMP] 10.0 - Possibilità di modificare numero di pagina nel footer registro iva in base all'anno indicato nel campo year_footer
  l10n_it_account/reports/account_reports_view.xml
  l10n_it_vat_registries/models/vat_registry.py
  l10n_it_vat_registries/report/report_registro_iva.xml
  l10n_it_vat_registries/wizard/print_registro_iva.py
  l10n_it_vat_registries/wizard/print_registro_iva.xml
  l10n_it_vat_registries_cash_basis/wizard/print_registro_iva.py
Labels: approved, ready to merge

#1658 [12.0] FIX l10n_it_vat_statement_communication adding "Down payment computation method" to be set when "Down payment due" is set
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
  l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
  l10n_it_vat_statement_communication/wizard/export_file.py
Labels: needs review
