Repository OCA/l10n-italy, pull requests merged in 2020-10, with the labels that each got.

#1903 Use correct english terms, from APPENDIX A -TECHNICAL SPECIFICATIONS
  l10n_it_esigibilita_iva/models/account.py
  l10n_it_fatturapa/models/account.py
Labels: approved, bot is merging ⏳

#1902 [12.0][FIX] put higher sequence to expense riba line
  l10n_it_ricevute_bancarie/models/account/account.py
Labels: bot is merging ⏳

#1907 [12.0] IMP l10n_it_invoices_data_communication handling new RC codes from 1.6 version
  l10n_it_invoices_data_communication/models/account_invoice.py
Labels: bot is merging ⏳

#1544 [8.0] encode_for_export per l10n_it_fatturapa_out + l10n_it_invoices_data_communication
  account_invoice_entry_date/models/account.py
  l10n_it_account/__init__.py
  l10n_it_account/tools/__init__.py
  l10n_it_account/tools/account_tools.py
  l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml
  l10n_it_fatturapa_out/__openerp__.py
  l10n_it_fatturapa_out/data/l10n_it_fatturapa_out_data.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00011.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_invoices_data_communication/__openerp__.py
  l10n_it_invoices_data_communication/models/communication.py
Labels: bot is merging ⏳

#1818 [12.0] IMP fiscal_epos_print allowing to save in pos order debug info returned by fiscal printer
  fiscal_epos_print/models/pos_order.py
  fiscal_epos_print/static/src/js/epson_epos_print.js
  fiscal_epos_print/static/src/js/models.js
  fiscal_epos_print/views/point_of_sale.xml
Labels: bot is merging ⏳

#1879 [12.0] ADD l10n_it_fiscalcode_sale: Mostra il codice fiscale del cliente nella stampa del preventivo
  l10n_it_fiscalcode_sale/__init__.py
  l10n_it_fiscalcode_sale/__manifest__.py
  l10n_it_fiscalcode_sale/i18n/it.po
  l10n_it_fiscalcode_sale/readme/CONTRIBUTORS.rst
  l10n_it_fiscalcode_sale/readme/DESCRIPTION.rst
  l10n_it_fiscalcode_sale/views/sale_order_report.xml
  setup/l10n_it_fiscalcode_sale/odoo/addons/l10n_it_fiscalcode_sale
  setup/l10n_it_fiscalcode_sale/setup.py
Labels: bot is merging ⏳, needs review

#1910 [12.0] FIX fiscal_epos_print when setting debug info when order is not set
  fiscal_epos_print/static/src/js/epson_epos_print.js
Labels: approved, bot is merging ⏳, needs review

#1855 [12.0][FIX] create field to exclude recomputation of old invoices
  l10n_it_fatturapa_in/migrations/12.0.1.18.3/pre-migration.py
Labels: approved, bot is merging ⏳, ready to merge

#1171 [11.0][l10n_it_fatturapa] Add support to multiple invoice preview formats
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/readme/CONFIGURE.rst
  l10n_it_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa/views/company_view.xml
Labels: merged 🎉, needs review

#1675 11.0 fatturapa in: search by VAT and CF
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳, needs review

#1661 [11.0] [FIX][l10n_it_reverse_charge]
  l10n_it_reverse_charge/models/account_invoice.py
Labels: bot is merging ⏳

#1906 [12.0] IMP l10n_it_fatturapa_in_rc: handling new RC codes from 1.6 version
  l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳, needs review

#1687 11.0 FIX l10n_it_account_stamp
  l10n_it_account_stamp/models/invoice.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/views/product_view.xml
Labels: bot is merging ⏳

#1593 11.0 upd l10n it vat registries
  l10n_it_vat_registries/models/account_tax_registry.py
  l10n_it_vat_registries/models/vat_registry.py
  l10n_it_vat_registries/report/report_registro_iva.xml
  l10n_it_vat_registries/security/vat_registry_security.xml
  l10n_it_vat_registries/views/account_journal_view.xml
  l10n_it_vat_registries/views/account_tax_registry_view.xml
  l10n_it_vat_registries/views/account_view.xml
  l10n_it_vat_registries/wizard/print_registro_iva.py
  l10n_it_vat_registries/wizard/print_registro_iva.xml
Labels: approved, bot is merging ⏳, ready to merge

#1838 [12.0] IMP l10n_it_sdi_channel when sending normal emails without expliciting SMTP server: the e-invoice PEC server must not be used
  l10n_it_sdi_channel/models/ir_mail_server.py
Labels: approved, bot is merging ⏳, needs review

#1918 [12.0] [FIX] l10n_it_fatturapa_out_ddt use of more appropriate source term
  l10n_it_fatturapa_out_ddt/__manifest__.py
  l10n_it_fatturapa_out_ddt/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_ddt/readme/USAGE.rst
  l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#1894 [12.0] IMP l10n_it_fiscal_document_type allowing to search records by code and showing code in relational fields
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
Labels: bot is merging ⏳, needs review
