Repository OCA/l10n-italy, pull requests merged in 2020-03, with the labels that each got.

#1551 [IMP] 11.0 - Order data on central journal and print line name or partner name
  l10n_it_central_journal/views/report_account_central_journal.xml
  l10n_it_central_journal/wizard/print_giornale.py
Labels: approved

#1664 [12.0] FIX l10n_it_vat_statement_communication: I contribuenti che hanno optato per la liquidazione trimestrale ai sensi dell’art. 7 del D.P.R. n. 542/99 devono indicare “5” per il quarto trimestre
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, needs review

#1663 [12.0] FIX l10n_it_vat_statement_communication: TypeError: Argument must be bytes or unicode, got 'int'
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, needs review

#1673 [10.0] libro giornale anno footer
  l10n_it_central_journal/models/central_journal.py
  l10n_it_central_journal/views/report_account_central_journal.xml
  l10n_it_central_journal/wizard/print_giornale.py
  l10n_it_central_journal/wizard/print_giornale.xml
Labels: approved

#1654 [12.0] IMP account_vat_period_end_statement allowing to create an annual prospect, without accounting entries
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/views/account_view.xml
Labels: needs review

#1677 12.0 comunicazione dati iva: esterometro
  l10n_it_invoices_data_communication/models/communication.py
  l10n_it_invoices_data_communication/views/comunicazione.xml
Labels: approved, ready to merge

#1660 12.0 [FIX][l10n_it_fatturapa_in] Fix partner search to be multicompany-com…
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge

#1684 [12.0] Annual prospect of VAT statement: do not compute previous credits. Add annual field to list and search view
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/views/account_view.xml
Labels: needs review

#1680 [10.0] FIX attach state on EC01 email text result
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
Labels: approved, needs review, ready to merge

#1690 [12.0] IMP l10n_it_fatturapa_out making your company messages more clear
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, needs review, ready to merge

#1683 [10.0][FIX] l10n_it_fatturapa_pec: Find fatturapa_attachment_out res by signed attach_name
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: needs review

#1652 [10.0][FIX] l10n_it_central_journal: Break long words in fields that can contain them
  l10n_it_central_journal/__manifest__.py
  l10n_it_central_journal/views/report_account_central_journal.xml
Labels: approved, ready to merge

#1611 [12.0][FIX] Dichiarazione Intrastat: Arrotondamenti a 1 in caso di valore inferiore a zero (AMMONT. EURO, VALORE STATIST, MASSA NETTA, UNITA' SUPPL)
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
Labels: approved

#1704 [12.0] IMP l10n_it_sdi_channel hiding "web server" fields ad attrs is not applicable to tree view
  l10n_it_sdi_channel/views/sdi_view.xml
Labels: approved, needs review

#1710 [12.0] Una partita IVA e più codici destinatario per le diverse attività esercitate
  l10n_it_fatturapa/models/partner.py
  l10n_it_fatturapa/views/partner_view.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00012.xml
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳, needs review

#1703 [8.0][FIX] action cancel bad name
  l10n_it_fatturapa_out/models/account.py
Labels: 8.0, bot is merging ⏳

#1707 [12.0] IMP l10n_it_ddt allowing to show lot deadline in DDT report
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/views/report_ddt.xml
  l10n_it_ddt/views/stock_picking_package_preparation.xml
Labels: approved, bot is merging ⏳, needs review
