Repository OCA/l10n-italy, pull requests merged in 2020-07, with the labels that each got.

#1812 [12.0] IMP l10n_it_fatturapa_pec notifying errors using email subject instead of message-id
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: approved, bot is merging ⏳, ready to merge

#1817 [12.0][FIX] l10n_it_dichiarazione_intento: test per nota di credito che supera plafond
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: bot is merging ⏳

#1820 [12.0] [FIX] Find fatturapa_attachment_out res by signed attach_name
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: bot is merging ⏳, needs review

#1821 [12.0] [FIX] attach state on EC01 email text result
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
Labels: bot is merging ⏳

#1805 [12.0] FIX l10n_it_fatturapa_in when importing an XML with BIC (present in Odoo DB) but without IstitutoFinanziario
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR10.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳, needs review

#1834 [10.0][FIX] l10n_it_fatturapa_in: Permettere caratteri non ascii in IndirizzoResa
  l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#1836 [12.0][account_vat_period_end_statement] Add more fields such as prev…
  account_vat_period_end_statement/views/account_view.xml
Labels: approved, bot is merging ⏳

#1835 [10.0][account_vat_period_end_statement] Add more fields such as pre…
  account_vat_period_end_statement/views/account_view.xml
Labels: bot is merging ⏳

#1841 [12.0] FIX fiscal_epos_print receipt date placeholder
  fiscal_epos_print/static/src/xml/pos.xml
Labels: approved, bot is merging ⏳, needs review
