Repository OCA/l10n-italy, pull requests merged in 2021-06, with the labels that each got.

#2109 [12.0][FIX]account_invoice_report_ddt_group: set generic session line name when invoice line has no reference in ddt lines.
  account_invoice_report_ddt_group/models/account_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#2300 [12.0] IMP l10n_it_fatturapa_out: prevent to export XML for vendor bills.
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳, ready to merge

#2044 [14.0] Migration: l10n_it_fatturapa_out_stamp
  l10n_it_fatturapa_out_stamp/README.rst
  l10n_it_fatturapa_out_stamp/__init__.py
  l10n_it_fatturapa_out_stamp/__manifest__.py
  l10n_it_fatturapa_out_stamp/i18n/it.po
  l10n_it_fatturapa_out_stamp/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_stamp/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_stamp/static/description/icon.png
  l10n_it_fatturapa_out_stamp/static/description/index.html
  l10n_it_fatturapa_out_stamp/views/account_invoice_it_dati_bollo.xml
  setup/l10n_it_fatturapa_out_stamp/odoo/addons/l10n_it_fatturapa_out_stamp
  setup/l10n_it_fatturapa_out_stamp/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2277 [14.0] FIX tax balance for partially deductible VAT
  l10n_it_account/models/account_tax.py
  l10n_it_account/tests/test_l10n_it_account.py
  l10n_it_vat_registries_split_payment/tests/test_sp.py
Labels: approved, bot is merging ⏳, ready to merge

#1989 [14.0][MIG] l10n_it_withholding_tax_causali
  l10n_it_withholding_tax_reason/README.rst
  l10n_it_withholding_tax_reason/__init__.py
  l10n_it_withholding_tax_reason/__manifest__.py
  l10n_it_withholding_tax_reason/i18n/l10n_it_withholding_tax_reason.pot
  l10n_it_withholding_tax_reason/models/__init__.py
  l10n_it_withholding_tax_reason/models/withholding_tax.py
  l10n_it_withholding_tax_reason/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax_reason/readme/DESCRIPTION.rst
  l10n_it_withholding_tax_reason/readme/INSTALL.rst
  l10n_it_withholding_tax_reason/static/description/icon.png
  l10n_it_withholding_tax_reason/static/description/index.html
  l10n_it_withholding_tax_reason/views/withholding_tax.xml
  setup/l10n_it_withholding_tax_reason/odoo/addons/l10n_it_withholding_tax_reason
  setup/l10n_it_withholding_tax_reason/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2306 [12.0] FIX l10n_it_vat_registries: use consistent order in report summary
  l10n_it_vat_registries/report/report_registro_iva.xml
Labels: bot is merging ⏳

#2294 [10.0][FIX] l10n_it_intrastat_statement: la rettifica può essere legata a un periodo di tipo diverso
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
Labels: bot is merging ⏳

#2322 [12.0] l10n_it_account_tax_kind: allow to search e group taxes by kind_id
  l10n_it_account_tax_kind/view/account_tax_view.xml
Labels: approved, bot is merging ⏳

#2330 [12.0][FIX] document partner data are no more needed
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: approved, bot is merging ⏳

#2268 [12.0][IMP] l10n_it_fatturapa_in: Errore parlante se manca configurazione del conto
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳, ready to merge

#2248 [14.0] mig l10n_it_vat_statement_communication
  l10n_it_vat_statement_communication/README.rst
  l10n_it_vat_statement_communication/__init__.py
  l10n_it_vat_statement_communication/__manifest__.py
  l10n_it_vat_statement_communication/data/comunicazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornituraIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornitura_v3.xsd
  l10n_it_vat_statement_communication/data/intestazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/typesDati_v3.xsd
  l10n_it_vat_statement_communication/data/typesProvincie_v3.xsd
  l10n_it_vat_statement_communication/i18n/it.po
  l10n_it_vat_statement_communication/i18n/l10n_it_vat_statement_communication.pot
  l10n_it_vat_statement_communication/migrations/14.0.1.0.0/noupdate_changes.xml
  l10n_it_vat_statement_communication/migrations/14.0.1.0.0/post-migration.py
  l10n_it_vat_statement_communication/models/__init__.py
  l10n_it_vat_statement_communication/models/account.py
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
  l10n_it_vat_statement_communication/models/config.py
  l10n_it_vat_statement_communication/readme/CONFIGURE.rst
  l10n_it_vat_statement_communication/readme/CONTRIBUTORS.rst
  l10n_it_vat_statement_communication/readme/DESCRIPTION.rst
  l10n_it_vat_statement_communication/readme/USAGE.rst
  l10n_it_vat_statement_communication/security/ir.model.access.csv
  l10n_it_vat_statement_communication/security/security.xml
  l10n_it_vat_statement_communication/static/description/icon.png
  l10n_it_vat_statement_communication/static/description/index.html
  l10n_it_vat_statement_communication/views/account.xml
  l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
  l10n_it_vat_statement_communication/views/config.xml
  l10n_it_vat_statement_communication/wizard/__init__.py
  l10n_it_vat_statement_communication/wizard/export_file.py
  l10n_it_vat_statement_communication/wizard/export_file_view.xml
  setup/l10n_it_vat_statement_communication/odoo/addons/l10n_it_vat_statement_communication
  setup/l10n_it_vat_statement_communication/setup.py
Labels: bot is merging ⏳

#2278 [14.0] porting l10n_it_invoices_data_communication
  l10n_it_invoices_data_communication/__init__.py
  l10n_it_invoices_data_communication/__manifest__.py
  l10n_it_invoices_data_communication/data/res_country_data.xml
  l10n_it_invoices_data_communication/i18n/it.po
  l10n_it_invoices_data_communication/i18n/l10n_it_invoices_data_communication.pot
  l10n_it_invoices_data_communication/migrations/13.0.1.0.0/post-migrate.py
  l10n_it_invoices_data_communication/migrations/14.0.1.0.0/noupdate_changes.xml
  l10n_it_invoices_data_communication/migrations/14.0.1.0.0/post-migration.py
  l10n_it_invoices_data_communication/models/__init__.py
  l10n_it_invoices_data_communication/models/account.py
  l10n_it_invoices_data_communication/models/account_invoice.py
  l10n_it_invoices_data_communication/models/communication.py
  l10n_it_invoices_data_communication/models/res_country.py
  l10n_it_invoices_data_communication/readme/CONTRIBUTORS.rst
  l10n_it_invoices_data_communication/readme/CREDITS.rst
  l10n_it_invoices_data_communication/readme/DESCRIPTION.rst
  l10n_it_invoices_data_communication/security/ir.model.access.csv
  l10n_it_invoices_data_communication/security/security.xml
  l10n_it_invoices_data_communication/static/description/icon.png
  l10n_it_invoices_data_communication/static/description/index.html
  l10n_it_invoices_data_communication/views/account.xml
  l10n_it_invoices_data_communication/views/account_invoice_view.xml
  l10n_it_invoices_data_communication/views/comunicazione.xml
  l10n_it_invoices_data_communication/views/res_country_view.xml
  l10n_it_invoices_data_communication/wizard/__init__.py
  l10n_it_invoices_data_communication/wizard/compute_fiscal_document_type.py
  l10n_it_invoices_data_communication/wizard/compute_fiscal_document_type_view.xml
  l10n_it_invoices_data_communication/wizard/export_file.py
  l10n_it_invoices_data_communication/wizard/export_file_view.xml
  l10n_it_invoices_data_communication/wizard/split_big_communication.py
  l10n_it_invoices_data_communication/wizard/split_big_communication_view.xml
  setup/l10n_it_invoices_data_communication/odoo/addons/l10n_it_invoices_data_communication
  setup/l10n_it_invoices_data_communication/setup.py
Labels: bot is merging ⏳
