Repository OCA/l10n-italy, pull requests merged in 2021-12, with the labels that each got.

#2530 [FIX] l10n_it_fatturapa_out: Esportazione fattura con natura esenzione
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_out_noteline.py
Labels: approved, bot is merging ⏳

#2450 [14.0][FIX] mass validation picking with Advanced DN Features
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, bot is merging ⏳

#2524 [12.0] FIX l10n_it_ddt: partner_shipping_id could be not belonging to customer
  l10n_it_ddt/views/stock_picking_package_preparation.xml
Labels: bot is merging ⏳

#2534 [12.0] FIX pyxb.exceptions_.SimpleFacetValueError: Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}EmailType pattern constraint violated by value test@pec
  l10n_it_fatturapa/bindings/_ds.diff
  l10n_it_fatturapa/bindings/_ds.py
  l10n_it_fatturapa/bindings/binding.diff
  l10n_it_fatturapa/bindings/binding.py
  l10n_it_fatturapa/bindings/xsd/Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR13.xml
Labels: approved, bot is merging ⏳

#2509 [12.0][IMP] Add conflicts module for l10n_it_fatturapa_sale
  l10n_it_fatturapa_sale/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#2541 imp for issue 2540 and 2072
  l10n_it_fiscal_document_type/__manifest__.py
  l10n_it_fiscal_document_type/data/fiscal.document.type.csv
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
  l10n_it_fiscal_document_type/views/fiscal_document_type_view.xml
Labels: approved, bot is merging ⏳

#2497 [14.0][fix] l10n_it_delivery_note: unable to set delivery note to draft in case invoice created before delivery note creation/association
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
  l10n_it_delivery_note/wizard/delivery_note_select.py
Labels: bot is merging ⏳

#2519 [14.0][MIG] l10n_it_website_portal_ipa
  l10n_it_website_portal_ipa/README.rst
  l10n_it_website_portal_ipa/__init__.py
  l10n_it_website_portal_ipa/__manifest__.py
  l10n_it_website_portal_ipa/controllers/__init__.py
  l10n_it_website_portal_ipa/controllers/main.py
  l10n_it_website_portal_ipa/i18n/it.po
  l10n_it_website_portal_ipa/i18n/l10n_it_website_portal_ipa.pot
  l10n_it_website_portal_ipa/readme/DESCRIPTION.rst
  l10n_it_website_portal_ipa/static/description/icon.png
  l10n_it_website_portal_ipa/static/description/index.html
  l10n_it_website_portal_ipa/static/src/js/l10n_it_website_portal_ipa.js
  l10n_it_website_portal_ipa/views/portal_templates.xml
  setup/l10n_it_website_portal_ipa/odoo/addons/l10n_it_website_portal_ipa
  setup/l10n_it_website_portal_ipa/setup.py
Labels: approved, bot is merging ⏳

#2549 [10.0][FIX] l10n_it_central_journal: allow wizard.giornale to filter account move lines based on selected journals
  l10n_it_central_journal/wizard/print_giornale.py
Labels: approved, bot is merging ⏳

#2518 [12.0][IMP] new module l10n_it_fatturapa_out_di
  l10n_it_fatturapa_out_di/README.rst
  l10n_it_fatturapa_out_di/__init__.py
  l10n_it_fatturapa_out_di/__manifest__.py
  l10n_it_fatturapa_out_di/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_di/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_di/static/description/index.html
  l10n_it_fatturapa_out_di/tests/__init__.py
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00003.xml
  l10n_it_fatturapa_out_di/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_di/wizard/__init__.py
  l10n_it_fatturapa_out_di/wizard/wizard_export_fatturapa.py
Labels: bot is merging ⏳

#2523 [12.0][FIX] l10n_it_corrispettivi: Partner per corrispettivi in ambiente multicompany
  l10n_it_corrispettivi/models/__init__.py
  l10n_it_corrispettivi/models/account.py
  l10n_it_corrispettivi/models/res_company.py
Labels: approved, ready to merge, bot is merging ⏳

#2229 14.0 mig l10n it fatturapa in purchase
  l10n_it_fatturapa_in_purchase/README.rst
  l10n_it_fatturapa_in_purchase/__init__.py
  l10n_it_fatturapa_in_purchase/__manifest__.py
  l10n_it_fatturapa_in_purchase/i18n/it.po
  l10n_it_fatturapa_in_purchase/i18n/l10n_it_fatturapa_in_purchase.pot
  l10n_it_fatturapa_in_purchase/models/__init__.py
  l10n_it_fatturapa_in_purchase/models/purchase_order.py
  l10n_it_fatturapa_in_purchase/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in_purchase/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in_purchase/readme/USAGE.rst
  l10n_it_fatturapa_in_purchase/static/description/icon.png
  l10n_it_fatturapa_in_purchase/static/description/index.html
  l10n_it_fatturapa_in_purchase/tests/__init__.py
  l10n_it_fatturapa_in_purchase/tests/data/IT05979361218_008.xml
  l10n_it_fatturapa_in_purchase/tests/test_l10n_it_fatturapa_in_purchase.py
  l10n_it_fatturapa_in_purchase/views/invoice_view.xml
  setup/l10n_it_fatturapa_in_purchase/odoo/addons/l10n_it_fatturapa_in_purchase
  setup/l10n_it_fatturapa_in_purchase/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2503 [14.0][IMP] set INVCONT when needed in XML
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00013.xml
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#2560 [14.0][FIX] l10n_it_reverse_charge: fix rc_inv_vals due to wrong module migration
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#2562 [14.0][FIX] l10n_it_fiscal_document_type: Keep model attribute in name_search
  l10n_it_fiscal_document_type/models/fiscal_document_type.py
Labels: approved, ready to merge, bot is merging ⏳
