Repository OCA/l10n-italy, pull requests merged in 2021-07, with the labels that each got.

#2339 [12.0][IMP] l10n_it_fatturapa_in: improve search of product in supplier_info
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳, ready to merge

#2347 [12.0] ADD fiscal_epos_print_meal_voucher
  fiscal_epos_print_meal_voucher/__init__.py
  fiscal_epos_print_meal_voucher/__manifest__.py
  fiscal_epos_print_meal_voucher/models/__init__.py
  fiscal_epos_print_meal_voucher/models/account_bank_statement.py
  fiscal_epos_print_meal_voucher/models/account_journal.py
  fiscal_epos_print_meal_voucher/models/pos_order.py
  fiscal_epos_print_meal_voucher/readme/CONTRIBUTORS.rst
  fiscal_epos_print_meal_voucher/readme/DESCRIPTION.rst
  fiscal_epos_print_meal_voucher/static/src/js/models.js
  fiscal_epos_print_meal_voucher/static/src/js/screens.js
  fiscal_epos_print_meal_voucher/static/src/xml/pos.xml
  fiscal_epos_print_meal_voucher/views/account_views.xml
  fiscal_epos_print_meal_voucher/views/assets.xml
Labels: approved, bot is merging ⏳

#2363 [14.0][FIX] l10n_it_fatturapa_in: _compute method failure
  l10n_it_fatturapa_in/models/attachment.py
Labels: bot is merging ⏳

#2337 [14.0] porting l10n_it_invoices_data_communication_fatturapa
  l10n_it_invoices_data_communication_fatturapa/README.rst
  l10n_it_invoices_data_communication_fatturapa/__init__.py
  l10n_it_invoices_data_communication_fatturapa/__manifest__.py
  l10n_it_invoices_data_communication_fatturapa/i18n/l10n_it_invoices_data_communication_fatturapa.pot
  l10n_it_invoices_data_communication_fatturapa/models/__init__.py
  l10n_it_invoices_data_communication_fatturapa/models/communication.py
  l10n_it_invoices_data_communication_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_invoices_data_communication_fatturapa/readme/DESCRIPTION.rst
  l10n_it_invoices_data_communication_fatturapa/static/description/icon.png
  l10n_it_invoices_data_communication_fatturapa/static/description/index.html
  l10n_it_invoices_data_communication_fatturapa/views/communication_view.xml
  setup/l10n_it_invoices_data_communication_fatturapa/odoo/addons/l10n_it_invoices_data_communication_fatturapa
  setup/l10n_it_invoices_data_communication_fatturapa/setup.py
Labels: approved, bot is merging ⏳

#2354 [14.0] [FIX] l10n_it_fatturapa_in: porting fixes
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2362 l10n_it_intrastat: fix https://github.com/OCA/l10n-italy/issues/2361
  l10n_it_intrastat/models/__init__.py
  l10n_it_intrastat/models/sale_order.py
  l10n_it_intrastat/readme/CONTRIBUTORS.rst
  l10n_it_intrastat/tests/test_intrastat.py
Labels: approved, bot is merging ⏳

#2308 [14.0][FIX] l10n_it_vat_payability: Dipendenza da openupgradelib per pre_init_hook
  .travis.yml
  l10n_it_vat_payability/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#2311 [14.0] FIX l10n_it_fatturapa: missing dep on l10n_generic_coa
  l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#2320 [12.0][REM][l10n_it_intrastat] Remove depends on stock
  l10n_it_intrastat/__manifest__.py
Labels: bot is merging ⏳

#2371 [14.0] [FIX] l10n_it_fiscalcode: codice fiscale per la persona dovrebbe avere caratteri in maiuscolo
  l10n_it_fiscalcode/model/res_partner.py
Labels: approved, bot is merging ⏳

#2368 [14.0] [IMP] l10n_it_account_tax_kind: allow to search and group taxes by kind_id
  l10n_it_account_tax_kind/view/account_tax_view.xml
Labels: bot is merging ⏳

#2370 [14.0][FIX] l10n_it_rea: Unicità codice REA solo per partner attivi
  l10n_it_rea/models/res_partner.py
  l10n_it_rea/tests/test_rea.py
Labels: bot is merging ⏳

#2257 [10.0][FIX] l10n_it_rea: Unicità codice REA solo per partner attivi
  l10n_it_rea/models/res_partner.py
  l10n_it_rea/tests/__init__.py
  l10n_it_rea/tests/test_rea.py
Labels: bot is merging ⏳

#2372 [12.0][FIX] l10n_it_rea: Unicità codice REA solo per partner attivi
  l10n_it_rea/models/res_partner.py
  l10n_it_rea/tests/__init__.py
  l10n_it_rea/tests/test_rea.py
Labels: bot is merging ⏳

#2297 [14.0][FIX] l10n_it_delivery_note: some minor fixes
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/readme/USAGE.rst
Labels: bot is merging ⏳

#2298 [12.0][FIX] l10n_it_delivery_note: some minor fixes
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/readme/USAGE.rst
Labels: bot is merging ⏳

#2378 [FIX] l10n_it_fatturapa_in: solleva errore quando si archivia un template con fornitore collegato
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2355 [14.0][FIX] l10n_it_fatturapa_in: Fixed singleton error on field computation
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, bot is merging ⏳

#2379 [14.0] [FIX] l10n_it_delivery_note: update method signature
  l10n_it_delivery_note/models/sale_order.py
Labels: bot is merging ⏳

#2374 [12.0] IMP fiscal_epos_print_meal_voucher allowing to add "ticket credit" to receipt
  fiscal_epos_print_meal_voucher/__manifest__.py
  fiscal_epos_print_meal_voucher/models/__init__.py
  fiscal_epos_print_meal_voucher/models/point_of_sale.py
  fiscal_epos_print_meal_voucher/readme/CONFIGURE.rst
  fiscal_epos_print_meal_voucher/readme/DESCRIPTION.rst
  fiscal_epos_print_meal_voucher/static/src/js/screens.js
  fiscal_epos_print_meal_voucher/static/src/xml/pos.xml
  fiscal_epos_print_meal_voucher/views/pos_config_views.xml
Labels: bot is merging ⏳

#2336 [14.0] [FIX] l10n_it_split_payment: fix payment lines
  l10n_it_split_payment/models/account.py
Labels: bot is merging ⏳

#2383 [14.0] [FIX] l10n_it_fatturapa_in: add street number to the address field
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2382 [12.0] Update l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py: concatenated “sede.numero_civico” to the “sede.indirizzo” field
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳
