Repository OCA/l10n-italy, pull requests merged in 2021-11, with the labels that each got.

#2488 [12.0][fix] fiscal_epos_print: null order in lottery_get_button_color method
  fiscal_epos_print/static/src/js/screens.js
Labels: approved, bot is merging ⏳

#2493 [12.0] IMP l10n_it_withholding_tax while duplicating withholding tax, add (copy) suffix to code
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: bot is merging ⏳

#2496 [14.0][FIX] l10n_it_fatturapa_out: fix test_multicompany_fail
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: bot is merging ⏳

#2487 [14.0][fix] l10n_it_delivery_note: update line_ids instead of invoice_line_ids with line notes to avoid auto compute accounting lines of the invoice.
  l10n_it_delivery_note/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2157 [14.0][MIG] l10n_it_sdi_channel: Migration to 14.0
  l10n_it_sdi_channel/README.rst
  l10n_it_sdi_channel/__init__.py
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/data/config_parameter.xml
  l10n_it_sdi_channel/demo/sdi_channel_demo.xml
  l10n_it_sdi_channel/i18n/it.po
  l10n_it_sdi_channel/i18n/l10n_it_sdi_channel.pot
  l10n_it_sdi_channel/migrations/13.0.1.0.0/noupdate_changes.xml
  l10n_it_sdi_channel/migrations/13.0.1.0.0/post-migration.py
  l10n_it_sdi_channel/models/__init__.py
  l10n_it_sdi_channel/models/company.py
  l10n_it_sdi_channel/models/fetchmail_server.py
  l10n_it_sdi_channel/models/ir_mail_server.py
  l10n_it_sdi_channel/models/sdi.py
  l10n_it_sdi_channel/readme/CONFIGURE.rst
  l10n_it_sdi_channel/readme/CONTRIBUTORS.rst
  l10n_it_sdi_channel/readme/DESCRIPTION.rst
  l10n_it_sdi_channel/security/ir.model.access.csv
  l10n_it_sdi_channel/security/security.xml
  l10n_it_sdi_channel/static/description/icon.png
  l10n_it_sdi_channel/static/description/index.html
  l10n_it_sdi_channel/views/company_view.xml
  l10n_it_sdi_channel/views/fetchmail_server.xml
  l10n_it_sdi_channel/views/ir_mail_server.xml
  l10n_it_sdi_channel/views/sdi_view.xml
  setup/l10n_it_sdi_channel/odoo/addons/l10n_it_sdi_channel
  setup/l10n_it_sdi_channel/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2485 [14.0][FIX] l10n_it_fatturapa_out: do not relay on invoice line having taxes
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/models/account.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#2499 [14.0][FIX] l10n_it_account_stamp: Descrizione righe fattura resettate quando viene aggiunto il bollo
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
Labels: approved, bot is merging ⏳

#2502 [14.0][FIX] l10n_it_fiscal_document_type: Tipo documento impostato dall'utente non mantenuto
  l10n_it_fiscal_document_type/models/account_move.py
  l10n_it_fiscal_document_type/tests/test_doc_type.py
Labels: bot is merging ⏳

#2512 [FIX][14.0] check lack of taxes only on product lines
  l10n_it_fatturapa_out/models/account.py
Labels: bot is merging ⏳

#2453 [14.0][FIX] l10n_it_delivery_note: allow validation of backorders
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note/tests/__init__.py
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
Labels: approved, ready to merge, bot is merging ⏳

#2483 [14.0][FIX] l10n_it_fatturapa_out: multiple taxes with same amount
  l10n_it_fatturapa_out/tests/data/IT06363391001_00014.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/efattura.py
Labels: approved, ready to merge, bot is merging ⏳

#2513 [12.0][FIX] l10n_it_delivery_note, fix stock_user permission for stock_delivery_note_line
  l10n_it_delivery_note/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2495 [14.0][IMP] l10n_it_withholding_tax while duplicating withholding tax, add (copy) suffix to code
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#2443 [10.0][FIX] l10n_it_fatturapa_out: Upper limit for Unidecode version
  requirements.txt
  setup/l10n_it_fatturapa_out/setup.py
Labels: bot is merging ⏳

#2514 [12.0] IMP l10n_it_ddt report printing dimension
  l10n_it_ddt/views/report_ddt.xml
Labels: approved, bot is merging ⏳

#2228 [14.0][MIG] l10n_it_intrastat
  l10n_it_intrastat/README.rst
  l10n_it_intrastat/__init__.py
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/data/account.intrastat.custom.csv
  l10n_it_intrastat/data/account.intrastat.transaction.nature.csv
  l10n_it_intrastat/data/account.intrastat.transport.csv
  l10n_it_intrastat/data/report.intrastat.code.csv
  l10n_it_intrastat/demo/product_demo.xml
  l10n_it_intrastat/i18n/es.po
  l10n_it_intrastat/i18n/it.po
  l10n_it_intrastat/i18n/l10n_it_intrastat.pot
  l10n_it_intrastat/migrations/12.0.1.0.0/pre-migrate.py
  l10n_it_intrastat/migrations/13.0.1.0.0/post-migrate.py
  l10n_it_intrastat/models/__init__.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/models/config.py
  l10n_it_intrastat/models/intrastat.py
  l10n_it_intrastat/models/product.py
  l10n_it_intrastat/readme/CONFIGURE.rst
  l10n_it_intrastat/readme/CONTRIBUTORS.rst
  l10n_it_intrastat/readme/DESCRIPTION.rst
  l10n_it_intrastat/readme/USAGE.rst
  l10n_it_intrastat/security/ir.model.access.csv
  l10n_it_intrastat/static/description/icon.png
  l10n_it_intrastat/static/description/index.html
  l10n_it_intrastat/tests/__init__.py
  l10n_it_intrastat/tests/test_intrastat.py
  l10n_it_intrastat/views/account.xml
  l10n_it_intrastat/views/config.xml
  l10n_it_intrastat/views/intrastat.xml
  l10n_it_intrastat/views/product.xml
  oca_dependencies.txt
  setup/l10n_it_intrastat/odoo/addons/l10n_it_intrastat
  setup/l10n_it_intrastat/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2138 [14.0] Migration: l10n_it_ricevute_bancarie
  l10n_it_ricevute_bancarie/README.rst
  l10n_it_ricevute_bancarie/__init__.py
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/data/riba_sequence.xml
  l10n_it_ricevute_bancarie/demo/riba_demo.xml
  l10n_it_ricevute_bancarie/i18n/it.po
  l10n_it_ricevute_bancarie/migrations/13.0.1.0.0/post-migration.py
  l10n_it_ricevute_bancarie/models/__init__.py
  l10n_it_ricevute_bancarie/models/account.py
  l10n_it_ricevute_bancarie/models/account_config.py
  l10n_it_ricevute_bancarie/models/bank_statement.py
  l10n_it_ricevute_bancarie/models/partner.py
  l10n_it_ricevute_bancarie/models/riba.py
  l10n_it_ricevute_bancarie/models/riba_config.py
  l10n_it_ricevute_bancarie/readme/CONFIGURE.rst
  l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
  l10n_it_ricevute_bancarie/readme/DESCRIPTION.rst
  l10n_it_ricevute_bancarie/readme/ROADMAP.rst
  l10n_it_ricevute_bancarie/readme/USAGE.rst
  l10n_it_ricevute_bancarie/report/__init__.py
  l10n_it_ricevute_bancarie/report/distinta_qweb.py
  l10n_it_ricevute_bancarie/report/report.xml
  l10n_it_ricevute_bancarie/security/ir.model.access.csv
  l10n_it_ricevute_bancarie/static/description/icon.png
  l10n_it_ricevute_bancarie/static/description/index.html
  l10n_it_ricevute_bancarie/tests/__init__.py
  l10n_it_ricevute_bancarie/tests/riba_common.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/account_config_view.xml
  l10n_it_ricevute_bancarie/views/account_view.xml
  l10n_it_ricevute_bancarie/views/configuration_view.xml
  l10n_it_ricevute_bancarie/views/distinta_report.xml
  l10n_it_ricevute_bancarie/views/partner_view.xml
  l10n_it_ricevute_bancarie/views/riba_detail_view.xml
  l10n_it_ricevute_bancarie/views/riba_view.xml
  l10n_it_ricevute_bancarie/views/wizard_accreditation.xml
  l10n_it_ricevute_bancarie/views/wizard_riba_file_export.xml
  l10n_it_ricevute_bancarie/views/wizard_riba_issue.xml
  l10n_it_ricevute_bancarie/views/wizard_unsolved.xml
  l10n_it_ricevute_bancarie/wizard/__init__.py
  l10n_it_ricevute_bancarie/wizard/wizard_accreditation.py
  l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
  l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py
  l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py
  setup/l10n_it_ricevute_bancarie/odoo/addons/l10n_it_ricevute_bancarie
  setup/l10n_it_ricevute_bancarie/setup.py
Labels: bot is merging ⏳

#2448 [12.0][IMP] l10n_it_account_stamp: Usabilità per il bollo in fattura
  l10n_it_account_stamp/models/invoice.py
  l10n_it_account_stamp/views/invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2505 [12.0] IMP l10n_it_account_stamp: print legal statement in invoice report
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/views/account_invoice_report.xml
Labels: bot is merging ⏳

#2421 [12.0] ADD l10n_it_website_portal_corrispettivi: Aggiunge ricevuta o fattura come opzione nel profilo dell'utente portale
  l10n_it_website_portal_corrispettivi/__init__.py
  l10n_it_website_portal_corrispettivi/__manifest__.py
  l10n_it_website_portal_corrispettivi/controllers/__init__.py
  l10n_it_website_portal_corrispettivi/controllers/main.py
  l10n_it_website_portal_corrispettivi/models/__init__.py
  l10n_it_website_portal_corrispettivi/models/res_partner.py
  l10n_it_website_portal_corrispettivi/readme/DESCRIPTION.rst
  l10n_it_website_portal_corrispettivi/views/l10n_it_website_portal_corrispettivi_templates.xml
  setup/l10n_it_website_portal_corrispettivi/odoo/addons/l10n_it_website_portal_corrispettivi
  setup/l10n_it_website_portal_corrispettivi/setup.py
Labels: bot is merging ⏳
