Repository OCA/l10n-italy, pull requests merged in 2021-01, with the labels that each got.

#2033 [8.0][FIX] withholding tax test
  l10n_it_withholding_tax/tests/test_invoice_multi_line_tax.py
Labels: bot is merging ⏳

#1464 [8.0][IMP] add ability to put internal reference for sale order in e-invoice
  l10n_it_fatturapa_out_sale/__openerp__.py
  l10n_it_fatturapa_out_sale/models/__init__.py
  l10n_it_fatturapa_out_sale/models/company.py
  l10n_it_fatturapa_out_sale/views/company_view.xml
  l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
Labels: bot is merging ⏳

#2034 [8.0][FIX] l10n_it_fatturapa: binding types from string to decimal
  l10n_it_fatturapa/bindings/binding.py
Labels: bot is merging ⏳

#2035 [12.0][FIX] ricevute bancarie ASCII instead UTF-8
  l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
Labels: bot is merging ⏳

#2025 [12.0][IMP][l10n_it_ricevute_bancarie] Flag per escludere un partner dalle …
  l10n_it_ricevute_bancarie/models/account/account.py
  l10n_it_ricevute_bancarie/models/partner/partner.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/partner_view.xml
Labels: approved, bot is merging ⏳

#2040 [12.0][FIX] l10n_it_account report conflicts with report qweb element page visibility
  l10n_it_account/__manifest__.py
Labels: bot is merging ⏳

#2001 12.0 fix fatturapa Email trailing space in XML import
  l10n_it_fatturapa/bindings/fatturapa.py
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20005.xml
Labels: approved, bot is merging ⏳

#2006 [12.0][FIX] fix code and add test to support issued declaration [l10n_it_dichiarazione_intento]
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: bot is merging ⏳

#2046 [12.0] [FIX] l10n_it_fatturapa: Changed inherit for partner related views for a missing reference of field `electronic_invoice_subjected`
  l10n_it_fatturapa/views/partner_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#2030 [12.0][IMP] l10n_it_fatturapa_in: invoices_total field in tree view
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#2029 [8.0][IMP] l10n_it_fatturapa_in: invoices_total field in tree view
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, bot is merging ⏳

#2061 [14.0] [FIX] l10n_it_rea category string
  l10n_it_rea/__manifest__.py
Labels: approved, bot is merging ⏳

#2051 [12.0][FIX] l10n_it_fatturapa_out: Fix error tests to copy files
  l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out/tests/fatturapa_common.py
Labels: approved, bot is merging ⏳

#2002 [12.0] l10n_it_fatturapa_out_rc
  l10n_it_fatturapa_out_rc/__init__.py
  l10n_it_fatturapa_out_rc/__manifest__.py
  l10n_it_fatturapa_out_rc/i18n/it.po
  l10n_it_fatturapa_out_rc/models/__init__.py
  l10n_it_fatturapa_out_rc/models/account_invoice.py
  l10n_it_fatturapa_out_rc/models/rc_type.py
  l10n_it_fatturapa_out_rc/readme/CONFIGURE.rst
  l10n_it_fatturapa_out_rc/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_rc/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_rc/tests/__init__.py
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00002.xml
  l10n_it_fatturapa_out_rc/tests/test_e_invoice_out_rc.py
  l10n_it_fatturapa_out_rc/views/rc_type_views.xml
  l10n_it_fatturapa_out_rc/wizard/__init__.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py
  l10n_it_reverse_charge/tests/rc_common.py
  l10n_it_reverse_charge/tests/test_rc.py
  setup/l10n_it_fatturapa_out_rc/odoo/addons/l10n_it_fatturapa_out_rc
  setup/l10n_it_fatturapa_out_rc/setup.py
Labels: bot is merging ⏳, needs review

#1939 [14.0] Migration: l10n_it_fiscal_payment_term
  l10n_it_fiscal_payment_term/README.rst
  l10n_it_fiscal_payment_term/__init__.py
  l10n_it_fiscal_payment_term/__manifest__.py
  l10n_it_fiscal_payment_term/data/fatturapa_data.xml
  l10n_it_fiscal_payment_term/i18n/it.po
  l10n_it_fiscal_payment_term/i18n/l10n_it_fiscal_payment_term.pot
  l10n_it_fiscal_payment_term/models/__init__.py
  l10n_it_fiscal_payment_term/models/account.py
  l10n_it_fiscal_payment_term/readme/CONFIGURE.rst
  l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_payment_term/readme/DESCRIPTION.rst
  l10n_it_fiscal_payment_term/security/ir.model.access.csv
  l10n_it_fiscal_payment_term/static/description/icon.png
  l10n_it_fiscal_payment_term/static/description/index.html
  l10n_it_fiscal_payment_term/views/account_view.xml
  setup/l10n_it_fiscal_payment_term/odoo/addons/l10n_it_fiscal_payment_term
  setup/l10n_it_fiscal_payment_term/setup.py
Labels: approved, bot is merging ⏳

#2070 [FIX][12.0] remove space
  l10n_it_fatturapa_sale/models/sale_order_line.py
Labels: bot is merging ⏳

#2064 [12.0][IMP] l10n_it_ricevute_bancarie, manage multiple bank in partner
  l10n_it_ricevute_bancarie/models/account/account.py
  l10n_it_ricevute_bancarie/tests/riba_common.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/account_view.xml
  l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py
Labels: approved, bot is merging ⏳, ready to merge
