Repository OCA/l10n-italy, pull requests merged in 2021-04, with the labels that each got.

#2201 [12.0][FIX] typo: taget -> target
  l10n_it_fatturapa/models/account.py
Labels: bot is merging ⏳

#2194 [FIX] l10n_it_fatturapa_in: fix https://github.com/OCA/l10n-italy/issues/2186
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2175 [12.0][FIX] l10n_it_intrastat_statement: Arrotondamento amount_euro e statistic_amount_euro, troncamento amount_currency
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
  l10n_it_intrastat_statement/views/intrastat.xml
Labels: bot is merging ⏳

#2196 [12.0] IMP _addGlobalDiscount when vendor journal does not have default accounts
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2077 14.0 mig l10n it account stamp
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__init__.py
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/i18n/it.po
  l10n_it_account_stamp/i18n/l10n_it_account_stamp.pot
  l10n_it_account_stamp/models/__init__.py
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/models/company.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp/readme/DESCRIPTION.rst
  l10n_it_account_stamp/readme/USAGE.rst
  l10n_it_account_stamp/static/description/icon.png
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/tests/__init__.py
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
  l10n_it_account_stamp/views/account_move_view.xml
  l10n_it_account_stamp/views/company_view.xml
  l10n_it_account_stamp/views/product_view.xml
  setup/l10n_it_account_stamp/odoo/addons/l10n_it_account_stamp
  setup/l10n_it_account_stamp/setup.py
Labels: bot is merging ⏳

#2204 [12.0][IMP] created invoice directly with riba bank
  l10n_it_ricevute_bancarie/models/account/account.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
Labels: approved, bot is merging ⏳

#2218 [12.0] account_vat_period_end_statement: print down payment and computation method
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/views/account_view.xml
  account_vat_period_end_statement/views/report_vatperiodendstatement.xml
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, bot is merging ⏳

#2214 [8.0][FIX] button visibility l10n_it_account_stamp
  l10n_it_account_stamp/views/invoice_view.xml
Labels: approved, bot is merging ⏳

#1999 [8.0][IMP] l10n_it_withholding_tax_payment: UI improve
  l10n_it_withholding_tax_payment/models/withholding_tax.py
  l10n_it_withholding_tax_payment/views/withholding_tax.xml
Labels: approved, bot is merging ⏳

#2216 [12.0][FIX][l10n_it_fatturapa_out_triple_discount]
  l10n_it_fatturapa_out_triple_discount/wizards/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#2141 14.0 mig delivery note
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/__init__.py
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/cli/__init__.py
  l10n_it_delivery_note/cli/core.py
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/i18n/it.po
  l10n_it_delivery_note/migration/13.0.1.0.0/noupdate_changes.xml
  l10n_it_delivery_note/migration/13.0.1.0.0/post-migration.py
  l10n_it_delivery_note/mixins/__init__.py
  l10n_it_delivery_note/mixins/picking_checker.py
  l10n_it_delivery_note/mixins/shipping_updater.py
  l10n_it_delivery_note/models/__init__.py
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/models/res_config_settings.py
  l10n_it_delivery_note/models/res_partner.py
  l10n_it_delivery_note/models/sale_order.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_location.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/readme/CONFIGURE.rst
  l10n_it_delivery_note/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note/readme/DESCRIPTION.rst
  l10n_it_delivery_note/readme/USAGE.rst
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/security/ir.model.access.csv
  l10n_it_delivery_note/security/ir_rule.xml
  l10n_it_delivery_note/security/res_groups.xml
  l10n_it_delivery_note/security/res_users.xml
  l10n_it_delivery_note/static/description/icon.jpg
  l10n_it_delivery_note/static/description/icon.png
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/static/src/scss/stock_delivery_note.scss
  l10n_it_delivery_note/tests/__init__.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/views/account_move.xml
  l10n_it_delivery_note/views/assets.xml
  l10n_it_delivery_note/views/res_config_settings.xml
  l10n_it_delivery_note/views/res_partner.xml
  l10n_it_delivery_note/views/sale_order.xml
  l10n_it_delivery_note/views/stock_delivery_note.xml
  l10n_it_delivery_note/views/stock_picking.xml
  l10n_it_delivery_note/wizard/__init__.py
  l10n_it_delivery_note/wizard/delivery_note_base.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
  l10n_it_delivery_note/wizard/delivery_note_create.xml
  l10n_it_delivery_note/wizard/delivery_note_select.py
  l10n_it_delivery_note/wizard/delivery_note_select.xml
  l10n_it_delivery_note/wizard/delivery_note_template.xml
  l10n_it_delivery_note/wizard/sale_advance_payment_inv.py
  l10n_it_delivery_note/wizard/sale_advance_payment_inv.xml
Labels: approved, bot is merging ⏳

#2219 [12.0][FIX] add riba partner bank to out_refund for compensated riba
  l10n_it_ricevute_bancarie/models/account/account.py
  l10n_it_ricevute_bancarie/views/account_view.xml
Labels: bot is merging ⏳

#1974 [14.0] Migration: l10n_it_delivery_note_order_link
  l10n_it_delivery_note_order_link/README.rst
  l10n_it_delivery_note_order_link/__init__.py
  l10n_it_delivery_note_order_link/__manifest__.py
  l10n_it_delivery_note_order_link/i18n/it.po
  l10n_it_delivery_note_order_link/i18n/l10n_it_delivery_note_order_link.pot
  l10n_it_delivery_note_order_link/models/__init__.py
  l10n_it_delivery_note_order_link/models/purchase_order.py
  l10n_it_delivery_note_order_link/models/sale_order.py
  l10n_it_delivery_note_order_link/models/stock_delivery_note.py
  l10n_it_delivery_note_order_link/readme/CONFIGURE.rst
  l10n_it_delivery_note_order_link/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note_order_link/readme/DESCRIPTION.rst
  l10n_it_delivery_note_order_link/readme/USAGE.rst
  l10n_it_delivery_note_order_link/static/description/icon.png
  l10n_it_delivery_note_order_link/static/description/index.html
  l10n_it_delivery_note_order_link/views/purchase_order.xml
  l10n_it_delivery_note_order_link/views/sale_order.xml
  setup/l10n_it_delivery_note_order_link/odoo/addons/l10n_it_delivery_note_order_link
  setup/l10n_it_delivery_note_order_link/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#2233 [14.0][IMP] l10n_it_account: menu per gestione intervalli data
  l10n_it_account/__manifest__.py
  l10n_it_account/views/account_menuitem.xml
Labels: approved, bot is merging ⏳

#2241 [FIX][12.0] l10n_it_invoices_data_communication file export
  l10n_it_invoices_data_communication/wizard/export_file.py
Labels: approved, bot is merging ⏳

#2240 [FIX][12.0] l10n_it_vat_statement_communication file export
  l10n_it_vat_statement_communication/wizard/export_file.py
Labels: bot is merging ⏳

#2232 [10.0][FIX] l10n_it_intrastat_statement: force round to 1 additional_units field only if has a value
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
Labels: approved, bot is merging ⏳, ready to merge

#2253 [12.0] [l10n_it_fiscalcode] Codice fiscale per la persona dovrebbe avere caratteri in maiuscolo
  l10n_it_fiscalcode/model/res_partner.py
Labels: approved, bot is merging ⏳

#2254 [12.0] l10n_it_intrastat_statement: force round to 1 additional_units field only if has a value
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
Labels: approved, bot is merging ⏳

#1732 [10.0][FIX] l10n_it_fatturapa_pec: Rollback unwanted DB changes in case of exception
  l10n_it_fatturapa_pec/models/fetchmail.py
Labels: approved, bot is merging ⏳

#2247 [14.0][FIX] l10n_it_vat_payability: replace script migration by pre_init_hook
  .travis.yml
  l10n_it_vat_payability/__init__.py
  l10n_it_vat_payability/__manifest__.py
  l10n_it_vat_payability/migrations/14.0.1.0.0/pre-migrate.py
  l10n_it_vat_payability/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳
