Repository OCA/l10n-italy, pull requests merged in 2021-09, with the labels that each got.

#2402 [14.0][IMP] l10n_it_withholding_tax: Istruzioni per il pagamento nel README
  l10n_it_withholding_tax/README.rst
  l10n_it_withholding_tax/readme/USAGE.rst
  l10n_it_withholding_tax/static/description/index.html
  l10n_it_withholding_tax/static/img/pagamento-fattura-fornitore.png
  l10n_it_withholding_tax/static/img/pagamento-ritenuta.png
Labels: approved, bot is merging ⏳

#2387 Fix issue https://github.com/OCA/l10n-italy/issues/1828
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#1934 12.0 nr company extra
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/views/company_view.xml
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/models/__init__.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2408 [14.0][FIX] l10n_it_fatturapa_out: string instead of list in error message
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: bot is merging ⏳

#2413 [12.0][FIX] l10n_it_dichiarazione_intento dt object
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: approved, bot is merging ⏳

#2154 [14.0][ADD] new module l10n_it_fatturapa_out_sp
  .pre-commit-config.yaml
  l10n_it_fatturapa_out_sp/README.rst
  l10n_it_fatturapa_out_sp/__init__.py
  l10n_it_fatturapa_out_sp/__manifest__.py
  l10n_it_fatturapa_out_sp/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_sp/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_sp/static/description/icon.png
  l10n_it_fatturapa_out_sp/static/description/index.html
  l10n_it_fatturapa_out_sp/tests/__init__.py
  l10n_it_fatturapa_out_sp/tests/data/IT06363391001_00004.xml
  l10n_it_fatturapa_out_sp/tests/fatturapa_common.py
  l10n_it_fatturapa_out_sp/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_sp/view/invoice_it_template.xml
  setup/l10n_it_fatturapa_out_sp/odoo/addons/l10n_it_fatturapa_out_sp
  setup/l10n_it_fatturapa_out_sp/setup.py
Labels: bot is merging ⏳

#2414 [12.0] IMP l10n_it_website_portal_fatturapa: when customers set they are subjected they are also obliged
  l10n_it_website_portal_fatturapa/controllers/main.py
Labels: approved, bot is merging ⏳

#2423 [12.0] FIX fiscal_epos_print: fiscalprinter_payment_index must be set also for Discount on payment
  fiscal_epos_print/views/account.xml
Labels: approved, bot is merging ⏳

#1908 12.0 mig l10n it fattura accompagnatoria
  l10n_it_accompanying_invoice/README.rst
  l10n_it_accompanying_invoice/__init__.py
  l10n_it_accompanying_invoice/__manifest__.py
  l10n_it_accompanying_invoice/i18n/it.po
  l10n_it_accompanying_invoice/models/__init__.py
  l10n_it_accompanying_invoice/models/account_invoice.py
  l10n_it_accompanying_invoice/readme/CONTRIBUTORS.rst
  l10n_it_accompanying_invoice/readme/DESCRIPTION.rst
  l10n_it_accompanying_invoice/readme/USAGE.rst
  l10n_it_accompanying_invoice/static/description/index.html
  l10n_it_accompanying_invoice/tests/__init__.py
  l10n_it_accompanying_invoice/tests/test_report.py
  l10n_it_accompanying_invoice/views/account.xml
  l10n_it_accompanying_invoice/views/report_invoice.xml
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/models/account.py
  l10n_it_ddt/models/sale.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/views/account.xml
  l10n_it_ddt/views/sale.xml
Labels: bot is merging ⏳

#2353 [14.0] [FIX] l10n_it_withholding_tax: fix for #2345 + multicompany
  l10n_it_withholding_tax/models/withholding_tax.py
Labels: bot is merging ⏳

#2332 [14.0][IMP] l10n_it_fatturapa: Istruzioni per problemi con l10n_it_edi
  l10n_it_fatturapa/readme/INSTALL.rst
Labels: approved, ready to merge, bot is merging ⏳

#2303 [14.0] [FIX] l10n_it_fatturapa_out: Fix error tests to copy files
  l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out/tests/fatturapa_common.py
Labels: bot is merging ⏳

#2352 [14.0][FIX] l10n_it_fatturapa_in multicompany wrong company
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#2424 [12.0] l10n_it_withholding_tax: Residual Net To Pay in report invoice, now, printed only if there is witholding tax in account move
  l10n_it_withholding_tax/views/report_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#2418 [FIX] l10n_it_withholding_tax: compare amount with float_compare
  l10n_it_withholding_tax/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#2305 [14.0] FIX l10n_it_vat_registries: use consistent order in report summary
  l10n_it_vat_registries/report/report_registro_iva.xml
Labels: bot is merging ⏳

#2358 [14.0][FIX] l10n_it_fiscal_document_type: data migration script
  l10n_it_fiscal_document_type/migrations/13.0.1.0.0/post-migration.py
Labels: bot is merging ⏳

#2419 [FIX] l10n_it_withholding_tax: compare amount with float_compare
  l10n_it_withholding_tax/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#2080 [14.0][MIG] l10n_it_fatturapa_export_zip
  l10n_it_fatturapa_export_zip/README.rst
  l10n_it_fatturapa_export_zip/__init__.py
  l10n_it_fatturapa_export_zip/__manifest__.py
  l10n_it_fatturapa_export_zip/i18n/it.po
  l10n_it_fatturapa_export_zip/models/__init__.py
  l10n_it_fatturapa_export_zip/models/attachment.py
  l10n_it_fatturapa_export_zip/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_export_zip/readme/DESCRIPTION.rst
  l10n_it_fatturapa_export_zip/security/ir.model.access.csv
  l10n_it_fatturapa_export_zip/static/description/icon.png
  l10n_it_fatturapa_export_zip/static/description/index.html
  l10n_it_fatturapa_export_zip/views/attachment_view.xml
  l10n_it_fatturapa_export_zip/wizard/__init__.py
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa_view.xml
  setup/l10n_it_fatturapa_export_zip/odoo/addons/l10n_it_fatturapa_export_zip
  setup/l10n_it_fatturapa_export_zip/setup.py
Labels: approved, bot is merging ⏳

#2440 Unidecode>=1.3.0 only supports Python 3.5 or later
  requirements.txt
Labels: 10.0, approved, bot is merging ⏳

#2416 [FIX] l10n_it_withholding_tax: compare amount with float_compare
  l10n_it_withholding_tax/models/account.py
Labels: bot is merging ⏳

#2427 [14.0] Errore Stampa registro IVA: Field amount doesn't exist in account.move
  l10n_it_vat_registries/models/vat_registry.py
Labels: approved, bot is merging ⏳

#2433 [12.0] Better view of payments list
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2436 [FIX] l10n_it_fiscal_document_type: license must be AGPL since it depends on AGPL modules
  l10n_it_fiscal_document_type/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳
