Repository OCA/l10n-italy, pull requests merged in 2022-01, with the labels that each got.

#2573 [14.0][FIX] l10n_it_fatturapa_in: remove limit parameter from browse
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2579 [14.0][FIX] l10n_it_account_stamp: force invoice currency in tax stamp lines
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
Labels: approved, ready to merge, bot is merging ⏳

#2315 [14.0][MIG] l10n_it_website_portal_fiscalcode
  l10n_it_website_portal_fiscalcode/README.rst
  l10n_it_website_portal_fiscalcode/__init__.py
  l10n_it_website_portal_fiscalcode/__manifest__.py
  l10n_it_website_portal_fiscalcode/controllers/__init__.py
  l10n_it_website_portal_fiscalcode/controllers/main.py
  l10n_it_website_portal_fiscalcode/i18n/it.po
  l10n_it_website_portal_fiscalcode/i18n/l10n_it_website_portal_fiscalcode.pot
  l10n_it_website_portal_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_website_portal_fiscalcode/static/description/icon.png
  l10n_it_website_portal_fiscalcode/static/description/index.html
  l10n_it_website_portal_fiscalcode/views/l10n_it_website_portal_fiscalcode_templates.xml
  setup/l10n_it_website_portal_fiscalcode/odoo/addons/l10n_it_website_portal_fiscalcode
  setup/l10n_it_website_portal_fiscalcode/setup.py
Labels: approved, bot is merging ⏳

#2586 [14.0][FIX] l10n_it_fatturapa_out: allow to write related_documents field when l10n_it_fatturapa_in is installed after l10n_it_fatturapa_out
  l10n_it_fatturapa_out/views/account_view.xml
Labels: bot is merging ⏳

#2556 [14.0][MIG] l10n_it_mis_report_pl_bs
  l10n_it_mis_reports_pl_bs/README.rst
  l10n_it_mis_reports_pl_bs/__init__.py
  l10n_it_mis_reports_pl_bs/__manifest__.py
  l10n_it_mis_reports_pl_bs/data/mis_report_bs.xml
  l10n_it_mis_reports_pl_bs/data/mis_report_pl.xml
  l10n_it_mis_reports_pl_bs/data/mis_report_styles.xml
  l10n_it_mis_reports_pl_bs/i18n/it.po
  l10n_it_mis_reports_pl_bs/i18n/l10n_it_mis_reports_pl_bs.pot
  l10n_it_mis_reports_pl_bs/readme/CONFIGURE.rst
  l10n_it_mis_reports_pl_bs/readme/CONTRIBUTORS.rst
  l10n_it_mis_reports_pl_bs/readme/DESCRIPTION.rst
  l10n_it_mis_reports_pl_bs/readme/INSTALL.rst
  l10n_it_mis_reports_pl_bs/readme/USAGE.rst
  l10n_it_mis_reports_pl_bs/static/description/icon.png
  l10n_it_mis_reports_pl_bs/static/description/index.html
  setup/l10n_it_mis_reports_pl_bs/odoo/addons/l10n_it_mis_reports_pl_bs
  setup/l10n_it_mis_reports_pl_bs/setup.py
Labels: approved, bot is merging ⏳

#2259 14.0 mig l10n_it_intrastat_statement
  l10n_it_intrastat_statement/README.rst
  l10n_it_intrastat_statement/__init__.py
  l10n_it_intrastat_statement/__manifest__.py
  l10n_it_intrastat_statement/data/sequence.xml
  l10n_it_intrastat_statement/i18n/es.po
  l10n_it_intrastat_statement/i18n/it.po
  l10n_it_intrastat_statement/i18n/l10n_it_intrastat_statement.pot
  l10n_it_intrastat_statement/migrations/13.0.1.0.0/noupdate_changes.xml
  l10n_it_intrastat_statement/migrations/13.0.1.0.0/post-migration.py
  l10n_it_intrastat_statement/models/__init__.py
  l10n_it_intrastat_statement/models/config.py
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_section.py
  l10n_it_intrastat_statement/readme/CONTRIBUTORS.rst
  l10n_it_intrastat_statement/readme/DESCRIPTION.rst
  l10n_it_intrastat_statement/readme/USAGE.rst
  l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
  l10n_it_intrastat_statement/report/intrastat_mod1_ter.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod1.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
  l10n_it_intrastat_statement/report/reports.xml
  l10n_it_intrastat_statement/security/ir.model.access.csv
  l10n_it_intrastat_statement/security/rules.xml
  l10n_it_intrastat_statement/static/description/icon.png
  l10n_it_intrastat_statement/static/description/index.html
  l10n_it_intrastat_statement/static/img/agenzia_dogane.jpg
  l10n_it_intrastat_statement/static/img/logo_dogane.gif
  l10n_it_intrastat_statement/tests/__init__.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
  l10n_it_intrastat_statement/views/config.xml
  l10n_it_intrastat_statement/views/intrastat.xml
  l10n_it_intrastat_statement/wizard/__init__.py
  l10n_it_intrastat_statement/wizard/export_file.py
  l10n_it_intrastat_statement/wizard/export_file_view.xml
  setup/l10n_it_intrastat_statement/odoo/addons/l10n_it_intrastat_statement
  setup/l10n_it_intrastat_statement/setup.py
Labels: approved, bot is merging ⏳

#2412 [12.0][FIX] l10n_it_dichiarazione_intento plafond out
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
Labels: approved, ready to merge, bot is merging ⏳

#2565 [14.0][FIX] split_payment: errore su conferma fatture con riga di split payment
  l10n_it_split_payment/migrations/14.0.1.0.0/post-migration.py
  l10n_it_split_payment/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#2451 [14.0][IMP] new module l10n_it_fatturapa_out_di
  .pre-commit-config.yaml
  l10n_it_fatturapa_out_di/README.rst
  l10n_it_fatturapa_out_di/__init__.py
  l10n_it_fatturapa_out_di/__manifest__.py
  l10n_it_fatturapa_out_di/data/invoice_it_template.xml
  l10n_it_fatturapa_out_di/i18n/l10n_it_fatturapa_out_sp.pot
  l10n_it_fatturapa_out_di/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_di/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_di/static/description/icon.png
  l10n_it_fatturapa_out_di/static/description/index.html
  l10n_it_fatturapa_out_di/tests/__init__.py
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00003.xml
  l10n_it_fatturapa_out_di/tests/fatturapa_common.py
  l10n_it_fatturapa_out_di/tests/test_fatturapa_xml_validation.py
  setup/l10n_it_fatturapa_out_di/odoo/addons/l10n_it_fatturapa_out_di
  setup/l10n_it_fatturapa_out_di/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2455 [12.0][FIX] l10n_it_delivery_note: allow validation of backorders
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note/tests/__init__.py
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
Labels: approved, ready to merge, bot is merging ⏳

#2576 [14.0][FIX] l10n_it_reverse_charge: undo reverse moves when supplier invoice is reset to draft
  l10n_it_reverse_charge/models/account_move.py
  l10n_it_reverse_charge/tests/test_rc.py
Labels: approved, ready to merge, bot is merging ⏳

#2551 [14.0][FIX] l10n_it_account: Importi (in)detraibili per liquidazione IVA multi periodo
  l10n_it_account/models/account_tax.py
  l10n_it_account/tests/test_l10n_it_account.py
Labels: approved, ready to merge, bot is merging ⏳

#2592 [FIX] l10n_it_fatturapa_in: field positioning in view
  l10n_it_fatturapa_in/views/account_view.xml
Labels: bot is merging ⏳

#2594 [12.0][FIX] fiscal_epos_print: Validazione massiva imposte
  fiscal_epos_print/models/account.py
Labels: approved, bot is merging ⏳

#2598 [12.0] IMP l10n_it_sdi_channel making first_invoice_sent more clear
  l10n_it_sdi_channel/models/sdi.py
Labels: approved, bot is merging ⏳

#2613 [14.0][IMP] l10n_it_account_stamp, move fields on accountig tab
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp/views/product_view.xml
Labels: approved, bot is merging ⏳

#2595 [14.0][fix] l10n_it_reverse_charge: unable to set payment to draft
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#2617 [FIX] l10n_it_withholding_tax: Prevenire "AttributeError: 'bool' object has no attribute 'id'"
  l10n_it_withholding_tax/models/account.py
Labels: approved, bot is merging ⏳

#2521 [12.0] ADD l10n_it_pos_fatturapa_send_directly
  l10n_it_pos_fatturapa_send_directly/__init__.py
  l10n_it_pos_fatturapa_send_directly/__manifest__.py
  l10n_it_pos_fatturapa_send_directly/models/__init__.py
  l10n_it_pos_fatturapa_send_directly/models/pos_order.py
  l10n_it_pos_fatturapa_send_directly/readme/CONTRIBUTORS.rst
  l10n_it_pos_fatturapa_send_directly/readme/DESCRIPTION.rst
  setup/l10n_it_pos_fatturapa_send_directly/.eggs/README.txt
  setup/l10n_it_pos_fatturapa_send_directly/odoo/addons/l10n_it_pos_fatturapa_send_directly
  setup/l10n_it_pos_fatturapa_send_directly/setup.py
Labels: bot is merging ⏳

#2614 [12.0][FIX] fiscal_epos_print, missing translation
  fiscal_epos_print/models/account.py
  fiscal_epos_print/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳
