Repository OCA/l10n-italy, pull requests merged in 2022-08, with the labels that each got.

#2828 14.0-mig-l10n_it_location_nuts
  l10n_it_location_nuts/README.rst
  l10n_it_location_nuts/__init__.py
  l10n_it_location_nuts/__manifest__.py
  l10n_it_location_nuts/hooks.py
  l10n_it_location_nuts/i18n/it.po
  l10n_it_location_nuts/i18n/l10n_it_location_nuts.pot
  l10n_it_location_nuts/readme/CONFIGURE.rst
  l10n_it_location_nuts/readme/CONTRIBUTORS.rst
  l10n_it_location_nuts/readme/DESCRIPTION.rst
  l10n_it_location_nuts/static/description/icon.png
  l10n_it_location_nuts/static/description/index.html
  l10n_it_location_nuts/tests/__init__.py
  l10n_it_location_nuts/tests/test_nuts.py
  l10n_it_location_nuts/wizard/__init__.py
  l10n_it_location_nuts/wizard/nuts_import.py
  setup/l10n_it_location_nuts/odoo/addons/l10n_it_location_nuts
  setup/l10n_it_location_nuts/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2886 [FIX] l10n_it_invoices_data_communication: use accounting date to sel…
  l10n_it_invoices_data_communication/models/communication.py
Labels: approved, ready to merge, bot is merging ⏳

#2866 [12.0][FIX] l10n_it_fatturapa_out_wt tests
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00014.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00017.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00018.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00019.xml
  l10n_it_fatturapa_out_wt/tests/test_fatturapa_wt.py
Labels: bot is merging ⏳

#2892 [12.0][FIX] l10n_it_delivery_note display_name depends on itself
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: bot is merging ⏳

#2899 l10n_it_delivery_note: Rimuovere Byloth dai maintainer
  l10n_it_delivery_note/__manifest__.py
Labels: approved, bot is merging ⏳

#2900 l10n_it_delivery_note: Rimuovere Byloth dai maintainer
  l10n_it_delivery_note/__manifest__.py
Labels: approved, bot is merging ⏳

#2859 [BKP] l10n_it_reverse_charge supporting "with_supplier_self_invoice" for e-invoices + link supplier self invoice to e-invoice
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in_rc/models/__init__.py
  l10n_it_fatturapa_in_rc/models/attachment.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/models/account_rc_type.py
  l10n_it_reverse_charge/static/description/fiscal_pos_extra.png
  l10n_it_reverse_charge/static/description/rc_selfinvoice_extra.png
  l10n_it_reverse_charge/tests/__init__.py
  l10n_it_reverse_charge/tests/rc_common.py
  l10n_it_reverse_charge/tests/test_account_rc_type.py
  l10n_it_reverse_charge/tests/test_rc.py
  l10n_it_reverse_charge/views/account_rc_type_view.xml
Labels: bot is merging ⏳

#2042 [12.0][l10n_it_fatturapa_out] trasmissione degli importi in EUR per fatture in valuta estera
  l10n_it_fatturapa_out/models/company.py
  l10n_it_fatturapa_out/tests/data/IT06363391001_00009.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00015.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00015a.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/views/company_view.xml
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00006.xml
  l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml
  l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py
Labels: approved, ready to merge, bot is merging ⏳

#2910 [FIX] Controllo IdFiscaleIVA solo per fornitori italiani
  l10n_it_fatturapa_in/models/partner.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_x05mX.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#2884 Permettere di ricevere notifiche per la ricezione di fatture elettroniche o notifiche
  l10n_it_fatturapa_sdicoop/tests/__init__.py
  l10n_it_fatturapa_sdicoop/tests/data/IT05979361218_001.xml
  l10n_it_fatturapa_sdicoop/tests/test_notification.py
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/data/mail_message_subtype_data.xml
  l10n_it_sdi_channel/models/__init__.py
  l10n_it_sdi_channel/models/fatturapa_attachment.py
  l10n_it_sdi_channel/models/fatturapa_attachment_out.py
  l10n_it_sdi_channel/models/sdi.py
  l10n_it_sdi_channel/views/sdi_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2515 [FIX] l10n_it_split_payment: fix unbalanced lines
  l10n_it_fatturapa_out_sp/tests/data/IT06363391001_00004.xml
  l10n_it_split_payment/models/account.py
  l10n_it_split_payment/readme/CONTRIBUTORS.rst
  l10n_it_split_payment/tests/test_splitpayment.py
  l10n_it_split_payment/views/account_view.xml
Labels: bot is merging ⏳

#2027 [8.0][FIX] l10n_it_fatturapa_in: link already open vendor invoices fr…
  .travis.yml
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
Labels: bot is merging ⏳

#2797 [FIX] Fixed negative quantity on electronic invoices
  l10n_it_fatturapa_out/tests/data/IT06363391001_00014.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2911 [14.0][IMP] ability to link already open vendor invoices from xml received
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#2890 [14.0][ADD] l10n_it_fatturapa_out: aggiunto stato e-fattura in lista note credito
  l10n_it_fatturapa_out/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳
