Repository OCA/l10n-italy, pull requests merged in 2022-03, with the labels that each got.

#2666 [12.0][FIX] l10n_it_fatturapa_in: show if a file contains self invoices
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2574 [14.0][MIG] l10n_it_pos_fiscalcode
  l10n_it_pos_fiscalcode/README.rst
  l10n_it_pos_fiscalcode/__init__.py
  l10n_it_pos_fiscalcode/__manifest__.py
  l10n_it_pos_fiscalcode/i18n/it.po
  l10n_it_pos_fiscalcode/i18n/l10n_it_pos_fiscalcode.pot
  l10n_it_pos_fiscalcode/readme/CONTRIBUTORS.rst
  l10n_it_pos_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_pos_fiscalcode/static/description/icon.png
  l10n_it_pos_fiscalcode/static/description/index.html
  l10n_it_pos_fiscalcode/static/src/js/models.js
  l10n_it_pos_fiscalcode/static/src/xml/pos.xml
  l10n_it_pos_fiscalcode/views/assets.xml
  setup/l10n_it_pos_fiscalcode/odoo/addons/l10n_it_pos_fiscalcode
  setup/l10n_it_pos_fiscalcode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2604 [14.0] l10n_it_delivery_note: fix print depending on picking_type instead of type_code
  l10n_it_delivery_note/report/report_delivery_note.xml
Labels: approved, ready to merge, bot is merging ⏳

#2084 [12.0][FIX] l10n_it_fatturapa_sale: field permissions
  l10n_it_fatturapa_sale/models/sale_order.py
  l10n_it_fatturapa_sale/models/sale_order_line.py
Labels: approved, ready to merge, bot is merging ⏳

#2582 [IMP] added declaration multi-company rules
  l10n_it_declaration_of_intent/__manifest__.py
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/security/declaration_security.xml
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, ready to merge, bot is merging ⏳

#2695 [14.0][FIX] l10n_it_delivery_note: force currency in DN line_note
  l10n_it_delivery_note/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2685 [14.0][FIX] l10n_it_account_stamp: add post-migrate script to migrate tax_stamp
  l10n_it_account_stamp/migrations/13.0.1.0.0/post-migrate.py
Labels: approved, ready to merge, bot is merging ⏳

#2686 [12.0] [IMP] Intrastat 2022
  l10n_it_intrastat/README.rst
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/data/account.intrastat.transaction.nature.b.csv
  l10n_it_intrastat/data/account.intrastat.transaction.nature.csv
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/models/config.py
  l10n_it_intrastat/models/intrastat.py
  l10n_it_intrastat/readme/CONTRIBUTORS.rst
  l10n_it_intrastat/security/ir.model.access.csv
  l10n_it_intrastat/static/description/index.html
  l10n_it_intrastat/views/account.xml
  l10n_it_intrastat/views/config.xml
  l10n_it_intrastat/views/intrastat.xml
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_section.py
  l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
  l10n_it_intrastat_statement/views/intrastat.xml
Labels: bot is merging ⏳

#2703 [14.0][FIX] l10n_italy_delivery_note_order_link enabled without use_advanced_delivery_note flag
  l10n_it_delivery_note_order_link/views/purchase_order.xml
  l10n_it_delivery_note_order_link/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#2705 [12.0][FIX] l10n_it_fatturapa_in, skip registered invoice in _compute_xml_data
  l10n_it_fatturapa_in/models/attachment.py
Labels: approved, bot is merging ⏳

#2569 [14.0][FIX] l10n_it_delivery_note: unable to create DN without sale order
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
  l10n_it_delivery_note/wizard/delivery_note_select.py
Labels: needs fixing, bot is merging ⏳

#2725 [FIX] l10n_it_reverse_charge: forward return of super in action_post method
  l10n_it_reverse_charge/models/account_move.py
Labels: bot is merging ⏳

#2724 [FIX] l10n_it_ricevute_bancarie: missing return in action_post method
  l10n_it_ricevute_bancarie/models/account.py
Labels: bot is merging ⏳

#2729 [12.0] FIX l10n_it_ddt: ValueError: Expected singleton: stock.picking.package.preparation(2, 1)
  l10n_it_ddt/models/stock_picking_package_preparation.py
Labels: approved, bot is merging ⏳

#2719 [FIX] l10n_it_intrastat_statement: Allineamento colonne report modelli intra bis
  l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
Labels: approved, ready to merge, bot is merging ⏳

#2730 [FIX] l10n_it_fatturapa_in - use .get_fiscal_position() instead of the value of the field
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#2736 [FIX][l10n_it_delivery_note] fix missing return result of super and m…
  l10n_it_delivery_note/models/stock_picking.py
Labels: bot is merging ⏳
