Repository OCA/l10n-italy, pull requests merged in 2022-09, with the labels that each got.

#2820 [14.0] [IMP] move FPA Schema xsd to l10n_it_account
  .pre-commit-config.yaml
  l10n_it_account/__manifest__.py
  l10n_it_account/tests/test_l10n_it_account.py
  l10n_it_account/tools/account_tools.py
  l10n_it_account/tools/xsd/Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd
  l10n_it_account/tools/xsd/xmldsig-core-schema.xsd
  l10n_it_account_tax_kind/tests/test_account_tax_kind.py
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/wizard/efattura.py
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/wizard/efattura.py
  l10n_it_fiscal_document_type/tests/test_doc_type.py
  l10n_it_fiscal_payment_term/tests/__init__.py
  l10n_it_fiscal_payment_term/tests/test_fiscal_payment_term.py
  l10n_it_payment_reason/tests/test_reason.py
  requirements.txt
  setup/l10n_it_account/setup.py
Labels: bot is merging ⏳

#2848 [14.0][MIG] l10n_it_fatturapa_out_wt: Migration to 14.0
  l10n_it_fatturapa_out_wt/README.rst
  l10n_it_fatturapa_out_wt/__init__.py
  l10n_it_fatturapa_out_wt/__manifest__.py
  l10n_it_fatturapa_out_wt/i18n/it.po
  l10n_it_fatturapa_out_wt/i18n/l10n_it_fatturapa_out_wt.pot
  l10n_it_fatturapa_out_wt/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_wt/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_wt/static/description/icon.png
  l10n_it_fatturapa_out_wt/static/description/index.html
  l10n_it_fatturapa_out_wt/tests/__init__.py
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00011.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00014.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00015.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00016.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00017.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00018.xml
  l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00019.xml
  l10n_it_fatturapa_out_wt/tests/test_fatturapa_wt.py
  l10n_it_fatturapa_out_wt/views/account_invoice_it_dati_ritenuta.xml
  l10n_it_fatturapa_out_wt/wizard/__init__.py
  l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py
  setup/l10n_it_fatturapa_out_wt/odoo/addons/l10n_it_fatturapa_out_wt
  setup/l10n_it_fatturapa_out_wt/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2908 [ADD] l10n_it_fatturapa_out_welfare
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_welfare/README.rst
  l10n_it_fatturapa_out_welfare/__init__.py
  l10n_it_fatturapa_out_welfare/__manifest__.py
  l10n_it_fatturapa_out_welfare/i18n/it.po
  l10n_it_fatturapa_out_welfare/models/__init__.py
  l10n_it_fatturapa_out_welfare/models/account_invoice.py
  l10n_it_fatturapa_out_welfare/models/account_invoice_line.py
  l10n_it_fatturapa_out_welfare/models/welfare_fund_type_amount.py
  l10n_it_fatturapa_out_welfare/readme/CONFIGURE.rst
  l10n_it_fatturapa_out_welfare/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_welfare/readme/USAGE.rst
  l10n_it_fatturapa_out_welfare/security/ir.model.access.csv
  l10n_it_fatturapa_out_welfare/static/description/index.html
  l10n_it_fatturapa_out_welfare/tests/__init__.py
  l10n_it_fatturapa_out_welfare/tests/data/IT06363391001_random.xml
  l10n_it_fatturapa_out_welfare/tests/test_fatturapa_out_welfare.py
  l10n_it_fatturapa_out_welfare/views/account_invoice_line_views.xml
  l10n_it_fatturapa_out_welfare/views/account_invoice_views.xml
  l10n_it_fatturapa_out_welfare/views/welfare_fund_type_amount_views.xml
  l10n_it_fatturapa_out_welfare/wizards/__init__.py
  l10n_it_fatturapa_out_welfare/wizards/wizard_export_fatturapa.py
  setup/l10n_it_fatturapa_out_welfare/odoo/addons/l10n_it_fatturapa_out_welfare
  setup/l10n_it_fatturapa_out_welfare/setup.py
Labels: bot is merging ⏳

#2857 [14.0][IMP] Intrastat 2022
  l10n_it_intrastat/README.rst
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/data/account.intrastat.transaction.nature.b.csv
  l10n_it_intrastat/data/account.intrastat.transaction.nature.csv
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/models/config.py
  l10n_it_intrastat/models/intrastat.py
  l10n_it_intrastat/readme/CONTRIBUTORS.rst
  l10n_it_intrastat/security/ir.model.access.csv
  l10n_it_intrastat/static/description/index.html
  l10n_it_intrastat/views/account.xml
  l10n_it_intrastat/views/config.xml
  l10n_it_intrastat/views/intrastat.xml
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section3.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section2.py
  l10n_it_intrastat_statement/models/intrastat_statement_section.py
  l10n_it_intrastat_statement/readme/CONTRIBUTORS.rst
  l10n_it_intrastat_statement/readme/DESCRIPTION.rst
  l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
  l10n_it_intrastat_statement/views/intrastat.xml
Labels: approved, bot is merging ⏳

#2931 [FIX] l10n_it_account: fix error during vat statement calculation
  l10n_it_account/models/account_tax.py
Labels: approved, bot is merging ⏳

#2764 [12.0] FIX fiscal_epos_print: in caso di omaggi bisogna comunque inviare la corretta "printRecTotal"
  fiscal_epos_print/static/src/js/epson_epos_print.js
Labels: bot is merging ⏳

#2936 [14.0][FIX] l10n_it_intrastat_statement: rendere facoltativo transact…
  l10n_it_intrastat_statement/views/intrastat.xml
Labels: approved, bot is merging ⏳

#2914 [FIX] Controllo IdFiscaleIVA solo per fornitori italiani
  l10n_it_fatturapa_in/models/partner.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_x05mX.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2623 Spostare menu RiBa in modo da renderlo visibile anche nella versione Enterprise
  l10n_it_ricevute_bancarie/models/__init__.py
  l10n_it_ricevute_bancarie/models/ir_ui_menu.py
  l10n_it_ricevute_bancarie/tests/__init__.py
  l10n_it_ricevute_bancarie/tests/test_menu.py
Labels: approved, ready to merge, bot is merging ⏳

#2895 [12.0][FIX] l10n_it_fatturapa_sale security
  l10n_it_fatturapa_sale/__manifest__.py
  l10n_it_fatturapa_sale/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#2826 14.0-fix-l10n_it_split_payments-migration_script_issue
  l10n_it_split_payment/migrations/14.0.1.0.0/post-migration.py
  l10n_it_split_payment/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2925 [12.0] FIX l10n_it_sdi_channel - ValueError: Wrong value for ir.attachment.type: 'out_invoice'
  l10n_it_sdi_channel/models/account_invoice.py
Labels: bot is merging ⏳

#2954 [FIX][l10n_it_fatturapa_export_zip] fix export zip
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
Labels: approved, bot is merging ⏳

#1979 [FIX][l10n_it_fatturapa_in] do not fail import of XML e-invoice on missing/wrong bank account information
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2904 [12.0] IMP l10n_it_reverse_charge showing info about original supplier invoice
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/views/account_invoice_view.xml
Labels: bot is merging ⏳

#2962 [12.0] FIX l10n_it_bill_of_entry : TypeError: exceptions must derive from BaseException
  l10n_it_bill_of_entry/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2945 Fattura elettronica: Specifiche tecniche versione 1.7.1
  l10n_it_fatturapa/bindings/_ds.diff
  l10n_it_fatturapa/bindings/_ds.py
  l10n_it_fatturapa/bindings/binding.diff
  l10n_it_fatturapa/bindings/binding.py
  l10n_it_fatturapa/bindings/fatturapa.py
  l10n_it_fatturapa/bindings/xsd/Schema_del_file_xml_FatturaPA_versione_1.2.2.xsd
  l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
  l10n_it_fatturapa/data/fatturaordinaria_v1.2.1.xsl
  l10n_it_fiscal_document_type/data/fiscal.document.type.csv
Labels: bot is merging ⏳
