Repository OCA/l10n-italy, pull requests merged in 2022-10, with the labels that each got.

#2963 [14.0][IMP] l10n_it_fatturapa, migration script
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/migrations/14.0.1.2.1/post-migration.py
  l10n_it_fatturapa/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2928 [14.0][ADD] l10n_it_central_journal_reportlab: aggiunto modulo libro giornale stampa reportlab
  l10n_it_central_journal_reportlab/README.rst
  l10n_it_central_journal_reportlab/__init__.py
  l10n_it_central_journal_reportlab/__manifest__.py
  l10n_it_central_journal_reportlab/models/__init__.py
  l10n_it_central_journal_reportlab/models/account.py
  l10n_it_central_journal_reportlab/readme/CONTRIBUTORS.rst
  l10n_it_central_journal_reportlab/readme/DESCRIPTION.rst
  l10n_it_central_journal_reportlab/security/ir.model.access.csv
  l10n_it_central_journal_reportlab/static/description/icon.png
  l10n_it_central_journal_reportlab/static/description/index.html
  l10n_it_central_journal_reportlab/tests/__init__.py
  l10n_it_central_journal_reportlab/tests/test_central_journal_reportlab.py
  l10n_it_central_journal_reportlab/views/date_range_view.xml
  l10n_it_central_journal_reportlab/wizard/__init__.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.xml
  setup/l10n_it_central_journal_reportlab/odoo/addons/l10n_it_central_journal_reportlab
  setup/l10n_it_central_journal_reportlab/setup.py
Labels: approved, bot is merging ⏳

#2813 [14.0] [fix] l10n_it_reverse_charge, l10n_it_fatturapa_in_rc - rc flag in move line
  l10n_it_fatturapa_in_rc/models/account_invoice.py
  l10n_it_fatturapa_in_rc/readme/CONTRIBUTORS.rst
  l10n_it_reverse_charge/models/account_move.py
  l10n_it_reverse_charge/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#2976 [14.0][FIX] l10n_it_fatturapa_out_rc: fix tests
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00002.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00003.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00004.xml
  l10n_it_fatturapa_out_rc/tests/test_fatturapa_xml_validation.py
Labels: work in progress, bot is merging ⏳

#2958 [14.0][FIX] l10n_it_fatturapa_in: fix invalid URIs
  l10n_it_fatturapa_in/tests/__init__.py
  l10n_it_fatturapa_in/tests/test_fix_bad_uris.py
  l10n_it_fatturapa_in/wizard/efattura.py
Labels: approved, ready to merge, bot is merging ⏳

#2708 [14.0][imp] l10n_it_sdi_channel, move pec channel to l10n_it_fatturapa_pec
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/data/config_parameter.xml
  l10n_it_fatturapa_pec/data/sdi_channel_demo.xml
  l10n_it_fatturapa_pec/migrations/14.0.1.0.4/pre-migration.py
  l10n_it_fatturapa_pec/models/__init__.py
  l10n_it_fatturapa_pec/models/company.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/ir_mail_server.py
  l10n_it_fatturapa_pec/models/sdi.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_pec/tests/e_invoice_common.py
  l10n_it_fatturapa_pec/views/company_view.xml
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
  l10n_it_fatturapa_pec/views/ir_mail_server.xml
  l10n_it_fatturapa_pec/views/sdi_view.xml
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/models/__init__.py
  l10n_it_sdi_channel/models/company.py
  l10n_it_sdi_channel/models/fetchmail_server.py
  l10n_it_sdi_channel/models/sdi.py
  l10n_it_sdi_channel/readme/CONFIGURE.rst
  l10n_it_sdi_channel/readme/CONTRIBUTORS.rst
  l10n_it_sdi_channel/views/company_view.xml
  l10n_it_sdi_channel/views/fetchmail_server.xml
  l10n_it_sdi_channel/views/sdi_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2983 [14.0][IMP] l10n_it_fatturapa_sale, admin_ref optional
  l10n_it_fatturapa_sale/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_sale/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#2688 [12.0][ADD] new module for OSS invoice management with l10n_it_fatturapa
  l10n_it_fatturapa_out_oss/README.rst
  l10n_it_fatturapa_out_oss/__init__.py
  l10n_it_fatturapa_out_oss/__manifest__.py
  l10n_it_fatturapa_out_oss/i18n/it.po
  l10n_it_fatturapa_out_oss/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_oss/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_oss/static/description/icon.png
  l10n_it_fatturapa_out_oss/static/description/index.html
  l10n_it_fatturapa_out_oss/tests/__init__.py
  l10n_it_fatturapa_out_oss/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_oss/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out_oss/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_oss/wizard/__init__.py
  l10n_it_fatturapa_out_oss/wizard/l10n_eu_oss_wizard.py
  l10n_it_fatturapa_out_oss/wizard/wizard_export_fatturapa.py
  setup/l10n_it_fatturapa_out_oss/odoo/addons/l10n_it_fatturapa_out_oss
  setup/l10n_it_fatturapa_out_oss/setup.py
Labels: bot is merging ⏳
