Repository OCA/l10n-italy, pull requests merged in 2022-11, with the labels that each got.

#3005 [14.0][FIX] Update from copier template to fix pre-commit
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
  l10n_it_fatturapa_in/tests/data/IT05979361218_016.xml
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20001.xml
  l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20005.xml
  l10n_it_fatturapa_in/tests/data/ITNREGCM80H30D612D_20003.xml
  l10n_it_fatturapa_in/tests/data/ITNREGCM80H30D612D_20004.xml
Labels: approved, bot is merging ⏳

#2835 [14.0][FIX] l10n_it_instrastat, account move: fix subject to intrastat on partner change and purchase order
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/models/__init__.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/models/sale_order.py
  l10n_it_intrastat/tests/test_intrastat.py
Labels: approved, bot is merging ⏳

#2082 [12.0] [ADD] l10n_it_delivery_note: gross_weight and net_weight computation from pickings
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: bot is merging ⏳

#2989 [16.0] [MIG] l10n_it_vat_payability
  l10n_it_vat_payability/README.rst
  l10n_it_vat_payability/__init__.py
  l10n_it_vat_payability/__manifest__.py
  l10n_it_vat_payability/i18n/es_AR.po
  l10n_it_vat_payability/i18n/it.po
  l10n_it_vat_payability/i18n/l10n_it_vat_payability.pot
  l10n_it_vat_payability/models/__init__.py
  l10n_it_vat_payability/models/account_tax.py
  l10n_it_vat_payability/readme/CONTRIBUTORS.rst
  l10n_it_vat_payability/readme/DESCRIPTION.rst
  l10n_it_vat_payability/static/description/icon.png
  l10n_it_vat_payability/static/description/index.html
  l10n_it_vat_payability/views/account_view.xml
  requirements.txt
  setup/l10n_it_vat_payability/odoo/addons/l10n_it_vat_payability
  setup/l10n_it_vat_payability/setup.py
Labels: approved, bot is merging ⏳

#3017 [IMP] [16.0] add exceptions to dotfiles
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#3023 [14.0][IMP]l10n_it_abicab: Remove unnecessary method "onchange_bank_id"
  l10n_it_abicab/models/abicab.py
  l10n_it_abicab/tests/test_abicab.py
Labels: approved, bot is merging ⏳

#3014 [FIX][l10n_it_fatturapa_in] fix fiscal position parameter
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#2990 [16.0] [MIG] l10n_it_account
  l10n_it_account/README.rst
  l10n_it_account/__init__.py
  l10n_it_account/__manifest__.py
  l10n_it_account/i18n/es_AR.po
  l10n_it_account/i18n/it.po
  l10n_it_account/i18n/l10n_it_account.pot
  l10n_it_account/i18n/sl.po
  l10n_it_account/migrations/16.0.1.0.0/post-migrate_balance_sign.py
  l10n_it_account/models/__init__.py
  l10n_it_account/models/account_account.py
  l10n_it_account/models/account_group.py
  l10n_it_account/models/account_tax.py
  l10n_it_account/readme/CONTRIBUTORS.rst
  l10n_it_account/readme/CREDITS.rst
  l10n_it_account/readme/DESCRIPTION.rst
  l10n_it_account/reports/account_reports_view.xml
  l10n_it_account/static/description/icon.png
  l10n_it_account/static/description/index.html
  l10n_it_account/static/src/css/l10n_it_account.css
  l10n_it_account/tests/__init__.py
  l10n_it_account/tests/test_l10n_it_account.py
  l10n_it_account/tools/__init__.py
  l10n_it_account/tools/account_tools.py
  l10n_it_account/tools/xsd/Schema_del_file_xml_FatturaPA_v1.2.2.xsd
  l10n_it_account/tools/xsd/xmldsig-core-schema.xsd
  l10n_it_account/views/account_menuitem.xml
  l10n_it_account/views/account_setting.xml
  l10n_it_account/views/account_view.xml
  l10n_it_account/views/partner_view.xml
  l10n_it_account/views/product_view.xml
  l10n_it_account/views/res_config_settings_views.xml
  requirements.txt
  setup/l10n_it_account/odoo/addons/l10n_it_account
  setup/l10n_it_account/setup.py
Labels: approved, bot is merging ⏳

#2992 [16.0] [MIG] l10n_it_fiscal_payment_term
  l10n_it_fiscal_payment_term/README.rst
  l10n_it_fiscal_payment_term/__init__.py
  l10n_it_fiscal_payment_term/__manifest__.py
  l10n_it_fiscal_payment_term/data/fatturapa_data.xml
  l10n_it_fiscal_payment_term/i18n/it.po
  l10n_it_fiscal_payment_term/i18n/l10n_it_fiscal_payment_term.pot
  l10n_it_fiscal_payment_term/models/__init__.py
  l10n_it_fiscal_payment_term/models/account.py
  l10n_it_fiscal_payment_term/readme/CONFIGURE.rst
  l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
  l10n_it_fiscal_payment_term/readme/DESCRIPTION.rst
  l10n_it_fiscal_payment_term/security/ir.model.access.csv
  l10n_it_fiscal_payment_term/static/description/icon.png
  l10n_it_fiscal_payment_term/static/description/index.html
  l10n_it_fiscal_payment_term/tests/__init__.py
  l10n_it_fiscal_payment_term/tests/test_fiscal_payment_term.py
  l10n_it_fiscal_payment_term/views/account_view.xml
  setup/l10n_it_fiscal_payment_term/odoo/addons/l10n_it_fiscal_payment_term
  setup/l10n_it_fiscal_payment_term/setup.py
Labels: bot is merging ⏳

#3018 [16.0] Update from copier template
  .copier-answers.yml
  README.md
Labels: bot is merging ⏳

#3036 [16.0][MIG] l10n_it_abicab
  l10n_it_abicab/README.rst
  l10n_it_abicab/__init__.py
  l10n_it_abicab/__manifest__.py
  l10n_it_abicab/i18n/de.po
  l10n_it_abicab/i18n/it.po
  l10n_it_abicab/i18n/l10n_it_abicab.pot
  l10n_it_abicab/i18n/nb_NO.po
  l10n_it_abicab/i18n/sl.po
  l10n_it_abicab/models/__init__.py
  l10n_it_abicab/models/abicab.py
  l10n_it_abicab/readme/CONTRIBUTORS.rst
  l10n_it_abicab/readme/DESCRIPTION.rst
  l10n_it_abicab/static/description/icon.png
  l10n_it_abicab/static/description/index.html
  l10n_it_abicab/tests/__init__.py
  l10n_it_abicab/tests/test_abicab.py
  l10n_it_abicab/views/abicab_view.xml
  setup/l10n_it_abicab/odoo/addons/l10n_it_abicab
  setup/l10n_it_abicab/setup.py
Labels: approved, bot is merging ⏳

#3039 [16.0] Update from copier template
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#3021 [16.0] [MIG] l10n_it_account_stamp
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__init__.py
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/i18n/it.po
  l10n_it_account_stamp/i18n/l10n_it_account_stamp.pot
  l10n_it_account_stamp/models/__init__.py
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/models/company.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp/readme/DESCRIPTION.rst
  l10n_it_account_stamp/readme/USAGE.rst
  l10n_it_account_stamp/static/description/icon.png
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/tests/__init__.py
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
  l10n_it_account_stamp/views/account_move_view.xml
  l10n_it_account_stamp/views/company_view.xml
  l10n_it_account_stamp/views/product_view.xml
  setup/l10n_it_account_stamp/odoo/addons/l10n_it_account_stamp
  setup/l10n_it_account_stamp/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3041 [14.0] [FIX] category in manifest file
  l10n_it_location_nuts/__manifest__.py
Labels: bot is merging ⏳

#2973 [FIX][l10n_it_fatturapa_out] fix FE to private people
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00016.xml
  l10n_it_fatturapa_out/wizard/efattura.py
Labels: approved, bot is merging ⏳

#3003 [12.0] [FIX] XML "show preview" not translatable
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/views/fatturapa_attachment_views.xml
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, bot is merging ⏳

#3040 [12.0] Update from copier template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#3004 [14.0] [FIX] XML "show preview" not translatable
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_out/models/attachment.py
  l10n_it_fatturapa_out/views/attachment_view.xml
Labels: approved, bot is merging ⏳

#3001 [16.0][MIG] l10n_it_appointment_code
  l10n_it_appointment_code/README.rst
  l10n_it_appointment_code/__init__.py
  l10n_it_appointment_code/__manifest__.py
  l10n_it_appointment_code/data/appointment_code_data.xml
  l10n_it_appointment_code/i18n/it.po
  l10n_it_appointment_code/i18n/l10n_it_appointment_code.pot
  l10n_it_appointment_code/models/__init__.py
  l10n_it_appointment_code/models/appointment_code.py
  l10n_it_appointment_code/readme/CONFIGURE.rst
  l10n_it_appointment_code/readme/CONTRIBUTORS.rst
  l10n_it_appointment_code/readme/DESCRIPTION.rst
  l10n_it_appointment_code/readme/USAGE.rst
  l10n_it_appointment_code/security/ir.model.access.csv
  l10n_it_appointment_code/static/description/icon.png
  l10n_it_appointment_code/static/description/index.html
  l10n_it_appointment_code/views/appointment_code_view.xml
  setup/l10n_it_appointment_code/odoo/addons/l10n_it_appointment_code
  setup/l10n_it_appointment_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2740 [12.0] [FIX] l10n_it_dichiarazione_intento: avoid duplicating messages in in…
  l10n_it_dichiarazione_intento/models/account_invoice.py
Labels: bot is merging ⏳

#3059 [14.0] [FIX] l10n_it_declaration_of_intent: avoid duplicating messages in in…
  l10n_it_declaration_of_intent/models/account_move.py
Labels: bot is merging ⏳

#2997 [16.0] [MIG] l10n_it_payment_reason
  l10n_it_payment_reason/README.rst
  l10n_it_payment_reason/__init__.py
  l10n_it_payment_reason/__manifest__.py
  l10n_it_payment_reason/data/payment_reason_data.xml
  l10n_it_payment_reason/i18n/it.po
  l10n_it_payment_reason/i18n/l10n_it_payment_reason.pot
  l10n_it_payment_reason/models/__init__.py
  l10n_it_payment_reason/models/payment_reason.py
  l10n_it_payment_reason/readme/CONFIGURE.rst
  l10n_it_payment_reason/readme/CONTRIBUTORS.rst
  l10n_it_payment_reason/readme/DESCRIPTION.rst
  l10n_it_payment_reason/readme/USAGE.rst
  l10n_it_payment_reason/security/ir.model.access.csv
  l10n_it_payment_reason/static/description/icon.png
  l10n_it_payment_reason/static/description/index.html
  l10n_it_payment_reason/tests/__init__.py
  l10n_it_payment_reason/tests/test_reason.py
  l10n_it_payment_reason/views/payment_reason_view.xml
  setup/l10n_it_payment_reason/odoo/addons/l10n_it_payment_reason
  setup/l10n_it_payment_reason/setup.py
Labels: approved, ready to merge, bot is merging ⏳
