Repository OCA/l10n-italy, pull requests merged in 2022-12, with the labels that each got.

#3019 [16.0][MIG] l10n_it_delivery_note_base
  l10n_it_delivery_note_base/README.rst
  l10n_it_delivery_note_base/__init__.py
  l10n_it_delivery_note_base/__manifest__.py
  l10n_it_delivery_note_base/data/delivery_note_data.xml
  l10n_it_delivery_note_base/i18n/it.po
  l10n_it_delivery_note_base/i18n/l10n_it_delivery_note_base.pot
  l10n_it_delivery_note_base/models/__init__.py
  l10n_it_delivery_note_base/models/stock_delivery_note_type.py
  l10n_it_delivery_note_base/models/stock_picking_goods_appearance.py
  l10n_it_delivery_note_base/models/stock_picking_transport_condition.py
  l10n_it_delivery_note_base/models/stock_picking_transport_method.py
  l10n_it_delivery_note_base/models/stock_picking_transport_reason.py
  l10n_it_delivery_note_base/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note_base/readme/DESCRIPTION.rst
  l10n_it_delivery_note_base/security/ir.model.access.csv
  l10n_it_delivery_note_base/security/ir_module_category.xml
  l10n_it_delivery_note_base/security/ir_rule.xml
  l10n_it_delivery_note_base/security/res_groups.xml
  l10n_it_delivery_note_base/security/res_users.xml
  l10n_it_delivery_note_base/static/description/icon.png
  l10n_it_delivery_note_base/static/description/index.html
  l10n_it_delivery_note_base/views/stock_delivery_note_type.xml
  l10n_it_delivery_note_base/views/stock_picking_goods_appearance.xml
  l10n_it_delivery_note_base/views/stock_picking_transport_condition.xml
  l10n_it_delivery_note_base/views/stock_picking_transport_method.xml
  l10n_it_delivery_note_base/views/stock_picking_transport_reason.xml
  setup/l10n_it_delivery_note_base/odoo/addons/l10n_it_delivery_note_base
  setup/l10n_it_delivery_note_base/setup.py
Labels: bot is merging ⏳

#2998 [16.0] [MIG] l10n_it_withholding_tax
  l10n_it_withholding_tax/README.rst
  l10n_it_withholding_tax/__init__.py
  l10n_it_withholding_tax/__manifest__.py
  l10n_it_withholding_tax/i18n/it.po
  l10n_it_withholding_tax/i18n/l10n_it_withholding_tax.pot
  l10n_it_withholding_tax/migrations/13.0.1.0.0/noupdate_changes.xml
  l10n_it_withholding_tax/migrations/13.0.1.0.0/post-migration.py
  l10n_it_withholding_tax/migrations/13.0.1.0.0/pre-migration.py
  l10n_it_withholding_tax/models/__init__.py
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax/readme/DESCRIPTION.rst
  l10n_it_withholding_tax/readme/USAGE.rst
  l10n_it_withholding_tax/security/ir.model.access.csv
  l10n_it_withholding_tax/security/security.xml
  l10n_it_withholding_tax/static/description/icon.png
  l10n_it_withholding_tax/static/description/index.html
  l10n_it_withholding_tax/static/img/fattura-fornitore-768x517.png
  l10n_it_withholding_tax/static/img/foto-3-1-1024x505.png
  l10n_it_withholding_tax/static/img/pagamento-fattura-fornitore.png
  l10n_it_withholding_tax/static/img/pagamento-ritenuta.png
  l10n_it_withholding_tax/static/img/ritenuta-acconto-odoo-codifica-768x457.png
  l10n_it_withholding_tax/static/src/xml/account_payment.xml
  l10n_it_withholding_tax/tests/__init__.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
  l10n_it_withholding_tax/views/account.xml
  l10n_it_withholding_tax/views/report_invoice.xml
  l10n_it_withholding_tax/views/withholding_tax.xml
  setup/l10n_it_withholding_tax/odoo/addons/l10n_it_withholding_tax
  setup/l10n_it_withholding_tax/setup.py
Labels: approved, ready to merge, bot is merging ⏳, needs functional review

#3086 [12.0][UPD] copier
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
Labels: bot is merging ⏳

#2999 [16.0] [MIG] l10n_it_withholding_tax_reason
  l10n_it_withholding_tax_reason/README.rst
  l10n_it_withholding_tax_reason/__init__.py
  l10n_it_withholding_tax_reason/__manifest__.py
  l10n_it_withholding_tax_reason/i18n/it.po
  l10n_it_withholding_tax_reason/i18n/l10n_it_withholding_tax_reason.pot
  l10n_it_withholding_tax_reason/models/__init__.py
  l10n_it_withholding_tax_reason/models/withholding_tax.py
  l10n_it_withholding_tax_reason/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax_reason/readme/DESCRIPTION.rst
  l10n_it_withholding_tax_reason/readme/INSTALL.rst
  l10n_it_withholding_tax_reason/static/description/icon.png
  l10n_it_withholding_tax_reason/static/description/index.html
  l10n_it_withholding_tax_reason/views/withholding_tax.xml
  setup/l10n_it_withholding_tax_reason/odoo/addons/l10n_it_withholding_tax_reason
  setup/l10n_it_withholding_tax_reason/setup.py
Labels: bot is merging ⏳, needs functional review

#3081 [16.0][MIG] l10n_it_declaration_of_intent
  l10n_it_declaration_of_intent/README.rst
  l10n_it_declaration_of_intent/__init__.py
  l10n_it_declaration_of_intent/__manifest__.py
  l10n_it_declaration_of_intent/data/sequence.xml
  l10n_it_declaration_of_intent/i18n/it.po
  l10n_it_declaration_of_intent/i18n/l10n_it_declaration_of_intent.pot
  l10n_it_declaration_of_intent/i18n/l10n_it_dichiarazione_intento.pot
  l10n_it_declaration_of_intent/models/__init__.py
  l10n_it_declaration_of_intent/models/account.py
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/models/company.py
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/models/product.py
  l10n_it_declaration_of_intent/models/sale.py
  l10n_it_declaration_of_intent/readme/CONFIGURE.rst
  l10n_it_declaration_of_intent/readme/CONTRIBUTORS.rst
  l10n_it_declaration_of_intent/readme/DESCRIPTION.rst
  l10n_it_declaration_of_intent/readme/ROADMAP.rst
  l10n_it_declaration_of_intent/readme/USAGE.rst
  l10n_it_declaration_of_intent/security/declaration_security.xml
  l10n_it_declaration_of_intent/security/ir.model.access.csv
  l10n_it_declaration_of_intent/static/description/icon.png
  l10n_it_declaration_of_intent/static/description/index.html
  l10n_it_declaration_of_intent/tests/__init__.py
  l10n_it_declaration_of_intent/tests/test_account.py
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
  l10n_it_declaration_of_intent/views/account_invoice_view.xml
  l10n_it_declaration_of_intent/views/account_view.xml
  l10n_it_declaration_of_intent/views/company_view.xml
  l10n_it_declaration_of_intent/views/declaration_of_intent_view.xml
  l10n_it_declaration_of_intent/wizard/__init__.py
  l10n_it_declaration_of_intent/wizard/select_declarations.py
  l10n_it_declaration_of_intent/wizard/select_declarations_view.xml
  setup/l10n_it_declaration_of_intent/odoo/addons/l10n_it_declaration_of_intent
  setup/l10n_it_declaration_of_intent/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3087 [12.0][FIX] l10n_it_delivery_note sequenza multi anno
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/tests/__init__.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_sequence.py
Labels: approved, bot is merging ⏳

#3099 [14.0][FIX] sequence with context date, to get correct sequence in date range scenario
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/tests/__init__.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_sequence.py
Labels: bot is merging ⏳

#3091 [FIX] l10n_it_account: show Date ranges sub menus
  l10n_it_account/__manifest__.py
  l10n_it_account/views/account_menuitem.xml
  l10n_it_account/views/account_setting.xml
Labels: bot is merging ⏳
