Repository OCA/l10n-italy, pull requests merged in 2022-02, with the labels that each got.

#2559 [14.0][MIG] l10n_it_fatturapa_out_rc
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/models/account.py
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/wizard/efattura.py
  l10n_it_fatturapa_out_rc/README.rst
  l10n_it_fatturapa_out_rc/__init__.py
  l10n_it_fatturapa_out_rc/__manifest__.py
  l10n_it_fatturapa_out_rc/i18n/it.po
  l10n_it_fatturapa_out_rc/i18n/l10n_it_fatturapa_out_rc.pot
  l10n_it_fatturapa_out_rc/models/__init__.py
  l10n_it_fatturapa_out_rc/models/account_move.py
  l10n_it_fatturapa_out_rc/models/rc_type.py
  l10n_it_fatturapa_out_rc/readme/CONFIGURE.rst
  l10n_it_fatturapa_out_rc/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_rc/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_rc/static/description/icon.png
  l10n_it_fatturapa_out_rc/static/description/index.html
  l10n_it_fatturapa_out_rc/tests/__init__.py
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00002.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00003.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00004.xml
  l10n_it_fatturapa_out_rc/tests/fatturapa_common.py
  l10n_it_fatturapa_out_rc/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_rc/views/invoice_it_template.xml
  l10n_it_fatturapa_out_rc/views/rc_type_views.xml
  l10n_it_fatturapa_out_rc/wizard/__init__.py
  l10n_it_fatturapa_out_rc/wizard/efattura.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_sp/view/invoice_it_template.xml
  setup/l10n_it_fatturapa_out_rc/odoo/addons/l10n_it_fatturapa_out_rc
  setup/l10n_it_fatturapa_out_rc/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2553 [14.0][FIX] l10n_it_fatturapa_in: show if a file contains self invoices
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2635 [14.0][FIX] failure in test due to changes in note handling in core
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: bot is merging ⏳

#2632 [14.0][FIX] l10n_it_fatturapa_out_rc: skip preventive checks when there are no invoices with rc
  l10n_it_fatturapa_out_rc/models/account_move.py
Labels: bot is merging ⏳

#2627 [14.0][FIX] l10n_it_declaration_of_intent: duplicated line_ids
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, bot is merging ⏳

#2198 [14.0] Migration: l10n_it_fatturapa_pec
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__init__.py
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/data/fetchmail_data.xml
  l10n_it_fatturapa_pec/i18n/it.po
  l10n_it_fatturapa_pec/i18n/l10n_it_fatturapa_pec.pot
  l10n_it_fatturapa_pec/models/__init__.py
  l10n_it_fatturapa_pec/models/company.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_pec/readme/DESCRIPTION.rst
  l10n_it_fatturapa_pec/readme/USAGE.rst
  l10n_it_fatturapa_pec/security/groups.xml
  l10n_it_fatturapa_pec/security/ir.model.access.csv
  l10n_it_fatturapa_pec/static/description/icon.png
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/tests/__init__.py
  l10n_it_fatturapa_pec/tests/data/ACCETTAZIONE_ IT03339130126_00009.xml.txt
  l10n_it_fatturapa_pec/tests/data/CONSEGNA_ IT03339130126_00009.xml.txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Invio File 7339338 (broken XML).txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Invio File 7339338.txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Ricevuta di consegna 6782414.txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_mancata_consegna.txt
  l10n_it_fatturapa_pec/tests/e_invoice_common.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
  l10n_it_fatturapa_pec/views/company_view.xml
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
  l10n_it_fatturapa_pec/wizard/__init__.py
  l10n_it_fatturapa_pec/wizard/send_pec.py
  l10n_it_fatturapa_pec/wizard/send_pec_view.xml
  setup/l10n_it_fatturapa_pec/odoo/addons/l10n_it_fatturapa_pec
  setup/l10n_it_fatturapa_pec/setup.py
Labels: bot is merging ⏳

#2638 [12.0] Show "E-Bill Received Date" in supplier invoice tree, in order to facilitate registration in correct order
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, bot is merging ⏳

#2593 [12.0][IMP] l10n_it_dichiarazione_intento: Supporto per multi-company
  l10n_it_dichiarazione_intento/__manifest__.py
  l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
  l10n_it_dichiarazione_intento/security/declaration_security.xml
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: approved, ready to merge, bot is merging ⏳

#2640 [14.0][FIX] l10n_it_declaration_of_intent: wrong calculation in get_declaration_residual_amounts method and KeyError exception in check_declarations_amounts
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, bot is merging ⏳

#2517 [10.0][BKP] l10n_it_fatturapa_out_rc: Backporting da 12.0
  .travis.yml
  l10n_it_account/__init__.py
  l10n_it_account/tools/__init__.py
  l10n_it_account/tools/account_tools.py
  l10n_it_fatturapa_out_rc/README.rst
  l10n_it_fatturapa_out_rc/__init__.py
  l10n_it_fatturapa_out_rc/__manifest__.py
  l10n_it_fatturapa_out_rc/i18n/it.po
  l10n_it_fatturapa_out_rc/i18n/l10n_it_fatturapa_out_rc.pot
  l10n_it_fatturapa_out_rc/models/__init__.py
  l10n_it_fatturapa_out_rc/models/account_invoice.py
  l10n_it_fatturapa_out_rc/models/rc_type.py
  l10n_it_fatturapa_out_rc/readme/CONFIGURE.rst
  l10n_it_fatturapa_out_rc/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_rc/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_rc/static/description/icon.png
  l10n_it_fatturapa_out_rc/static/description/index.html
  l10n_it_fatturapa_out_rc/tests/__init__.py
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00002.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00003.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00004.xml
  l10n_it_fatturapa_out_rc/tests/test_e_invoice_out_rc.py
  l10n_it_fatturapa_out_rc/views/rc_type_views.xml
  l10n_it_fatturapa_out_rc/wizard/__init__.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py
  l10n_it_invoices_data_communication/__manifest__.py
  l10n_it_invoices_data_communication/models/communication.py
  l10n_it_reverse_charge/__manifest__.py
  l10n_it_reverse_charge/models/account_rc_type.py
  l10n_it_reverse_charge/security/reverse_charge_security.xml
  l10n_it_reverse_charge/tests/rc_common.py
  l10n_it_reverse_charge/tests/test_rc.py
  l10n_it_reverse_charge/views/account_rc_type_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2622 [10.0][fix] l10n_it_dichiarazione_intento: exception creating invoice with partner already associated to a declaration of intent
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: approved, ready to merge, bot is merging ⏳

#2648 [14.0][IMP] l10n_it_account: manage multi-company report
  l10n_it_account/reports/account_reports_view.xml
Labels: approved, bot is merging ⏳
