Repository OCA/l10n-italy, pull requests merged in 2022-04, with the labels that each got.

#2657 [12.0] REF l10n_it_withholding_tax withholding.tax display_name with cleaner implementation
  l10n_it_withholding_tax/models/withholding_tax.py
Labels: bot is merging ⏳

#2741 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
  l10n_it_abicab/views/abicab_view.xml
  l10n_it_account/models/account_group.py
  l10n_it_account_tax_kind/tests/test_account_tax_kind.py
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/views/partner_view.xml
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_out_rc/wizard/efattura.py
  l10n_it_intrastat_statement/i18n/l10n_it_intrastat_statement.pot
  l10n_it_intrastat_statement/models/__init__.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section2.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section3.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section4.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section2.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section3.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section4.py
  l10n_it_invoices_data_communication/models/communication.py
  l10n_it_rea/views/company_view.xml
  test-requirements.txt
Labels: help wanted, needs review, approved, bot is merging ⏳

#2765 [FIX] l10n_it_fatturapa_in: fix compare between float values
  l10n_it_fatturapa_in/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#2548 [10.0] l10n_it_dichiarazione_intento: Validazione massiva di fatture
  l10n_it_dichiarazione_intento/models/account_invoice.py
  l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py
Labels: bot is merging ⏳

#2732 [14.0][FIX] l10n_it_withholding_tax: allow to record payments by selecting vendor bills from Bills tree view
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#2752 [FIX] fiscal_epos_print: Impedire stampa scontrini diversi per la stampante fiscale, ma contenenti gli stessi dati
  fiscal_epos_print/__manifest__.py
  fiscal_epos_print/migrations/12.0.2.0.0/post-fiscal_epos_disable_reprint.py
  fiscal_epos_print/models/point_of_sale.py
  fiscal_epos_print/readme/CONTRIBUTORS.rst
  fiscal_epos_print/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳
