Repository OCA/l10n-italy, pull requests merged in 2022-07, with the labels that each got.

#2628 [12.O][IMP] add support to dropshipping to l10n_it_delivery_note
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, bot is merging ⏳

#2832 [FIX] Il resoconto dello stato patrimoniale non tiene conto degli anni precedenti
  l10n_it_account_balance_report/__manifest__.py
  l10n_it_account_balance_report/data/account_type.xml
  l10n_it_account_balance_report/migrations/12.0.1.0.5/post-migrate.py
  l10n_it_account_balance_report/report/account_balance_report.py
  l10n_it_account_balance_report/report/account_balance_report_xlsx.py
  l10n_it_account_balance_report/report/templates/account_balance_report.xml
Labels: approved, bot is merging ⏳

#2871 [14.0][FIX] Do not overwrite missing value
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳

#2850 [12.0][FIX] Do not overwrite missing value
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2787 [14.0][IMP] make template data overridable
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/wizard/efattura.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_rc/views/invoice_it_template.xml
  l10n_it_fatturapa_out_rc/wizard/__init__.py
  l10n_it_fatturapa_out_rc/wizard/efattura.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2858 [FIX][l10n_it_fatturapa_in] change from log.erro fo to log.info to av…
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: approved, ready to merge, bot is merging ⏳

#2790 [12.0] l10n_it_reverse_charge supporting "with_supplier_self_invoice" for e-invoices + link supplier self invoice to e-invoice
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in_rc/models/__init__.py
  l10n_it_fatturapa_in_rc/models/attachment.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py
  l10n_it_reverse_charge/models/account_invoice.py
  l10n_it_reverse_charge/models/account_rc_type.py
  l10n_it_reverse_charge/static/description/fiscal_pos_extra.png
  l10n_it_reverse_charge/static/description/rc_selfinvoice_extra.png
  l10n_it_reverse_charge/tests/__init__.py
  l10n_it_reverse_charge/tests/rc_common.py
  l10n_it_reverse_charge/tests/test_account_rc_type.py
  l10n_it_reverse_charge/tests/test_rc.py
  l10n_it_reverse_charge/views/account_rc_type_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2821 [14.0][FIX] l10n_it_ricevute_bancarie: avoid loosing reference to lines partner
  l10n_it_ricevute_bancarie/models/account.py
Labels: approved, bot is merging ⏳

#2873 [14.0][FIX] l10n_it_reverse_charge: porting mistake
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#2112 [12.0] l10n_it_bill_of_entry bolle doganali
  l10n_it_bill_of_entry/__init__.py
  l10n_it_bill_of_entry/__manifest__.py
  l10n_it_bill_of_entry/demo/bill_of_entry_demo.xml
  l10n_it_bill_of_entry/i18n/it.po
  l10n_it_bill_of_entry/models/__init__.py
  l10n_it_bill_of_entry/models/account_invoice.py
  l10n_it_bill_of_entry/models/company.py
  l10n_it_bill_of_entry/readme/CONFIGURE.rst
  l10n_it_bill_of_entry/readme/CONTRIBUTORS.rst
  l10n_it_bill_of_entry/readme/DESCRIPTION.rst
  l10n_it_bill_of_entry/readme/USAGE.rst
  l10n_it_bill_of_entry/tests/__init__.py
  l10n_it_bill_of_entry/tests/test_bill_of_entry.py
  l10n_it_bill_of_entry/views/account_invoice_view.xml
  l10n_it_bill_of_entry/views/company_view.xml
  setup/l10n_it_bill_of_entry/odoo/addons/l10n_it_bill_of_entry
  setup/l10n_it_bill_of_entry/setup.py
Labels: approved, bot is merging ⏳

#2877 [14.0] [IMP] l10n_it_account_stamp: add receipt info in readme
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/readme/CONFIGURE.rst
  l10n_it_account_stamp/readme/DESCRIPTION.rst
  l10n_it_account_stamp/readme/USAGE.rst
  l10n_it_account_stamp/static/description/index.html
Labels: approved, bot is merging ⏳

#2876 Pulsante per validare e inviare le fatture a SdI
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
  l10n_it_fatturapa_sdicoop/tests/__init__.py
  l10n_it_fatturapa_sdicoop/tests/test_account_invoice.py
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/models/__init__.py
  l10n_it_sdi_channel/models/account_invoice.py
  l10n_it_sdi_channel/models/company.py
  l10n_it_sdi_channel/security/security.xml
  l10n_it_sdi_channel/tests/__init__.py
  l10n_it_sdi_channel/tests/test_account_invoice.py
  l10n_it_sdi_channel/views/account_invoice_views.xml
  l10n_it_sdi_channel/views/company_view.xml
Labels: approved, ready to merge, bot is merging ⏳
