Repository OCA/l10n-italy, pull requests merged in 2023-07, with the labels that each got.

#3423 [14.0][FW] [12.0] IMP l10n_it_account_stamp: print legal statement in invoice report
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/views/account_move_report.xml
Labels: bot is merging ⏳

#3348 [14.0][FIX] assets_management view html report
  assets_management/report/asset_journal.py
  assets_management/report/asset_previsional.py
Labels: approved, bot is merging ⏳

#3439 [16.0][FW] [14.0][FW] [12.0] IMP l10n_it_account_stamp: print legal statement in invoice report
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/views/account_move_report.xml
Labels: bot is merging ⏳, needs functional review

#3349 [14.0][FIX] assets_management currency convert function
  assets_management/report/asset_journal.py
  assets_management/report/asset_previsional.py
Labels: approved, bot is merging ⏳

#3298 [14.0] FIX l10n_it_fatturapa_out_rc: complete support for "with_supplier_self_invoice"
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00004.xml
  l10n_it_fatturapa_out_rc/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_rc/views/invoice_it_template.xml
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#3287 [FIX] Pagamenti in sospeso per fatture in inversione contabile
  l10n_it_reverse_charge/README.rst
  l10n_it_reverse_charge/models/account_move.py
  l10n_it_reverse_charge/readme/CONFIGURE.rst
  l10n_it_reverse_charge/readme/CONTRIBUTORS.rst
  l10n_it_reverse_charge/static/description/index.html
  l10n_it_reverse_charge/static/description/registro_riconciliazione.png
  l10n_it_reverse_charge/static/description/registro_riconciliazione_2.png
  l10n_it_reverse_charge/tests/rc_common.py
  l10n_it_reverse_charge/tests/test_rc.py
  l10n_it_reverse_charge/views/account_move_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3443 [FIX] l10n_it_fatturapa_in: rimosso abs dall'importo imponibile
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#3450 [16.0] [FIX] l10n_it_declaration_of_intent: fix creditnote sign
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, needs functional review

#3385 [ADD] ATECO code for condominium
  l10n_it_ateco/data/ateco_data.xml
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#3384 [ADD] ATECO code for condominium
  l10n_it_ateco/data/ateco_data.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3465 [16.0][FIX] l10n_it_fatturapa: fix not valid URI
  l10n_it_fatturapa/models/ir_attachment.py
Labels: bot is merging ⏳

#3464 [14.0][FIX] l10n_it_fatturapa: fix not valid URI
  l10n_it_fatturapa/models/ir_attachment.py
Labels: bot is merging ⏳

#3436 [14.0][FW] [12.0] REF l10n_it_withholding_tax withholding.tax display_name with cleaner implementation
  l10n_it_withholding_tax/models/withholding_tax.py
Labels: approved, bot is merging ⏳

#3316 [FIX][14.0] assets_management depreciable amount computation by date
  assets_management/models/asset_depreciation.py
  assets_management/report/asset_previsional.py
  assets_management/tests/test_assets_management.py
  assets_management/wizard/asset_generate_depreciation.py
Labels: approved, ready to merge, bot is merging ⏳

#3354 [14.0][FIX] l10n_it_withholding_tax_reason migration script
  l10n_it_withholding_tax_reason/migrations/14.0.1.0.0/pre-migration.py
  l10n_it_withholding_tax_reason/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax_reason/readme/INSTALL.rst
Labels: approved, ready to merge, bot is merging ⏳

#3379 [14.0] [IMP] l10n_it_central_journal: update logic to set initial line value
  l10n_it_central_journal/views/report_account_central_journal.xml
Labels: approved, ready to merge, bot is merging ⏳

#3482 [14.0][MIG] l10n_it_pos_fatturapa
  l10n_it_pos_fatturapa/README.rst
  l10n_it_pos_fatturapa/__init__.py
  l10n_it_pos_fatturapa/__manifest__.py
  l10n_it_pos_fatturapa/i18n/it.po
  l10n_it_pos_fatturapa/i18n/l10n_it_pos_fatturapa.pot
  l10n_it_pos_fatturapa/models/__init__.py
  l10n_it_pos_fatturapa/models/res_partner.py
  l10n_it_pos_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_pos_fatturapa/readme/DESCRIPTION.rst
  l10n_it_pos_fatturapa/static/description/icon.png
  l10n_it_pos_fatturapa/static/description/index.html
  l10n_it_pos_fatturapa/static/src/js/ClientDetailsEdit.js
  l10n_it_pos_fatturapa/static/src/js/models.js
  l10n_it_pos_fatturapa/static/src/xml/pos_dump.xml
  l10n_it_pos_fatturapa/views/assets.xml
  setup/l10n_it_pos_fatturapa/odoo/addons/l10n_it_pos_fatturapa
  setup/l10n_it_pos_fatturapa/setup.py
Labels: approved, bot is merging ⏳

#3340 [IMP] fatturapa_in Autofatture per autoconsumo TD27
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/IT02780790107_11009.xml
  l10n_it_fatturapa_in/tests/data/IT02780790107_11010.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, ready to merge, bot is merging ⏳, needs functional review

#3320 [IMP] Nuovo modulo per corretta fatturazione KIT da DDT
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt_mrp_kit/README.rst
  l10n_it_ddt_mrp_kit/__init__.py
  l10n_it_ddt_mrp_kit/__manifest__.py
  l10n_it_ddt_mrp_kit/models/__init__.py
  l10n_it_ddt_mrp_kit/models/stock_picking_package_preparation.py
  l10n_it_ddt_mrp_kit/models/stock_picking_package_preparation_line.py
  l10n_it_ddt_mrp_kit/readme/CONTRIBUTORS.rst
  l10n_it_ddt_mrp_kit/readme/DESCRIPTION.rst
  l10n_it_ddt_mrp_kit/readme/USAGE.rst
  l10n_it_ddt_mrp_kit/static/description/icon.png
  l10n_it_ddt_mrp_kit/static/description/index.html
  l10n_it_ddt_mrp_kit/tests/__init__.py
  l10n_it_ddt_mrp_kit/tests/test_td_invoice_kit.py
  setup/l10n_it_ddt_mrp_kit/odoo/addons/l10n_it_ddt_mrp_kit
  setup/l10n_it_ddt_mrp_kit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3492 [FIX][l10n_it_account_stamp] fix xpath to avoid error on update all E…
  l10n_it_account_stamp/views/account_move_report.xml
Labels: approved, ready to merge, bot is merging ⏳

#3189 [16.0][MIG] l10n_it_sdi_channel
  l10n_it_sdi_channel/README.rst
  l10n_it_sdi_channel/__init__.py
  l10n_it_sdi_channel/__manifest__.py
  l10n_it_sdi_channel/i18n/it.po
  l10n_it_sdi_channel/i18n/l10n_it_sdi_channel.pot
  l10n_it_sdi_channel/models/__init__.py
  l10n_it_sdi_channel/models/company.py
  l10n_it_sdi_channel/models/sdi.py
  l10n_it_sdi_channel/readme/CONFIGURE.rst
  l10n_it_sdi_channel/readme/CONTRIBUTORS.rst
  l10n_it_sdi_channel/readme/DESCRIPTION.rst
  l10n_it_sdi_channel/security/ir.model.access.csv
  l10n_it_sdi_channel/security/security.xml
  l10n_it_sdi_channel/static/description/icon.png
  l10n_it_sdi_channel/static/description/index.html
  l10n_it_sdi_channel/views/company_view.xml
  l10n_it_sdi_channel/views/sdi_view.xml
  setup/l10n_it_sdi_channel/odoo/addons/l10n_it_sdi_channel
  setup/l10n_it_sdi_channel/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3404 [16.0][FIX] l10n_it_withholding_tax: set wt amount residual in invoice payment wizard
  l10n_it_withholding_tax/models/account.py
Labels: approved, bot is merging ⏳
