Repository OCA/l10n-italy, pull requests merged in 2023-06, with the labels that each got.

#3289 [FIX] Dichiarazioni di ritenuta d'acconto duplicate
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#3369 [IMP][14.0]l10n_it_location_nuts: Rimozione test per problema api nuts
  l10n_it_location_nuts/tests/__init__.py
Labels: bot is merging ⏳

#3335 [14.0] fix: remove access to all models, allow selection of reports
  l10n_it_fatturapa/security/ir.model.access.csv
  l10n_it_fatturapa_out/security/ir.model.access.csv
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#3374 14.0 [IMP] l10n_it_delivery_note: aggiunto constraint sul numero DDT
  l10n_it_delivery_note/i18n/it.po
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#3347 [FIX][l10n_it_ricevute_bancarie] fix issue https://github.com/OCA/l10…
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3352 [14.0][IMP] l10n_it_ricevute_bancarie: Issue riba without admin permissions
  l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py
Labels: approved, ready to merge, bot is merging ⏳

#3324 [FIX][l10n_it_declaration_of_intent] fix domain wizard
  l10n_it_declaration_of_intent/wizard/select_declarations.py
Labels: approved, bot is merging ⏳

#3388 16.0 [IMP] l10n_it_delivery_note: aggiunto constraint sul numero DDT
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#3380 [16.0][FIX] - account_vat_period_end_statement - wrong trees proportions
  account_vat_period_end_statement/__manifest__.py
  account_vat_period_end_statement/static/src/css/l10n_it_vat_registries.css
  account_vat_period_end_statement/views/account_view.xml
Labels: approved, bot is merging ⏳

#3341 [14.0][MIG] l10n_it_fiscalcode_sale
  l10n_it_fiscalcode_sale/README.rst
  l10n_it_fiscalcode_sale/__init__.py
  l10n_it_fiscalcode_sale/__manifest__.py
  l10n_it_fiscalcode_sale/i18n/it.po
  l10n_it_fiscalcode_sale/i18n/l10n_it_fiscalcode_sale.pot
  l10n_it_fiscalcode_sale/readme/CONTRIBUTORS.rst
  l10n_it_fiscalcode_sale/readme/DESCRIPTION.rst
  l10n_it_fiscalcode_sale/static/description/icon.png
  l10n_it_fiscalcode_sale/static/description/index.html
  l10n_it_fiscalcode_sale/views/sale_order_report.xml
  setup/l10n_it_fiscalcode_sale/odoo/addons/l10n_it_fiscalcode_sale
  setup/l10n_it_fiscalcode_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3365 [FIX] Esportare solo il numero di telefono dedicato alla fattura elettronica
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: bot is merging ⏳

#3377 [16.0][FIX] l10n_it_fatturapa_out: fix su _validate_max_invoice_in_xml con record multipli
  l10n_it_fatturapa_out/models/partner.py
Labels: bot is merging ⏳
