Repository OCA/l10n-italy, pull requests merged in 2023-05, with the labels that each got.

#2934 [FIX] I follower delle Fatture Elettroniche hanno sottotipi diversi dal canale SdI
  l10n_it_fatturapa_sdicoop/tests/test_notification.py
  l10n_it_sdi_channel/models/fatturapa_attachment.py
Labels: approved, bot is merging ⏳

#3074 [12.0] [FIX] Importazione fatture elettroniche per utente Fatturazione
  l10n_it_fatturapa_in/security/ir.model.access.csv
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: bot is merging ⏳

#3071 [FIX] Ritenute: Nota di credito non mantiene la ritenuta e genera movimenti
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, bot is merging ⏳

#3206 [IMP] Spostamento codice per migliorare disaccoppiamento
  l10n_it_fatturapa_out/models/attachment.py
  l10n_it_fatturapa_out/views/attachment_view.xml
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
  l10n_it_sdi_channel/views/fatturapa_attachment_views.xml
Labels: approved, bot is merging ⏳

#3066 [FIX] Esportazione autofatture per diversi fornitori
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out_rc/tests/test_e_invoice_out_rc.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py
Labels: approved, bot is merging ⏳

#3294 [16.0][REF] l10n_it_fatturapa_out: Invoice used in tests is open when validated
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: bot is merging ⏳

#2979 [MIG] l10n_it_corrispettivi_fatturapa_out
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/migrations/14.0.3.3.0/pre-migration.py
  l10n_it_fatturapa_out/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3312 [FIX][l10n_it_declaration_of_intent] fix issue https://github.com/OCA…
  l10n_it_declaration_of_intent/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#2572 [14.0][FIX] l10n_it_withholding_tax: set wt amount residual in invoice payment wizard
  l10n_it_withholding_tax/models/account.py
Labels: approved, bot is merging ⏳

#3303 [14.0][IMP]l10n_it_delivery_note: set partner as commercial partner
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
Labels: approved, ready to merge, bot is merging ⏳

#2853 [12.0] FIX l10n_it_fatturapa_out_rc - AttributeError: 'DatiPagamentoType' object has no attribute 'ImportoPagamento'
  l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py
Labels: approved, bot is merging ⏳

#2907 [14.0][IMP] l10n_it_fatturapa_in: fattura semplificata
  .pre-commit-config.yaml
  l10n_it_account/tools/account_tools.py
  l10n_it_account/tools/xsd/Schema_VFSM10.xsd
  l10n_it_fatturapa/data/fatturasemplificata_v1.0.xsl
  l10n_it_fatturapa/models/company.py
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa/views/company_view.xml
  l10n_it_fatturapa_in/tests/data/IT02780790107_11009.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/efattura.py
  l10n_it_fatturapa_out/views/company_view.xml
Labels: approved, ready to merge, bot is merging ⏳, needs functional review

#3322 [14.0][FIX] l10n_it_withholding_tax, fix precision digits
  l10n_it_withholding_tax/models/account.py
Labels: approved, bot is merging ⏳

#3317 [14.0][FIX] - l10n_fatturapa_out: Users without access to 'settings' …
  l10n_it_fatturapa_out/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#3339 [16.0] [FIX] l10n_it_website_portal_ipa: fix method signature
  l10n_it_website_portal_ipa/controllers/main.py
Labels: bot is merging ⏳
