Repository OCA/l10n-italy, pull requests merged in 2023-04, with the labels that each got.

#3264 [16.0] l10n_it_fatturapa: fix preview style unwanted reset
  l10n_it_fatturapa/models/company.py
Labels: approved, bot is merging ⏳

#3262 [14.0] l10n_it_fatturapa: fix preview style unwanted reset
  l10n_it_fatturapa/models/company.py
Labels: approved, bot is merging ⏳

#2981 [14.0][FIX] l10n it intrastat statement: weight can be 0
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/views/account.xml
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section1.py
Labels: approved, ready to merge, bot is merging ⏳

#3261 14.0 mgr l10n it asset history import
  l10n_it_asset_history_import/README.rst
  l10n_it_asset_history_import/__init__.py
  l10n_it_asset_history_import/__manifest__.py
  l10n_it_asset_history_import/i18n/it.po
  l10n_it_asset_history_import/models/__init__.py
  l10n_it_asset_history_import/models/asset.py
  l10n_it_asset_history_import/models/asset_category.py
  l10n_it_asset_history_import/models/asset_depreciation_line.py
  l10n_it_asset_history_import/models/asset_depreciation_mode.py
  l10n_it_asset_history_import/models/asset_depreciation_type.py
  l10n_it_asset_history_import/readme/DESCRIPTION.rst
  l10n_it_asset_history_import/readme/USAGE.rst
  l10n_it_asset_history_import/security/ir.model.access.csv
  l10n_it_asset_history_import/static/asset_import.png
  l10n_it_asset_history_import/static/description/icon.png
  l10n_it_asset_history_import/static/description/index.html
  l10n_it_asset_history_import/views/asset.xml
  l10n_it_asset_history_import/views/asset_category.xml
  l10n_it_asset_history_import/views/asset_depreciation_mode.xml
  l10n_it_asset_history_import/views/asset_depreciation_type.xml
  l10n_it_asset_history_import/wizards/__init__.py
  l10n_it_asset_history_import/wizards/asset_history_import.py
  l10n_it_asset_history_import/wizards/asset_history_import.xml
  requirements.txt
  setup/l10n_it_asset_history_import/odoo/addons/l10n_it_asset_history_import
  setup/l10n_it_asset_history_import/setup.py
Labels: approved, bot is merging ⏳

#3249 [FIX] l10_it_fatturapa_out: In generazione xml nota credito, l'import…
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2737 [14.0][l10n_it_pos_fiscalcode] Fix fiscal code usage on POS
  l10n_it_pos_fiscalcode/readme/CONTRIBUTORS.rst
  l10n_it_pos_fiscalcode/static/description/index.html
  l10n_it_pos_fiscalcode/static/src/js/models.js
  l10n_it_pos_fiscalcode/static/src/js/screens.js
  l10n_it_pos_fiscalcode/static/src/xml/pos.xml
  l10n_it_pos_fiscalcode/views/assets.xml
Labels: bot is merging ⏳

#2951 [IMP] Ricevute bancarie "Al dopo incasso"
  l10n_it_ricevute_bancarie/readme/CONFIGURE.rst
  l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
  l10n_it_ricevute_bancarie/tests/riba_common.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/configuration_view.xml
  l10n_it_ricevute_bancarie/views/riba_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3253 [16.0][FIX] l10n_it_fatturapa_out: report function signature
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#3230 [14.0][ADD] l10n_it_riba_sale_commission
  l10n_it_riba_sale_commission/README.rst
  l10n_it_riba_sale_commission/__init__.py
  l10n_it_riba_sale_commission/__manifest__.py
  l10n_it_riba_sale_commission/i18n/it.po
  l10n_it_riba_sale_commission/models/__init__.py
  l10n_it_riba_sale_commission/models/account_move.py
  l10n_it_riba_sale_commission/models/riba_config.py
  l10n_it_riba_sale_commission/readme/CONTRIBUTORS.rst
  l10n_it_riba_sale_commission/readme/DESCRIPTION.rst
  l10n_it_riba_sale_commission/static/description/icon.png
  l10n_it_riba_sale_commission/static/description/index.html
  l10n_it_riba_sale_commission/views/configuration_riba_view.xml
  l10n_it_riba_sale_commission/views/invoice_no_commission.xml
  l10n_it_riba_sale_commission/wizard/__init__.py
  l10n_it_riba_sale_commission/wizard/wizard_riba_commissions_settle.py
  setup/l10n_it_riba_sale_commission/odoo/addons/l10n_it_riba_sale_commission
  setup/l10n_it_riba_sale_commission/setup.py
Labels: approved, bot is merging ⏳

#3296 [14.0][IMP] Remove oca_dependencies.txt as useless in repo with GitHub Actions as CI
  oca_dependencies.txt
Labels: bot is merging ⏳
