Repository OCA/l10n-italy, pull requests merged in 2023-09, with the labels that each got.

#3064 [ADD] l10n_it_account_balance_eu
  l10n_it_account_balance_eu/README.rst
  l10n_it_account_balance_eu/__init__.py
  l10n_it_account_balance_eu/__manifest__.py
  l10n_it_account_balance_eu/data/account.balance.eu.csv
  l10n_it_account_balance_eu/data/account_balance_eu_reclassification.xml
  l10n_it_account_balance_eu/i18n/it.po
  l10n_it_account_balance_eu/i18n/l10n_it_account_balance_eu.pot
  l10n_it_account_balance_eu/models/__init__.py
  l10n_it_account_balance_eu/models/account_balance_eu.py
  l10n_it_account_balance_eu/readme/CONFIGURE.rst
  l10n_it_account_balance_eu/readme/CONTRIBUTORS.rst
  l10n_it_account_balance_eu/readme/DESCRIPTION.rst
  l10n_it_account_balance_eu/readme/ROADMAP.rst
  l10n_it_account_balance_eu/readme/USAGE.rst
  l10n_it_account_balance_eu/report/__init__.py
  l10n_it_account_balance_eu/report/account_balance_eu_report.py
  l10n_it_account_balance_eu/report/account_balance_eu_report.xml
  l10n_it_account_balance_eu/report/templates/layouts.xml
  l10n_it_account_balance_eu/security/account_balance_eu.xml
  l10n_it_account_balance_eu/static/description/icon.png
  l10n_it_account_balance_eu/static/description/index.html
  l10n_it_account_balance_eu/static/src/css/report.css
  l10n_it_account_balance_eu/static/src/js/action_manager_report.js
  l10n_it_account_balance_eu/static/src/js/client_action.js
  l10n_it_account_balance_eu/static/src/xml/report.xml
  l10n_it_account_balance_eu/tests/__init__.py
  l10n_it_account_balance_eu/tests/test_balance_eu.py
  l10n_it_account_balance_eu/views/account_balance_eu_view.xml
  l10n_it_account_balance_eu/views/report_template.xml
  l10n_it_account_balance_eu/wizards/__init__.py
  l10n_it_account_balance_eu/wizards/account_balance_eu_wizard.py
  l10n_it_account_balance_eu/wizards/account_balance_eu_wizard.xml
  setup/l10n_it_account_balance_eu/odoo/addons/l10n_it_account_balance_eu
  setup/l10n_it_account_balance_eu/setup.py
Labels: bot is merging ⏳, needs functional review

#3558 [16.0][IMP] l10n_it_delivery_note: remove misleading price_unit sum total
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳

#3493 [14.0][IMP]l10n_it_delivery_note_customer_code: Product_customer_name nel modello e report
  l10n_it_delivery_note_customer_code/__manifest__.py
  l10n_it_delivery_note_customer_code/models/delivery_note_line.py
  l10n_it_delivery_note_customer_code/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note_customer_code/readme/DESCRIPTION.rst
  l10n_it_delivery_note_customer_code/report/report_delivery_note.xml
Labels: approved, bot is merging ⏳

#3557 [14.0][IMP] l10n_it_delivery_note: remove misleading price_unit sum total
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳

#3550 [16.0] [UPD] l10n_it_delivery_note: aggiornato maintainers
  l10n_it_delivery_note/__manifest__.py
Labels: bot is merging ⏳

#3190 [16.0][MIG] l10n_it_fatturapa_pec
  l10n_it_fatturapa_pec/README.rst
  l10n_it_fatturapa_pec/__init__.py
  l10n_it_fatturapa_pec/__manifest__.py
  l10n_it_fatturapa_pec/data/config_parameter.xml
  l10n_it_fatturapa_pec/data/fetchmail_data.xml
  l10n_it_fatturapa_pec/data/sdi_channel_demo.xml
  l10n_it_fatturapa_pec/i18n/it.po
  l10n_it_fatturapa_pec/i18n/l10n_it_fatturapa_pec.pot
  l10n_it_fatturapa_pec/models/__init__.py
  l10n_it_fatturapa_pec/models/company.py
  l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
  l10n_it_fatturapa_pec/models/fetchmail.py
  l10n_it_fatturapa_pec/models/ir_mail_server.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/models/sdi.py
  l10n_it_fatturapa_pec/readme/CONFIGURE.rst
  l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_pec/readme/DESCRIPTION.rst
  l10n_it_fatturapa_pec/readme/USAGE.rst
  l10n_it_fatturapa_pec/security/groups.xml
  l10n_it_fatturapa_pec/security/ir.model.access.csv
  l10n_it_fatturapa_pec/static/description/icon.png
  l10n_it_fatturapa_pec/static/description/index.html
  l10n_it_fatturapa_pec/tests/__init__.py
  l10n_it_fatturapa_pec/tests/data/ACCETTAZIONE_ IT03339130126_00009.xml.txt
  l10n_it_fatturapa_pec/tests/data/CONSEGNA_ IT03339130126_00009.xml.txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Invio File 7339338 (broken XML).txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Invio File 7339338.txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Ricevuta di consegna 6782414.txt
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_mancata_consegna.txt
  l10n_it_fatturapa_pec/tests/e_invoice_common.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
  l10n_it_fatturapa_pec/views/company_view.xml
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
  l10n_it_fatturapa_pec/views/fetchmail_view.xml
  l10n_it_fatturapa_pec/views/ir_mail_server.xml
  l10n_it_fatturapa_pec/views/sdi_view.xml
  l10n_it_fatturapa_pec/wizard/__init__.py
  l10n_it_fatturapa_pec/wizard/send_pec.py
  l10n_it_fatturapa_pec/wizard/send_pec_view.xml
  requirements.txt
  setup/l10n_it_fatturapa_pec/odoo/addons/l10n_it_fatturapa_pec
  setup/l10n_it_fatturapa_pec/setup.py
Labels: approved, bot is merging ⏳, needs functional review

#3179 [16.0][MIG] l10n_it_fatturapa_out_stamp
  l10n_it_fatturapa_out_stamp/README.rst
  l10n_it_fatturapa_out_stamp/__init__.py
  l10n_it_fatturapa_out_stamp/__manifest__.py
  l10n_it_fatturapa_out_stamp/i18n/it.po
  l10n_it_fatturapa_out_stamp/i18n/l10n_it_fatturapa_out_stamp.pot
  l10n_it_fatturapa_out_stamp/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_stamp/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_stamp/static/description/icon.png
  l10n_it_fatturapa_out_stamp/static/description/index.html
  l10n_it_fatturapa_out_stamp/views/account_invoice_it_dati_bollo.xml
  setup/l10n_it_fatturapa_out_stamp/odoo/addons/l10n_it_fatturapa_out_stamp
  setup/l10n_it_fatturapa_out_stamp/setup.py
Labels: bot is merging ⏳

#3002 [16.0][MIG] l10n_it_central_journal_reportlab
  l10n_it_central_journal_reportlab/README.rst
  l10n_it_central_journal_reportlab/__init__.py
  l10n_it_central_journal_reportlab/__manifest__.py
  l10n_it_central_journal_reportlab/i18n/it.po
  l10n_it_central_journal_reportlab/i18n/l10n_it_central_journal_reportlab.pot
  l10n_it_central_journal_reportlab/models/__init__.py
  l10n_it_central_journal_reportlab/models/account.py
  l10n_it_central_journal_reportlab/readme/CONTRIBUTORS.rst
  l10n_it_central_journal_reportlab/readme/DESCRIPTION.rst
  l10n_it_central_journal_reportlab/security/ir.model.access.csv
  l10n_it_central_journal_reportlab/static/description/icon.png
  l10n_it_central_journal_reportlab/static/description/index.html
  l10n_it_central_journal_reportlab/tests/__init__.py
  l10n_it_central_journal_reportlab/tests/test_central_journal_reportlab.py
  l10n_it_central_journal_reportlab/views/date_range_view.xml
  l10n_it_central_journal_reportlab/wizard/__init__.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.xml
  setup/l10n_it_central_journal_reportlab/odoo/addons/l10n_it_central_journal_reportlab
  setup/l10n_it_central_journal_reportlab/setup.py
Labels: approved, bot is merging ⏳, needs functional review

#3077 [16.0][MIG] l10n_it_fatturapa_sale
  l10n_it_fatturapa_sale/README.rst
  l10n_it_fatturapa_sale/__init__.py
  l10n_it_fatturapa_sale/__manifest__.py
  l10n_it_fatturapa_sale/i18n/it.po
  l10n_it_fatturapa_sale/i18n/l10n_it_fatturapa_sale.pot
  l10n_it_fatturapa_sale/models/__init__.py
  l10n_it_fatturapa_sale/models/account_move.py
  l10n_it_fatturapa_sale/models/account_move_line.py
  l10n_it_fatturapa_sale/models/related_document.py
  l10n_it_fatturapa_sale/models/sale_order.py
  l10n_it_fatturapa_sale/models/sale_order_line.py
  l10n_it_fatturapa_sale/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_sale/readme/DESCRIPTION.rst
  l10n_it_fatturapa_sale/static/description/icon.png
  l10n_it_fatturapa_sale/static/description/index.html
  l10n_it_fatturapa_sale/tests/__init__.py
  l10n_it_fatturapa_sale/tests/test_fatturapa_sale.py
  l10n_it_fatturapa_sale/views/related_document_type_views.xml
  l10n_it_fatturapa_sale/views/sale_order_line_views.xml
  l10n_it_fatturapa_sale/views/sale_order_views.xml
  setup/l10n_it_fatturapa_sale/odoo/addons/l10n_it_fatturapa_sale
  setup/l10n_it_fatturapa_sale/setup.py
Labels: bot is merging ⏳

#3022 [16.0] [MIG] l10n_it_delivery_note_order_link
  l10n_it_delivery_note_order_link/README.rst
  l10n_it_delivery_note_order_link/__init__.py
  l10n_it_delivery_note_order_link/__manifest__.py
  l10n_it_delivery_note_order_link/i18n/it.po
  l10n_it_delivery_note_order_link/i18n/l10n_it_delivery_note_order_link.pot
  l10n_it_delivery_note_order_link/models/__init__.py
  l10n_it_delivery_note_order_link/models/purchase_order.py
  l10n_it_delivery_note_order_link/models/sale_order.py
  l10n_it_delivery_note_order_link/models/stock_delivery_note.py
  l10n_it_delivery_note_order_link/readme/CONFIGURE.rst
  l10n_it_delivery_note_order_link/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note_order_link/readme/DESCRIPTION.rst
  l10n_it_delivery_note_order_link/readme/USAGE.rst
  l10n_it_delivery_note_order_link/static/description/icon.png
  l10n_it_delivery_note_order_link/static/description/index.html
  l10n_it_delivery_note_order_link/views/purchase_order.xml
  l10n_it_delivery_note_order_link/views/sale_order.xml
  setup/l10n_it_delivery_note_order_link/odoo/addons/l10n_it_delivery_note_order_link
  setup/l10n_it_delivery_note_order_link/setup.py
Labels: bot is merging ⏳

#3332 [16.0] [MIG] l10n_it_fatturapa_export_zip
  l10n_it_fatturapa_export_zip/README.rst
  l10n_it_fatturapa_export_zip/__init__.py
  l10n_it_fatturapa_export_zip/__manifest__.py
  l10n_it_fatturapa_export_zip/i18n/it.po
  l10n_it_fatturapa_export_zip/i18n/l10n_it_fatturapa_export_zip.pot
  l10n_it_fatturapa_export_zip/models/__init__.py
  l10n_it_fatturapa_export_zip/models/attachment.py
  l10n_it_fatturapa_export_zip/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_export_zip/readme/DESCRIPTION.rst
  l10n_it_fatturapa_export_zip/security/ir.model.access.csv
  l10n_it_fatturapa_export_zip/static/description/icon.png
  l10n_it_fatturapa_export_zip/static/description/index.html
  l10n_it_fatturapa_export_zip/views/attachment_view.xml
  l10n_it_fatturapa_export_zip/wizard/__init__.py
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
  l10n_it_fatturapa_export_zip/wizard/export_fatturapa_view.xml
  setup/l10n_it_fatturapa_export_zip/odoo/addons/l10n_it_fatturapa_export_zip
  setup/l10n_it_fatturapa_export_zip/setup.py
Labels: bot is merging ⏳, needs functional review

#3333 [16.0] [MIG] l10n_it_fatturapa_in_purchase
  l10n_it_fatturapa_in_purchase/README.rst
  l10n_it_fatturapa_in_purchase/__init__.py
  l10n_it_fatturapa_in_purchase/__manifest__.py
  l10n_it_fatturapa_in_purchase/i18n/it.po
  l10n_it_fatturapa_in_purchase/i18n/l10n_it_fatturapa_in_purchase.pot
  l10n_it_fatturapa_in_purchase/models/__init__.py
  l10n_it_fatturapa_in_purchase/models/purchase_order.py
  l10n_it_fatturapa_in_purchase/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in_purchase/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in_purchase/readme/USAGE.rst
  l10n_it_fatturapa_in_purchase/static/description/icon.png
  l10n_it_fatturapa_in_purchase/static/description/index.html
  l10n_it_fatturapa_in_purchase/tests/__init__.py
  l10n_it_fatturapa_in_purchase/tests/data/IT05979361218_008.xml
  l10n_it_fatturapa_in_purchase/tests/test_l10n_it_fatturapa_in_purchase.py
  l10n_it_fatturapa_in_purchase/views/invoice_view.xml
  setup/l10n_it_fatturapa_in_purchase/odoo/addons/l10n_it_fatturapa_in_purchase
  setup/l10n_it_fatturapa_in_purchase/setup.py
Labels: bot is merging ⏳, needs functional review

#3214 [MIG] l10n_it_website_sale_fiscalcode: Migration to 14.0
  l10n_it_website_sale_fiscalcode/README.rst
  l10n_it_website_sale_fiscalcode/__init__.py
  l10n_it_website_sale_fiscalcode/__manifest__.py
  l10n_it_website_sale_fiscalcode/controllers/__init__.py
  l10n_it_website_sale_fiscalcode/controllers/main.py
  l10n_it_website_sale_fiscalcode/i18n/de.po
  l10n_it_website_sale_fiscalcode/i18n/es.po
  l10n_it_website_sale_fiscalcode/i18n/it.po
  l10n_it_website_sale_fiscalcode/i18n/l10n_it_website_sale_fiscalcode.pot
  l10n_it_website_sale_fiscalcode/i18n/sl.po
  l10n_it_website_sale_fiscalcode/readme/CONTRIBUTORS.rst
  l10n_it_website_sale_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_website_sale_fiscalcode/readme/USAGE.rst
  l10n_it_website_sale_fiscalcode/static/description/icon.png
  l10n_it_website_sale_fiscalcode/static/description/index.html
  l10n_it_website_sale_fiscalcode/views/templates.xml
  setup/l10n_it_website_sale_fiscalcode/odoo/addons/l10n_it_website_sale_fiscalcode
  setup/l10n_it_website_sale_fiscalcode/setup.py
Labels: approved, bot is merging ⏳

#3137 [16.0] [MIG] l10n_it_vat_statement_communication
  l10n_it_vat_statement_communication/README.rst
  l10n_it_vat_statement_communication/__init__.py
  l10n_it_vat_statement_communication/__manifest__.py
  l10n_it_vat_statement_communication/data/comunicazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornituraIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/fornitura_v3.xsd
  l10n_it_vat_statement_communication/data/intestazioneIvp_2017_v1.xsd
  l10n_it_vat_statement_communication/data/typesDati_v3.xsd
  l10n_it_vat_statement_communication/data/typesProvincie_v3.xsd
  l10n_it_vat_statement_communication/i18n/it.po
  l10n_it_vat_statement_communication/i18n/l10n_it_vat_statement_communication.pot
  l10n_it_vat_statement_communication/models/__init__.py
  l10n_it_vat_statement_communication/models/account.py
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
  l10n_it_vat_statement_communication/models/config.py
  l10n_it_vat_statement_communication/readme/CONFIGURE.rst
  l10n_it_vat_statement_communication/readme/CONTRIBUTORS.rst
  l10n_it_vat_statement_communication/readme/DESCRIPTION.rst
  l10n_it_vat_statement_communication/readme/USAGE.rst
  l10n_it_vat_statement_communication/security/ir.model.access.csv
  l10n_it_vat_statement_communication/security/security.xml
  l10n_it_vat_statement_communication/static/description/icon.png
  l10n_it_vat_statement_communication/static/description/index.html
  l10n_it_vat_statement_communication/tests/__init__.py
  l10n_it_vat_statement_communication/tests/test_vat_statement_communication.py
  l10n_it_vat_statement_communication/views/account.xml
  l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
  l10n_it_vat_statement_communication/views/config.xml
  l10n_it_vat_statement_communication/wizard/__init__.py
  l10n_it_vat_statement_communication/wizard/export_file.py
  l10n_it_vat_statement_communication/wizard/export_file_view.xml
  setup/l10n_it_vat_statement_communication/odoo/addons/l10n_it_vat_statement_communication
  setup/l10n_it_vat_statement_communication/setup.py
Labels: bot is merging ⏳, needs functional review

#3571 [MIG] l10n_it_fatturapa_out_rc
  l10n_it_fatturapa_out_rc/README.rst
  l10n_it_fatturapa_out_rc/__init__.py
  l10n_it_fatturapa_out_rc/__manifest__.py
  l10n_it_fatturapa_out_rc/i18n/it.po
  l10n_it_fatturapa_out_rc/i18n/l10n_it_fatturapa_out_rc.pot
  l10n_it_fatturapa_out_rc/models/__init__.py
  l10n_it_fatturapa_out_rc/models/account_move.py
  l10n_it_fatturapa_out_rc/models/rc_type.py
  l10n_it_fatturapa_out_rc/readme/CONFIGURE.rst
  l10n_it_fatturapa_out_rc/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_rc/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_rc/static/description/icon.png
  l10n_it_fatturapa_out_rc/static/description/index.html
  l10n_it_fatturapa_out_rc/tests/__init__.py
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00002.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00003.xml
  l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00004.xml
  l10n_it_fatturapa_out_rc/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_rc/views/invoice_it_template.xml
  l10n_it_fatturapa_out_rc/views/rc_type_views.xml
  l10n_it_fatturapa_out_rc/wizard/__init__.py
  l10n_it_fatturapa_out_rc/wizard/wizard_export_fatturapa.py
  setup/l10n_it_fatturapa_out_rc/odoo/addons/l10n_it_fatturapa_out_rc
  setup/l10n_it_fatturapa_out_rc/setup.py
Labels: approved, bot is merging ⏳

#3497 [FIX][l10n_it_account_stamp] fix xpath to avoid error on update all E…
  l10n_it_account_stamp/views/account_move_report.xml
Labels: bot is merging ⏳

#3362 [14.0][FIX] l10n_it_fatturapa migration script
  l10n_it_fatturapa/migrations/13.0.1.0.0/post-migrate.py
  l10n_it_fatturapa/migrations/13.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳

#3363 [14.0][FIX] l10n_it_fatturapa_in migration scripts
  l10n_it_fatturapa_in/migrations/12.0.1.18.3/pre-migration.py
  l10n_it_fatturapa_in/migrations/13.0.1.0.0/post-migration.py
  l10n_it_fatturapa_in/migrations/13.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#3485 [14.0][FIX] l10n_it_delivery_note script pre-migrate migration
  l10n_it_delivery_note/migrations/13.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳

#3486 [14.0][FIX] l10n_it_withholding_tax pre-migration script
  l10n_it_withholding_tax/migrations/13.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#3487 [14.0][FIX] l10n_it_invoices_data_communication post-migrate rinominato in pre-migrate migration
  l10n_it_invoices_data_communication/migrations/13.0.1.0.0/post-migrate.py
  l10n_it_invoices_data_communication/migrations/13.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳

#3496 [14.0][FIX] move update of fatturapa_attachment_out_id in pre-migration script
  l10n_it_fatturapa_out/migrations/13.0.1.0.0/post-migration.py
  l10n_it_fatturapa_out/migrations/13.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#3577 [16.0] IMP l10n_it_reverse_charge supporting with_supplier_self_invoice for e-invoices
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/views/account_view.xml
Labels: bot is merging ⏳

#3411 [14.0][IMP]l10n_it_ricevute_bancarie:Wizard per filtrare riba in base all'ammontare massimo
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/readme/USAGE.rst
  l10n_it_ricevute_bancarie/security/ir.model.access.csv
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/account_view.xml
  l10n_it_ricevute_bancarie/views/wizard_presentation.xml
  l10n_it_ricevute_bancarie/wizard/__init__.py
  l10n_it_ricevute_bancarie/wizard/wizard_presentation_riba.py
Labels: approved, ready to merge, bot is merging ⏳

#3239 [14.0][IMP] assets_management: add ability to dismiss directly an asset
  assets_management/models/asset.py
  assets_management/models/asset_depreciation.py
  assets_management/report/asset_journal.py
  assets_management/report/asset_previsional.py
  assets_management/report/templates/asset_journal.xml
  assets_management/report/templates/asset_previsional.xml
  assets_management/views/asset.xml
  assets_management/wizard/account_move_manage_asset.py
  assets_management/wizard/account_move_manage_asset_view.xml
  assets_management/wizard/asset_journal_report.py
  assets_management/wizard/asset_journal_report_view.xml
  assets_management/wizard/asset_previsional_report.py
  assets_management/wizard/asset_previsional_report_view.xml
Labels: approved, bot is merging ⏳

#3281 [FIX] assets_management: correct permission management
  assets_management/__manifest__.py
  assets_management/security/ir.model.access.csv
  assets_management/views/asset_menuitems.xml
Labels: approved, ready to merge, bot is merging ⏳

#3567 [16.0][mig]l10n_it_fiscalcode_sale
  l10n_it_fiscalcode_sale/README.rst
  l10n_it_fiscalcode_sale/__init__.py
  l10n_it_fiscalcode_sale/__manifest__.py
  l10n_it_fiscalcode_sale/i18n/it.po
  l10n_it_fiscalcode_sale/i18n/l10n_it_fiscalcode_sale.pot
  l10n_it_fiscalcode_sale/readme/CONTRIBUTORS.rst
  l10n_it_fiscalcode_sale/readme/DESCRIPTION.rst
  l10n_it_fiscalcode_sale/static/description/icon.png
  l10n_it_fiscalcode_sale/static/description/index.html
  l10n_it_fiscalcode_sale/views/sale_order_report.xml
  setup/l10n_it_fiscalcode_sale/odoo/addons/l10n_it_fiscalcode_sale
  setup/l10n_it_fiscalcode_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3603 [16.0][FIX] l10n_it_declaration_of_intent: check declarations on invoices only
  l10n_it_declaration_of_intent/models/account_move.py
Labels: approved, bot is merging ⏳

#3605 [14.0][FIX] l10n_it_declaration_of_intent: check declarations on invoices only
  l10n_it_declaration_of_intent/models/account_move.py
Labels: approved, bot is merging ⏳

#3475 [14.0] l10n_it_fatturapa_in: forward port of #2788
  .pre-commit-config.yaml
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/ZGEXQROO37831_anonimizzata.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: approved, ready to merge, bot is merging ⏳

#3611 [IMP] l10n_it_delivery_note: add hook to prepare vals needed to create DN
  l10n_it_delivery_note/wizard/delivery_note_create.py
Labels: bot is merging ⏳

#3543 [IMP][14.0] l10n_it_intrastat: add some missing instrastat codes
  l10n_it_intrastat/data/report.intrastat.code.csv
Labels: approved, ready to merge, bot is merging ⏳
