Repository OCA/l10n-italy, pull requests merged in 2023-01, with the labels that each got.

#3114 [FIX] Nei test, c'è un conflitto di sequenze fattura
  l10n_it_fatturapa_out_welfare/tests/test_fatturapa_out_welfare.py
Labels: bot is merging ⏳

#3056 [12.0][BACK] l10n_it_delivery_note invoice from ddt
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/models/sale_order.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/wizard/__init__.py
  l10n_it_delivery_note/wizard/delivery_note_invoice.py
  l10n_it_delivery_note/wizard/delivery_note_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#3111 [16.0][FIX] l10n_it_fatturapa_out: piva in tests
  l10n_it_fatturapa_out/tests/fatturapa_common.py
Labels: bot is merging ⏳

#3126 [16.0] [FIX] l10n_it_fatturapa_out: TypeError: format requires a mapping
  l10n_it_fatturapa_out/models/account.py
Labels: bot is merging ⏳

#3105 [12.0] [FIX] l10n_it_account_stamp_sale: change module dependency
  l10n_it_account_stamp_sale/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#3128 [14.0][FIX] l10n_it_intrastat: migration leftover
  l10n_it_intrastat/models/account.py
Labels: bot is merging ⏳

#2346 [14.0][FIX] l10n_it_delivery_note: fix create invoice from delivery note
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/models/sale_order.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/security/ir.model.access.csv
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/wizard/__init__.py
  l10n_it_delivery_note/wizard/delivery_note_invoice.py
  l10n_it_delivery_note/wizard/delivery_note_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#3106 [12.0] [FIX] l10n_it_fiscalcode_sale: change module dependency
  l10n_it_fiscalcode_sale/__manifest__.py
Labels: approved, bot is merging ⏳

#3143 [14.0][FIX] l10n_it_fatturapa_sale, sales team access
  l10n_it_fatturapa_sale/__manifest__.py
  l10n_it_fatturapa_sale/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#3134 [IMP] Impostare una nota predefinita per il DdT nel tipo DdT
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/tests/test_ddt.py
  l10n_it_ddt/views/stock_picking_package_preparation.xml
  l10n_it_ddt/wizard/ddt_from_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#3057 [FIX][l10n_it_declaration_of_intent] fix creditnote sign
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳
