Repository OCA/l10n-italy, pull requests merged in 2023-10, with the labels that each got.

#3622 [16.0][IMP][l10n_it_intrastat] add some missing intrastat codes
  l10n_it_intrastat/data/report.intrastat.code.csv
Labels: bot is merging ⏳

#3593 [IMP][14.0] l10n_it_delivery_note_rma: Rma requests from ddt portal page
  l10n_it_delivery_note_rma/__init__.py
  l10n_it_delivery_note_rma/__manifest__.py
  l10n_it_delivery_note_rma/controllers/__init__.py
  l10n_it_delivery_note_rma/controllers/delivery_note_portal.py
  l10n_it_delivery_note_rma/controllers/rma_portal.py
  l10n_it_delivery_note_rma/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note_rma/static/src/js/rma_portal_form.js
  l10n_it_delivery_note_rma/tests/__init__.py
  l10n_it_delivery_note_rma/tests/test_delivery_note_rma_portal.py
  l10n_it_delivery_note_rma/views/assets.xml
  l10n_it_delivery_note_rma/views/delivery_portal_template.xml
  l10n_it_delivery_note_rma/wizard/stock_delivery_note_rma_wizard.py
Labels: approved, bot is merging ⏳

#3266 [16.0][FIX] - l10n_fatturapa_out | It possible to force-enable the ex…
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#3630 [REF] I test non devono essere importati
  l10n_it_bill_of_entry/__init__.py
Labels: bot is merging ⏳

#3534 [FIX] Nelle fatture con ritenuta, resettare l'importo da pagare al netto da pagare residuo
  l10n_it_withholding_tax/__init__.py
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/readme/ROADMAP.rst
  l10n_it_withholding_tax/tests/test_withholding_tax.py
  l10n_it_withholding_tax/wizards/__init__.py
  l10n_it_withholding_tax/wizards/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳

#3584 [MIG] l10n_it_fatturapa_import_zip
  l10n_it_fatturapa_import_zip/README.rst
  l10n_it_fatturapa_import_zip/__init__.py
  l10n_it_fatturapa_import_zip/__manifest__.py
  l10n_it_fatturapa_import_zip/i18n/it.po
  l10n_it_fatturapa_import_zip/models/__init__.py
  l10n_it_fatturapa_import_zip/models/account_invoice.py
  l10n_it_fatturapa_import_zip/models/attachment.py
  l10n_it_fatturapa_import_zip/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_import_zip/readme/DESCRIPTION.rst
  l10n_it_fatturapa_import_zip/readme/USAGE.rst
  l10n_it_fatturapa_import_zip/security/ir.model.access.csv
  l10n_it_fatturapa_import_zip/security/rules.xml
  l10n_it_fatturapa_import_zip/static/description/index.html
  l10n_it_fatturapa_import_zip/tests/__init__.py
  l10n_it_fatturapa_import_zip/tests/data/xml_import.zip
  l10n_it_fatturapa_import_zip/tests/test_import_zip.py
  l10n_it_fatturapa_import_zip/views/account_invoice_views.xml
  l10n_it_fatturapa_import_zip/views/attachment_views.xml
  l10n_it_fatturapa_import_zip/wizards/__init__.py
  l10n_it_fatturapa_import_zip/wizards/wizard_import_fatturapa.py
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  setup/l10n_it_fatturapa_import_zip/odoo/addons/l10n_it_fatturapa_import_zip
  setup/l10n_it_fatturapa_import_zip/setup.py
Labels: approved, ready to merge

#3636 [16.0][MIG] l10n_it_delivery_note_batch
  l10n_it_delivery_note_batch/README.rst
  l10n_it_delivery_note_batch/__init__.py
  l10n_it_delivery_note_batch/__manifest__.py
  l10n_it_delivery_note_batch/i18n/it.po
  l10n_it_delivery_note_batch/i18n/l10n_it_delivery_note_batch.pot
  l10n_it_delivery_note_batch/models/__init__.py
  l10n_it_delivery_note_batch/models/stock_delivery_note.py
  l10n_it_delivery_note_batch/models/stock_picking_batch.py
  l10n_it_delivery_note_batch/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note_batch/readme/DESCRIPTION.rst
  l10n_it_delivery_note_batch/readme/USAGE.rst
  l10n_it_delivery_note_batch/static/description/icon.png
  l10n_it_delivery_note_batch/static/description/index.html
  l10n_it_delivery_note_batch/views/stock_picking_batch_views.xml
  l10n_it_delivery_note_batch/views/stock_picking_views.xml
  setup/l10n_it_delivery_note_batch/odoo/addons/l10n_it_delivery_note_batch
  setup/l10n_it_delivery_note_batch/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#3615 [MIG] l10n_it_ricevute_bancarie -> l10n_it_riba
  l10n_it_riba/README.rst
  l10n_it_riba/__init__.py
  l10n_it_riba/__manifest__.py
  l10n_it_riba/data/riba_sequence.xml
  l10n_it_riba/demo/riba_demo.xml
  l10n_it_riba/i18n/it.po
  l10n_it_riba/i18n/l10n_it_riba.pot
  l10n_it_riba/migrations/16.0.1.0.0/data/noupdate.xml
  l10n_it_riba/migrations/16.0.1.0.0/post-migrate.py
  l10n_it_riba/migrations/16.0.1.0.0/pre-migrate.py
  l10n_it_riba/models/__init__.py
  l10n_it_riba/models/account.py
  l10n_it_riba/models/account_config.py
  l10n_it_riba/models/ir_ui_menu.py
  l10n_it_riba/models/partner.py
  l10n_it_riba/models/riba.py
  l10n_it_riba/models/riba_config.py
  l10n_it_riba/readme/CONFIGURE.rst
  l10n_it_riba/readme/CONTRIBUTORS.rst
  l10n_it_riba/readme/DESCRIPTION.rst
  l10n_it_riba/readme/ROADMAP.rst
  l10n_it_riba/readme/USAGE.rst
  l10n_it_riba/report/__init__.py
  l10n_it_riba/report/report.xml
  l10n_it_riba/report/slip_qweb.py
  l10n_it_riba/security/ir.model.access.csv
  l10n_it_riba/security/riba_security.xml
  l10n_it_riba/static/description/icon.png
  l10n_it_riba/static/description/index.html
  l10n_it_riba/tests/__init__.py
  l10n_it_riba/tests/riba_common.py
  l10n_it_riba/tests/test_menu.py
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/views/account_config_view.xml
  l10n_it_riba/views/account_view.xml
  l10n_it_riba/views/configuration_view.xml
  l10n_it_riba/views/partner_view.xml
  l10n_it_riba/views/riba_detail_view.xml
  l10n_it_riba/views/riba_view.xml
  l10n_it_riba/views/slip_report.xml
  l10n_it_riba/views/wizard_credit.xml
  l10n_it_riba/views/wizard_past_due.xml
  l10n_it_riba/views/wizard_presentation.xml
  l10n_it_riba/views/wizard_riba_file_export.xml
  l10n_it_riba/views/wizard_riba_issue.xml
  l10n_it_riba/wizard/__init__.py
  l10n_it_riba/wizard/wizard_credit.py
  l10n_it_riba/wizard/wizard_past_due.py
  l10n_it_riba/wizard/wizard_presentation_riba.py
  l10n_it_riba/wizard/wizard_riba_file_export.py
  l10n_it_riba/wizard/wizard_riba_issue.py
  setup/l10n_it_riba/odoo/addons/l10n_it_riba
  setup/l10n_it_riba/setup.py
  setup/l10n_it_ricevute_bancarie/odoo/addons/l10n_it_ricevute_bancarie
Labels: approved, bot is merging ⏳, needs functional review, 16.0

#3327 [16.0][MIG] l10n_it_intrastat_statement
  l10n_it_intrastat_statement/README.rst
  l10n_it_intrastat_statement/__init__.py
  l10n_it_intrastat_statement/__manifest__.py
  l10n_it_intrastat_statement/data/sequence.xml
  l10n_it_intrastat_statement/i18n/es.po
  l10n_it_intrastat_statement/i18n/it.po
  l10n_it_intrastat_statement/i18n/l10n_it_intrastat_statement.pot
  l10n_it_intrastat_statement/models/__init__.py
  l10n_it_intrastat_statement/models/config.py
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section2.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section3.py
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section4.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section1.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section2.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section3.py
  l10n_it_intrastat_statement/models/intrastat_statement_sale_section4.py
  l10n_it_intrastat_statement/models/intrastat_statement_section.py
  l10n_it_intrastat_statement/readme/CONTRIBUTORS.rst
  l10n_it_intrastat_statement/readme/DESCRIPTION.rst
  l10n_it_intrastat_statement/readme/USAGE.rst
  l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
  l10n_it_intrastat_statement/report/intrastat_mod1_ter.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod1.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
  l10n_it_intrastat_statement/report/reports.xml
  l10n_it_intrastat_statement/security/ir.model.access.csv
  l10n_it_intrastat_statement/security/rules.xml
  l10n_it_intrastat_statement/static/description/icon.png
  l10n_it_intrastat_statement/static/description/index.html
  l10n_it_intrastat_statement/static/img/agenzia_dogane.jpg
  l10n_it_intrastat_statement/static/img/logo_dogane.gif
  l10n_it_intrastat_statement/tests/__init__.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
  l10n_it_intrastat_statement/views/config.xml
  l10n_it_intrastat_statement/views/intrastat.xml
  l10n_it_intrastat_statement/wizard/__init__.py
  l10n_it_intrastat_statement/wizard/export_file.py
  l10n_it_intrastat_statement/wizard/export_file_view.xml
  setup/l10n_it_intrastat_statement/odoo/addons/l10n_it_intrastat_statement
  setup/l10n_it_intrastat_statement/setup.py
Labels: approved, bot is merging ⏳, needs functional review

#3619 [MIG] l10n_it_financial_statements_report
  l10n_it_financial_statements_report/README.rst
  l10n_it_financial_statements_report/__init__.py
  l10n_it_financial_statements_report/__manifest__.py
  l10n_it_financial_statements_report/i18n/it.po
  l10n_it_financial_statements_report/i18n/l10n_it_financial_statements_report.pot
  l10n_it_financial_statements_report/models/__init__.py
  l10n_it_financial_statements_report/models/account_account.py
  l10n_it_financial_statements_report/readme/CONTRIBUTORS.rst
  l10n_it_financial_statements_report/readme/CREDITS.rst
  l10n_it_financial_statements_report/readme/DESCRIPTION.rst
  l10n_it_financial_statements_report/readme/INSTALL.rst
  l10n_it_financial_statements_report/readme/USAGE.rst
  l10n_it_financial_statements_report/report/__init__.py
  l10n_it_financial_statements_report/report/financial_statements_report.py
  l10n_it_financial_statements_report/report/financial_statements_report_xlsx.py
  l10n_it_financial_statements_report/report/reports.xml
  l10n_it_financial_statements_report/report/templates/financial_statements_report.xml
  l10n_it_financial_statements_report/static/description/icon.png
  l10n_it_financial_statements_report/static/description/index.html
  l10n_it_financial_statements_report/static/src/js/action_manager_report.js
  l10n_it_financial_statements_report/static/src/js/client_action.js
  l10n_it_financial_statements_report/tests/__init__.py
  l10n_it_financial_statements_report/tests/test_report.py
  l10n_it_financial_statements_report/wizard/__init__.py
  l10n_it_financial_statements_report/wizard/wizard_financial_statements_report.py
  l10n_it_financial_statements_report/wizard/wizard_financial_statements_report.xml
  setup/l10n_it_financial_statements_report/odoo/addons/l10n_it_financial_statements_report
  setup/l10n_it_financial_statements_report/setup.py
Labels: approved, ready to merge, bot is merging ⏳, needs functional review, 16.0

#3613 [16.0][FIX] l10n_it_delivery_note: fix location address
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#3549 [16.0][ADD] l10n_it_delivery_note: gross_weight and net_weight computation from pickings
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, ready to merge, bot is merging ⏳

#3602 [16.0][ADD] l10n_it_fatturapa_in: aggiunto totale fatture in tree
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3506 [16.0][FIX] l10n_it_declaration_of_intent: controllo dichiarazione solo se tipo fattura
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, bot is merging ⏳

#3606 [16.0] FIX l10n_it_account migration when table account_account_type does not exist
  l10n_it_account/migrations/16.0.1.0.0/post-migrate_balance_sign.py
Labels: approved, ready to merge, bot is merging ⏳

#3338 [16.0] [MIG] l10n_it_website_portal_fiscal_code
  l10n_it_website_portal_fiscalcode/README.rst
  l10n_it_website_portal_fiscalcode/__init__.py
  l10n_it_website_portal_fiscalcode/__manifest__.py
  l10n_it_website_portal_fiscalcode/controllers/__init__.py
  l10n_it_website_portal_fiscalcode/controllers/main.py
  l10n_it_website_portal_fiscalcode/i18n/it.po
  l10n_it_website_portal_fiscalcode/i18n/l10n_it_website_portal_fiscalcode.pot
  l10n_it_website_portal_fiscalcode/readme/DESCRIPTION.rst
  l10n_it_website_portal_fiscalcode/static/description/icon.png
  l10n_it_website_portal_fiscalcode/static/description/index.html
  l10n_it_website_portal_fiscalcode/views/l10n_it_website_portal_fiscalcode_templates.xml
  setup/l10n_it_website_portal_fiscalcode/odoo/addons/l10n_it_website_portal_fiscalcode
  setup/l10n_it_website_portal_fiscalcode/setup.py
Labels: approved, bot is merging ⏳, needs functional review

#3177 [16.0][FIX] l10n_it_delivery_note: sales team access
  l10n_it_delivery_note/models/sale_order.py
  l10n_it_delivery_note/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#3499 [16.0][FIX] l10n_it_delivery_note: fix picking view
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#3583 [16.0] [REF] l10n_it_delivery_note: aggiornato report per trasferimento interno
  l10n_it_delivery_note/report/report_delivery_note.xml
Labels: approved, ready to merge, bot is merging ⏳, needs functional review

#3647 [16.0][FIX] l10n_it_fatturapa_in: link to existing supplier bills with
  l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
Labels: approved, bot is merging ⏳

#3653 [16.0][FIX] l10n_it_fatturapa_out: fix account view related documents…
  l10n_it_fatturapa_out/views/account_view.xml
Labels: approved, bot is merging ⏳

#3654 [16.0][FIX] l10n_it_fatturapa_out: fix account view attachments width
  l10n_it_fatturapa_out/views/account_view.xml
Labels: approved, bot is merging ⏳

#3326 [16.0][FIX] l10n_it_fatturapa_in: fix date in fattura
  l10n_it_fatturapa_in/tests/data/IT05979361218_017.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#3011 [14.0][ADD] l10n_it_delivery_note: gross_weight and net_weight computation from pickings
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: bot is merging ⏳

#3638 [MIG] l10n_it_vat_statement_split_payment
  l10n_it_vat_statement_split_payment/README.rst
  l10n_it_vat_statement_split_payment/__init__.py
  l10n_it_vat_statement_split_payment/__manifest__.py
  l10n_it_vat_statement_split_payment/i18n/it.po
  l10n_it_vat_statement_split_payment/i18n/l10n_it_vat_statement_split_payment.pot
  l10n_it_vat_statement_split_payment/models/__init__.py
  l10n_it_vat_statement_split_payment/models/account.py
  l10n_it_vat_statement_split_payment/models/account_config.py
  l10n_it_vat_statement_split_payment/models/res_company.py
  l10n_it_vat_statement_split_payment/models/statement.py
  l10n_it_vat_statement_split_payment/readme/CONFIGURE.rst
  l10n_it_vat_statement_split_payment/readme/CONTRIBUTORS.rst
  l10n_it_vat_statement_split_payment/readme/CREDITS.rst
  l10n_it_vat_statement_split_payment/readme/DESCRIPTION.rst
  l10n_it_vat_statement_split_payment/readme/USAGE.rst
  l10n_it_vat_statement_split_payment/static/description/icon.png
  l10n_it_vat_statement_split_payment/static/description/index.html
  l10n_it_vat_statement_split_payment/tests/__init__.py
  l10n_it_vat_statement_split_payment/tests/test_vat_statement_split.py
  l10n_it_vat_statement_split_payment/views/account_config_view.xml
  setup/l10n_it_vat_statement_split_payment/odoo/addons/l10n_it_vat_statement_split_payment
  setup/l10n_it_vat_statement_split_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳, needs functional review

#3652 [16.0][FIX] l10n_it_fatturapa_out - delete database constraint after field changed type
  l10n_it_fatturapa_out/migrations/16.0.1.0.9/pre-migrate.py
Labels: approved, ready to merge, bot is merging ⏳

#3640 [FIX] Non deve essere possibile creare o modificare i tipi di documento fiscale
  l10n_it_fiscal_document_type/__manifest__.py
  l10n_it_fiscal_document_type/security/ir.model.access.csv
  l10n_it_fiscal_document_type/tests/test_doc_type.py
Labels: approved, ready to merge, bot is merging ⏳

#3624 [14.0] [IMP] l10n_it_ricevute_bancarie: aggiunto numero fattura nelle account move line create da Ri.Ba
  l10n_it_ricevute_bancarie/models/riba.py
Labels: approved, ready to merge, bot is merging ⏳

#3663 [14.0][FIX] update mantainer username As400it -> MarcoCalcagni
  l10n_it_delivery_note_base/__manifest__.py
  l10n_it_delivery_note_batch/__manifest__.py
  l10n_it_mis_reports_pl_bs/__manifest__.py
Labels: bot is merging ⏳

#3612 [MIG] l10n_it_fatturapa_in_rc
  l10n_it_fatturapa_in_rc/README.rst
  l10n_it_fatturapa_in_rc/__init__.py
  l10n_it_fatturapa_in_rc/__manifest__.py
  l10n_it_fatturapa_in_rc/i18n/it.po
  l10n_it_fatturapa_in_rc/i18n/l10n_it_fatturapa_in_rc.pot
  l10n_it_fatturapa_in_rc/models/__init__.py
  l10n_it_fatturapa_in_rc/models/account_invoice.py
  l10n_it_fatturapa_in_rc/models/account_rc_type.py
  l10n_it_fatturapa_in_rc/models/attachment.py
  l10n_it_fatturapa_in_rc/readme/CONFIGURE.rst
  l10n_it_fatturapa_in_rc/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in_rc/readme/DESCRIPTION.rst
  l10n_it_fatturapa_in_rc/static/description/icon.png
  l10n_it_fatturapa_in_rc/static/description/index.html
  l10n_it_fatturapa_in_rc/tests/__init__.py
  l10n_it_fatturapa_in_rc/tests/data/IT01234567890_FPR04.xml
  l10n_it_fatturapa_in_rc/tests/test_fatturapa_in_rc.py
  l10n_it_fatturapa_in_rc/views/rc_type_view.xml
  l10n_it_fatturapa_in_rc/wizard/__init__.py
  l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py
  setup/l10n_it_fatturapa_in_rc/odoo/addons/l10n_it_fatturapa_in_rc
  setup/l10n_it_fatturapa_in_rc/setup.py
Labels: approved, ready to merge, bot is merging ⏳, needs functional review

#3658 [16.0] [IMP] l10n_it_ricevute_bancarie: aggiunto numero fattura nelle account move line create da Ri.Ba
  l10n_it_riba/models/riba.py
Labels: approved, bot is merging ⏳

#3656 [14.0][IMP] l10n_it_financial_statements_report: add company header
  l10n_it_financial_statements_report/readme/USAGE.rst
  l10n_it_financial_statements_report/report/templates/financial_statements_report.xml
Labels: approved, bot is merging ⏳

#3540 [IMP][14.0]l10n_it_riba_sale_commission: generazione provvigioni con data pagamento
  l10n_it_riba_sale_commission/__manifest__.py
  l10n_it_riba_sale_commission/models/account_move.py
  l10n_it_riba_sale_commission/readme/DESCRIPTION.rst
  l10n_it_riba_sale_commission/tests/__init__.py
  l10n_it_riba_sale_commission/tests/test_riba_sale_commission.py
  l10n_it_riba_sale_commission/wizard/wizard_riba_commissions_settle.py
Labels: approved, ready to merge, bot is merging ⏳

#3394 [16.0] [MIG] l10n_it_vat_registries_split_payment
  l10n_it_vat_registries_split_payment/README.rst
  l10n_it_vat_registries_split_payment/__init__.py
  l10n_it_vat_registries_split_payment/__manifest__.py
  l10n_it_vat_registries_split_payment/i18n/it.po
  l10n_it_vat_registries_split_payment/i18n/l10n_it_vat_registries_split_payment.pot
  l10n_it_vat_registries_split_payment/readme/CONTRIBUTORS.rst
  l10n_it_vat_registries_split_payment/readme/DESCRIPTION.rst
  l10n_it_vat_registries_split_payment/report/__init__.py
  l10n_it_vat_registries_split_payment/report/report_vat_registry.py
  l10n_it_vat_registries_split_payment/static/description/icon.png
  l10n_it_vat_registries_split_payment/static/description/index.html
  l10n_it_vat_registries_split_payment/tests/__init__.py
  l10n_it_vat_registries_split_payment/tests/test_sp.py
  setup/l10n_it_vat_registries_split_payment/odoo/addons/l10n_it_vat_registries_split_payment
  setup/l10n_it_vat_registries_split_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳, needs functional review, 16.0

#3601 [14.0] FIX l10n_it_financial_statements_report: use landscape format for PDF
  l10n_it_financial_statements_report/report/financial_statements_report.py
  l10n_it_financial_statements_report/report/reports.xml
  l10n_it_financial_statements_report/report/templates/financial_statements_report.xml
Labels: approved, bot is merging ⏳

#3308 [14.0] [IMP] l10n_it_delivery_note_base: creazione dinamica dei tipi di DN e delle loro sequenze
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_sequence.py
  l10n_it_delivery_note_base/__init__.py
  l10n_it_delivery_note_base/__manifest__.py
  l10n_it_delivery_note_base/data/delivery_note_data.xml
  l10n_it_delivery_note_base/hooks.py
  l10n_it_delivery_note_base/models/__init__.py
  l10n_it_delivery_note_base/models/res_company.py
  l10n_it_delivery_note_base/models/stock_delivery_note_type.py
  l10n_it_delivery_note_base/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#3675 Update of Maintainers
  l10n_it_delivery_note_base/__manifest__.py
Labels: bot is merging ⏳

#3676 Update of Maintainers
  l10n_it_delivery_note_batch/__manifest__.py
Labels: bot is merging ⏳

#3673 [14.0] `l10n_it_delivery_note_base`: Rimosso l'utente `Byloth` dai maintainers.
  l10n_it_delivery_note_base/__manifest__.py
Labels: bot is merging ⏳

#3672 [12.0] `l10n_it_delivery_note_base`: Rimosso l'utente `Byloth` dai maintainers.
  l10n_it_delivery_note_base/__manifest__.py
Labels: bot is merging ⏳

#3664 [16.0][IMP] l10n_it_delivery_note_base: creazione dinamica dei tipi di DN e delle loro sequenze
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_sequence.py
  l10n_it_delivery_note_base/__init__.py
  l10n_it_delivery_note_base/__manifest__.py
  l10n_it_delivery_note_base/data/delivery_note_data.xml
  l10n_it_delivery_note_base/hooks.py
  l10n_it_delivery_note_base/models/__init__.py
  l10n_it_delivery_note_base/models/res_company.py
  l10n_it_delivery_note_base/models/stock_delivery_note_type.py
  l10n_it_delivery_note_base/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#3518 [14.0][FIX]l10n_it_delivery_note: change inconsistent strings
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, ready to merge, bot is merging ⏳

#3495 [14.0][FIX] l10n_it_withholding_tax_reason migration script compatibile con apriori
  l10n_it_withholding_tax_reason/__init__.py
  l10n_it_withholding_tax_reason/__manifest__.py
  l10n_it_withholding_tax_reason/hooks.py
  l10n_it_withholding_tax_reason/migrations/14.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#3604 [FIX] migration script for l10n_it_payment_reason with OpenUpgrade
  l10n_it_payment_reason/__init__.py
  l10n_it_payment_reason/__manifest__.py
  l10n_it_payment_reason/hooks.py
Labels: bot is merging ⏳

#3480 [14.0][FIX] l10n_it_declaration_of_intent pre-migration script compatibile con apriori
  l10n_it_declaration_of_intent/__init__.py
  l10n_it_declaration_of_intent/__manifest__.py
  l10n_it_declaration_of_intent/hooks.py
  l10n_it_declaration_of_intent/migrations/13.0.1.0.0/post-migrate.py
  l10n_it_declaration_of_intent/migrations/13.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳

#3598 [FIX][14.0] set migration script of l10n_it_appointment_code to same logic of other
  l10n_it_appointment_code/__init__.py
  l10n_it_appointment_code/__manifest__.py
  l10n_it_appointment_code/hooks.py
Labels: bot is merging ⏳

#3635 [FIX][14.0] move invoice_id script to pre-migration
  l10n_it_intrastat_statement/migrations/13.0.1.0.0/post-migration.py
  l10n_it_intrastat_statement/migrations/13.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#3470 [14.0][FIX] l10n_it_delivery_note: fix action window
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: bot is merging ⏳
