Repository OCA/l10n-italy, pull requests merged in 2024-01, with the labels that each got.

#3803 [IMP] l10n_it_delivery_note: picking's dn fields optional in tree view
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#3727 [14.0] [IMP] l10n_it_delivery_note: filter 'type_id' based on company
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/views/stock_delivery_note.xml
  l10n_it_delivery_note/wizard/delivery_note_base.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3750 [16.0] [FIX] l10n_it_delivery_note: fix partner ddt
  l10n_it_delivery_note/models/stock_picking.py
Labels: bot is merging ⏳, 16.0

#3806 [FIX] l10n_it_fatturapa_pec: filename without colon
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA_ Invio File 7339338 (base64).txt
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
Labels: approved, ready to merge, bot is merging ⏳

#3794 [IMP] l10n_it_delivery_note: add maintainers
  l10n_it_delivery_note/__manifest__.py
Labels: bot is merging ⏳

#3539 [14.0][FIX] l10n_it_central_journal_reportlab: utilizzare i data range solo con azienda impostata
  l10n_it_central_journal_reportlab/wizard/print_giornale.xml
Labels: approved, bot is merging ⏳, 14.0, missing issue

#3418 [FIX][l10n_it_ricevute_bancarie] fix issue https://github.com/OCA/l10…
  l10n_it_ricevute_bancarie/views/account_view.xml
Labels: approved, bot is merging ⏳, 14.0

#3159 [14.0][FIX] l10n_it_intrastat_statement: report doesn't show the right origin country for the good
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
Labels: bot is merging ⏳, 14.0

#3629 [16.0][MIG] l10n_it_bill_of_entry
  l10n_it_bill_of_entry/README.rst
  l10n_it_bill_of_entry/__init__.py
  l10n_it_bill_of_entry/__manifest__.py
  l10n_it_bill_of_entry/demo/bill_of_entry_demo.xml
  l10n_it_bill_of_entry/i18n/it.po
  l10n_it_bill_of_entry/i18n/l10n_it_bill_of_entry.pot
  l10n_it_bill_of_entry/models/__init__.py
  l10n_it_bill_of_entry/models/account_move.py
  l10n_it_bill_of_entry/models/company.py
  l10n_it_bill_of_entry/readme/CONFIGURE.rst
  l10n_it_bill_of_entry/readme/CONTRIBUTORS.rst
  l10n_it_bill_of_entry/readme/DESCRIPTION.rst
  l10n_it_bill_of_entry/readme/USAGE.rst
  l10n_it_bill_of_entry/static/description/icon.png
  l10n_it_bill_of_entry/static/description/index.html
  l10n_it_bill_of_entry/tests/__init__.py
  l10n_it_bill_of_entry/tests/test_bill_of_entry.py
  l10n_it_bill_of_entry/views/account_invoice_view.xml
  l10n_it_bill_of_entry/views/company_view.xml
  setup/l10n_it_bill_of_entry/odoo/addons/l10n_it_bill_of_entry
  setup/l10n_it_bill_of_entry/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 16.0

#3839 [14.0][FIX] l10n_it_delivery_note_inter_*: remove pickings
  l10n_it_delivery_note_inter_company/models/stock_delivery_note.py
  l10n_it_delivery_note_inter_warehouse/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳, 14.0, no issue needed

#3818 [16.0] [MIG] l10n_it_fatturapa_out_oss
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_oss/README.rst
  l10n_it_fatturapa_out_oss/__init__.py
  l10n_it_fatturapa_out_oss/__manifest__.py
  l10n_it_fatturapa_out_oss/data/invoice_it_template.xml
  l10n_it_fatturapa_out_oss/i18n/it.po
  l10n_it_fatturapa_out_oss/i18n/l10n_it_fatturapa_out_oss.pot
  l10n_it_fatturapa_out_oss/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_oss/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_oss/static/description/icon.png
  l10n_it_fatturapa_out_oss/static/description/index.html
  l10n_it_fatturapa_out_oss/tests/__init__.py
  l10n_it_fatturapa_out_oss/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_oss/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out_oss/tests/fatturapa_common.py
  l10n_it_fatturapa_out_oss/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_oss/wizard/__init__.py
  l10n_it_fatturapa_out_oss/wizard/l10n_eu_oss_wizard.py
  setup/l10n_it_fatturapa_out_oss/odoo/addons/l10n_it_fatturapa_out_oss
  setup/l10n_it_fatturapa_out_oss/setup.py
Labels: migration, bot is merging ⏳, 16.0

#3845 [16.0] [FIX] l10n_it_delivery_note: fix qty line
  l10n_it_delivery_note/models/stock_delivery_note_line.py
Labels: approved, bot is merging ⏳

#3829 [14.0][IMP] l10n_it_delivery_note: add hook to prepare vals needed to create DN
  l10n_it_delivery_note/wizard/delivery_note_create.py
Labels: approved, bot is merging ⏳

#3812 [16.0] [IMP] l10n_it_delivery_note: picking's dn fields optional in tree view
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#3846 [16.0] FIX l10n_it_fatturapa_out: it does not depend on l10n_eu_oss_oca so it can't use oss_country_id
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_oss/wizard/__init__.py
  l10n_it_fatturapa_out_oss/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#3849 [IMP][14.0] l10n_it_delivery_note_customer_code: add fields to view
  l10n_it_delivery_note_customer_code/README.rst
  l10n_it_delivery_note_customer_code/__manifest__.py
  l10n_it_delivery_note_customer_code/static/description/index.html
  l10n_it_delivery_note_customer_code/views/stock_delivery_note_views.xml
Labels: approved, bot is merging ⏳

#3834 [14.0][IMP] l10n_it_delivery_note: add SO number and customer reference to DN report
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/models/__init__.py
  l10n_it_delivery_note/models/res_company.py
  l10n_it_delivery_note/models/res_config_settings.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/readme/CONFIGURE.rst
  l10n_it_delivery_note/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/views/res_config_settings.xml
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3857 [FIX] l10n_it_intrastat action_post
  l10n_it_intrastat/models/account.py
Labels: approved, bot is merging ⏳

#3862 [14.0] [FIX] l10n_it_delivery_note: fix qty line
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#3864 [16.0] FIX l10n_it_reverse_charge: reconcile_supplier_invoice setting currency to avoid redundant exchange_diff_move when not needed
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#3881 [14.0] [REF] l10n_it_delivery_note: aggiornato report per trasferimento interno
  l10n_it_delivery_note/report/report_delivery_note.xml
Labels: approved, bot is merging ⏳

#3848 [FIX] currency_rate_update_boi: fix test
  currency_rate_update_boi/tests/test_currency_rate_update_boi.py
Labels: approved, ready to merge, bot is merging ⏳

#3889 [14.0][l10n_it_intrastat_statement] Fix credit note compensation not in period
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
  l10n_it_intrastat_statement/views/intrastat.xml
Labels: bot is merging ⏳

#3902 [14.0] [IMP] l10n_it_delivery_note: group pickings by dn state and date
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#3896 [16.0] [FIX] l10n_it_account_tax_kind unhide law reference on tax
  l10n_it_account_tax_kind/view/account_tax_view.xml
Labels: approved, bot is merging ⏳

#3895 [14.0] [FIX] l10n_it_account_tax_kind unhide law reference on tax
  l10n_it_account_tax_kind/view/account_tax_view.xml
Labels: approved, bot is merging ⏳

#3699 [16.0] [FIX] nolabel view
  account_vat_period_end_statement/views/account_view.xml
  l10n_it_ateco/view/ateco_view.xml
  l10n_it_ateco/view/partner_view.xml
  l10n_it_central_journal_reportlab/wizard/print_giornale.xml
  l10n_it_declaration_of_intent/wizard/select_declarations_view.xml
  l10n_it_delivery_note/views/stock_picking.xml
  l10n_it_fatturapa/views/account_view.xml
  l10n_it_fatturapa_in/views/account_view.xml
  l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
  l10n_it_fatturapa_sale/views/sale_order_views.xml
  l10n_it_intrastat/views/account.xml
  l10n_it_withholding_tax_payment/views/withholding_tax.xml
Labels: approved, ready to merge, bot is merging ⏳, 16.0, no issue needed

#3909 [12.0] [FIX] Fix problematic tests
  assets_management/tests/test_assets_management.py
  l10n_it_fatturapa_out_welfare/tests/data/IT06363391001_random.xml
Labels: approved, bot is merging ⏳, no issue needed

#3186 [ADD] l10n_it_fatturapa_out_fd
  l10n_it_fatturapa_out_fd/__init__.py
  l10n_it_fatturapa_out_fd/__manifest__.py
  l10n_it_fatturapa_out_fd/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_fd/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_fd/tests/__init__.py
  l10n_it_fatturapa_out_fd/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_fd/tests/test_xml_generation.py
  l10n_it_fatturapa_out_fd/wizards/__init__.py
  l10n_it_fatturapa_out_fd/wizards/wizard_export_fatturapa.py
  setup/l10n_it_fatturapa_out_fd/odoo/addons/l10n_it_fatturapa_out_fd
  setup/l10n_it_fatturapa_out_fd/setup.py
Labels: approved, 12.0, bot is merging ⏳, new module

#3894 [12.0] [FIX] l10n_it_account_tax_kind: unhide law reference on tax
  l10n_it_account_tax_kind/view/account_tax_view.xml
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#3918 [16.0] FIX l10n_it_abicab views incompatibility
  l10n_it_abicab/views/abicab_view.xml
Labels: bot is merging ⏳
