Repository OCA/l10n-italy, pull requests merged in 2024-09, with the labels that each got.

#4344 [FIX] Scritte ripetute nella stampa di una liquidazione IVA pagata
  account_vat_period_end_statement/tests/test_vat_statement.py
  account_vat_period_end_statement/views/report_vatperiodendstatement.xml
Labels: approved, bot is merging ⏳

#3505 [FIX] Righe negative, note e sezioni in fattura fornitore con inversione contabile
  l10n_it_reverse_charge/models/account_move.py
  l10n_it_reverse_charge/tests/test_rc.py
Labels: approved, bot is merging ⏳, 14.0

#4327 [FIX] l10n_it_intrastat: compute weight in case of variants
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/tests/test_intrastat.py
Labels: approved, ready to merge, bot is merging ⏳

#4326 [FIX] RiBa: utilizzare banca del partner commerciale in caso di indirizzo di fatturazione
  l10n_it_riba/models/account.py
  l10n_it_riba/tests/__init__.py
  l10n_it_riba/tests/test_account_move.py
  l10n_it_riba/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3985 [16.0] ADD l10n_it_withholding_tax_payment_order: Integrazione Ritenute d'acconto e Ordini di pagamento
  l10n_it_withholding_tax_payment_order/README.rst
  l10n_it_withholding_tax_payment_order/__init__.py
  l10n_it_withholding_tax_payment_order/__manifest__.py
  l10n_it_withholding_tax_payment_order/models/__init__.py
  l10n_it_withholding_tax_payment_order/models/account_move_line.py
  l10n_it_withholding_tax_payment_order/pyproject.toml
  l10n_it_withholding_tax_payment_order/readme/CONTRIBUTORS.md
  l10n_it_withholding_tax_payment_order/readme/DESCRIPTION.md
  l10n_it_withholding_tax_payment_order/static/description/index.html
  setup/l10n_it_withholding_tax_payment_order/odoo/addons/l10n_it_withholding_tax_payment_order
  setup/l10n_it_withholding_tax_payment_order/setup.py
Labels: approved, bot is merging ⏳, 16.0, new module

#4328 [FIX] l10n_it_riba esporta file senza rimuovere i caratteri non accettati
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/wizard/wizard_riba_file_export.py
Labels: bot is merging ⏳

#4351 [FIX] RiBa: conferma fatture senza conto bancario da list view
  l10n_it_riba/models/account.py
  l10n_it_riba/tests/test_riba.py
Labels: approved, ready to merge, bot is merging ⏳

#4357 [16.0] [FIX] l10n_it_vat_statement_communication: fix file doctype declaration
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, bot is merging ⏳

#4189 [MIG] l10n_it_sepa_bonifici -> l10n_it_sct_cbi
  .pre-commit-config.yaml
  l10n_it_sct_cbi/README.rst
  l10n_it_sct_cbi/__init__.py
  l10n_it_sct_cbi/__manifest__.py
  l10n_it_sct_cbi/data/account_payment_method.xml
  l10n_it_sct_cbi/data/standards/CBIBdyCrossBorderPaymentRequest.00.01.01.xsd
  l10n_it_sct_cbi/data/standards/CBIBdyPaymentRequest.00.04.01.xsd
  l10n_it_sct_cbi/data/standards/CBICrossBorderPaymentRequestLogMsg.00.01.01.xsd
  l10n_it_sct_cbi/data/standards/CBICrossBorderPaymentRequestPhyMsg.00.01.01.xsd
  l10n_it_sct_cbi/data/standards/CBIHdrSrv.001.07.xsd
  l10n_it_sct_cbi/data/standards/CBIHdrTrt.001.07.xsd
  l10n_it_sct_cbi/data/standards/CBIPaymentRequest.00.04.01.xsd
  l10n_it_sct_cbi/data/standards/CBIPaymentRequestMsg.00.04.01.xsd
  l10n_it_sct_cbi/data/standards/CBISgnInf.001.04.xsd
  l10n_it_sct_cbi/i18n/it.po
  l10n_it_sct_cbi/i18n/l10n_it_sct_cbi.pot
  l10n_it_sct_cbi/i18n/sl.po
  l10n_it_sct_cbi/models/__init__.py
  l10n_it_sct_cbi/models/account_payment_method.py
  l10n_it_sct_cbi/models/account_payment_order.py
  l10n_it_sct_cbi/pyproject.toml
  l10n_it_sct_cbi/readme/CONFIGURE.md
  l10n_it_sct_cbi/readme/CONTRIBUTORS.md
  l10n_it_sct_cbi/readme/DESCRIPTION.md
  l10n_it_sct_cbi/readme/USAGE.md
  l10n_it_sct_cbi/static/company_setting.png
  l10n_it_sct_cbi/static/description/icon.png
  l10n_it_sct_cbi/static/description/index.html
  l10n_it_sct_cbi/static/generate_payment.png
  l10n_it_sct_cbi/static/make_payment_download.png
  l10n_it_sct_cbi/static/order_payment.png
  l10n_it_sct_cbi/static/payment_mode1.png
  l10n_it_sct_cbi/static/payment_mode2.png
  l10n_it_sct_cbi/tests/__init__.py
  l10n_it_sct_cbi/tests/test_generate_file.py
Labels: approved, migration, bot is merging ⏳, 16.0, needs technical review

#4345 [14.0][FIX]assets_management: properly open wizard
  assets_management/models/account_move.py
  assets_management/tests/test_assets_common.py
  assets_management/tests/test_assets_management.py
  assets_management/wizard/account_move_manage_asset.py
Labels: approved, bot is merging ⏳, 14.0

#4324 [14.0][IMP]l10n_it_delivery_note: split move lines based on dn
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/models/sale_order.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
Labels: bot is merging ⏳, 14.0

#4282 [FIX] account_vat_period_end_statement: remove not required dependency
  account_vat_period_end_statement/__manifest__.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#4388 [FIX] l10n_it_account: Fixed context overwrite in account tax
  l10n_it_account/models/account_tax.py
Labels: approved, bot is merging ⏳, no issue needed
