Repository OCA/l10n-italy, pull requests merged in 2024-08, with the labels that each got.

#4306 [IMP][14.0] l10n_it_ricevute_bancarie: small QoL improvements
  l10n_it_ricevute_bancarie/models/account.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#4313 [14.0][FIX] l10n_it_delivery_note: get right dn when creating invoice
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
Labels: approved, bot is merging ⏳

#3800 [FIX] l10n_it_fatturapa_out: Configurazione in azienda per numero massimo fatture per fattura elettronica
  l10n_it_fatturapa_out/models/partner.py
  l10n_it_fatturapa_out/tests/fatturapa_common.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: bot is merging ⏳

#4307 [16.0] [FIX] l10n_it_intrastat using invoice ref
  l10n_it_intrastat/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#4238 [FIX] l10n_it_reverse_charge: force amount_currency set in line values
  l10n_it_reverse_charge/models/account_move.py
  l10n_it_reverse_charge/tests/rc_common.py
  l10n_it_reverse_charge/tests/test_rc.py
Labels: approved, ready to merge, bot is merging ⏳

#4317 [FIX]l10n_it_vat_statement_communication: fix name type encoding miss…
  l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
Labels: approved, bot is merging ⏳, 14.0

#4133 [14.0] l10n_it_fatturapa: tolto staticmethod a ftpa_preview_xml
  l10n_it_fatturapa/models/ir_attachment.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: approved, bot is merging ⏳, 14.0

#4311 [FIX] l10n_it_intrastat: Permettere agli override di eseguire un'azione
  l10n_it_intrastat/README.rst
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/readme/CONTRIBUTORS.md
  l10n_it_intrastat/static/description/index.html
  l10n_it_intrastat/tests/test_intrastat.py
Labels: bot is merging ⏳

#4320 [16.0][FIX] l10n_it_intrastat_statement: report doesn't show the right origin country for the good
  l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
Labels: approved, ready to merge, bot is merging ⏳

#4316 [FIX] Intrastat: sulla stampa del modello non sono indicati alcuni campi
  l10n_it_intrastat_statement/report/report_intrastat_mod1.xml
  l10n_it_intrastat_statement/report/report_intrastat_mod2.xml
Labels: approved, ready to merge, bot is merging ⏳

#4295 [IMP] l10n_it_fatturapa_out: Better error messages on XML validation
  l10n_it_account/tools/account_tools.py
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/efattura.py
Labels: bot is merging ⏳

#3984 [16.0] [IMP] l10n_it_riba: aggiungere esposizione/rischio e migliorare la gestione degli insoluti
  l10n_it_riba/README.rst
  l10n_it_riba/__manifest__.py
  l10n_it_riba/models/account.py
  l10n_it_riba/models/riba.py
  l10n_it_riba/models/riba_config.py
  l10n_it_riba/readme/CONFIGURE.md
  l10n_it_riba/readme/CONTRIBUTORS.md
  l10n_it_riba/readme/USAGE.md
  l10n_it_riba/security/ir.model.access.csv
  l10n_it_riba/static/description/index.html
  l10n_it_riba/tests/riba_common.py
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/views/account_view.xml
  l10n_it_riba/views/configuration_view.xml
  l10n_it_riba/views/riba_detail_view.xml
  l10n_it_riba/views/riba_view.xml
  l10n_it_riba/views/wizard_riba_payment_date.xml
  l10n_it_riba/wizard/__init__.py
  l10n_it_riba/wizard/wizard_past_due.py
  l10n_it_riba/wizard/wizard_riba_payment_date.py
Labels: approved, bot is merging ⏳

#3986 [FIX] Nelle fatture con ritenuta, resettare l'importo da pagare al netto da pagare residuo
  l10n_it_withholding_tax/README.rst
  l10n_it_withholding_tax/__init__.py
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/readme/ROADMAP.md
  l10n_it_withholding_tax/static/description/index.html
  l10n_it_withholding_tax/tests/test_withholding_tax.py
  l10n_it_withholding_tax/wizards/__init__.py
  l10n_it_withholding_tax/wizards/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳

#4207 [COV] l10n_it_declaration_of_intent: Validazione massiva di fatture
  l10n_it_declaration_of_intent/README.rst
  l10n_it_declaration_of_intent/readme/CONTRIBUTORS.md
  l10n_it_declaration_of_intent/static/description/index.html
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0
