Repository OCA/l10n-italy, pull requests merged in 2024-04, with the labels that each got.

#4056 [16.0] [FIX] l10n_it_fatturapa_out - wizard only reports
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#4013 [FIX] Sezione dei risconti attivi nel bilancio a sezioni contrapposte
  l10n_it_financial_statements_report/__manifest__.py
  l10n_it_financial_statements_report/migrations/16.0.1.0.1/post-migrate.py
  l10n_it_financial_statements_report/models/account_account.py
  l10n_it_financial_statements_report/tests/__init__.py
  l10n_it_financial_statements_report/tests/test_account.py
Labels: approved, ready to merge, bot is merging ⏳

#4083 [16.0][MIG] l10n_it_website_sale_fiscalcode
  l10n_it_website_sale_fiscalcode/README.rst
  l10n_it_website_sale_fiscalcode/__init__.py
  l10n_it_website_sale_fiscalcode/__manifest__.py
  l10n_it_website_sale_fiscalcode/controllers/__init__.py
  l10n_it_website_sale_fiscalcode/controllers/main.py
  l10n_it_website_sale_fiscalcode/i18n/de.po
  l10n_it_website_sale_fiscalcode/i18n/es.po
  l10n_it_website_sale_fiscalcode/i18n/it.po
  l10n_it_website_sale_fiscalcode/i18n/l10n_it_website_sale_fiscalcode.pot
  l10n_it_website_sale_fiscalcode/i18n/sl.po
  l10n_it_website_sale_fiscalcode/pyproject.toml
  l10n_it_website_sale_fiscalcode/readme/CONTRIBUTORS.md
  l10n_it_website_sale_fiscalcode/readme/DESCRIPTION.md
  l10n_it_website_sale_fiscalcode/readme/USAGE.md
  l10n_it_website_sale_fiscalcode/static/description/icon.png
  l10n_it_website_sale_fiscalcode/static/description/index.html
  l10n_it_website_sale_fiscalcode/views/templates.xml
Labels: migration, bot is merging ⏳, 16.0

#4026 [FIX] Fattura elettronica TD01 con totale negativo
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/tests/data/IT02098391200_FPR16.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: approved, bot is merging ⏳

#4089 [14.0][IMP]l10n_it_delivery_note: show total price in StockDeliveryNote report
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/models/res_company.py
  l10n_it_delivery_note/models/res_config_settings.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/readme/CONFIGURE.rst
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#4112 [14.0] [FIX] l10n_it_delivery_note: report adjustments
  l10n_it_delivery_note/report/report_delivery_note.xml
Labels: bot is merging ⏳
