Repository OCA/l10n-italy, pull requests merged in 2024-06, with the labels that each got.

#4150 [14.0][FIX] l10n_it_ricevute_bancarie: allow issuing only on posted move
  l10n_it_ricevute_bancarie/views/account_view.xml
  l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py
Labels: approved, bot is merging ⏳, 14.0

#4176 [FIX] l10n_it_declaration_of_intent: remove line on move.unlink()
  l10n_it_declaration_of_intent/__manifest__.py
  l10n_it_declaration_of_intent/demo/declaration_of_intent.xml
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, bot is merging ⏳

#4161 FIX 16.0-l10n_it_fiscalcode: Fix invoice report, now fiscalcode is always printed if present in partner
  l10n_it_fiscalcode/view/report_invoice_document.xml
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#4194 [14.0][FIX]Backport 4107: errore attachment e-fatture
  l10n_it_fatturapa/README.rst
  l10n_it_fatturapa/__manifest__.py
  l10n_it_fatturapa/models/__init__.py
  l10n_it_fatturapa/models/link_e_invoice_ir_attachment.py
  l10n_it_fatturapa/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa/static/description/index.html
  l10n_it_fatturapa_import_zip/__manifest__.py
  l10n_it_fatturapa_import_zip/migrations/14.0.1.1.0/post-migrate.py
  l10n_it_fatturapa_import_zip/models/attachment.py
  l10n_it_fatturapa_import_zip/static/description/index.html
  l10n_it_fatturapa_import_zip/tests/test_import_zip.py
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/migrations/14.0.2.3.0/post-migrate.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/migrations/14.0.3.6.0/post-migrate.py
  l10n_it_fatturapa_out/models/attachment.py
  l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: bot is merging ⏳

#4180 [14.0][FIX] l10n_it_fiscalcode: add codicefiscale.isvalid() and check when partner becomes a person
  l10n_it_fiscalcode/README.rst
  l10n_it_fiscalcode/model/res_partner.py
  l10n_it_fiscalcode/readme/CONTRIBUTORS.rst
  l10n_it_fiscalcode/static/description/index.html
  l10n_it_fiscalcode/tests/test_fiscalcode.py
Labels: approved, ready to merge, bot is merging ⏳

#4199 [FIX] l10n_it_withholding_tax: fix singleton error
  l10n_it_withholding_tax/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#4178 [FIX]l10n_it_financial_statements_report: Syntax compatibility
  l10n_it_financial_statements_report/report/financial_statements_report_xlsx.py
Labels: approved, ready to merge, bot is merging ⏳

#4193 [FIX] l10n_it_bill_of_entry: Gestione del multi-azienda nei test
  l10n_it_bill_of_entry/tests/test_bill_of_entry.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#3431 [14.0][FW] ricevute bancarie ASCII instead UTF-8
  l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
Labels: bot is merging ⏳, 14.0, no stale

#4186 [16.0] [FIX] l10n_it_intrastat_statement: progressive_to_modify_id is not used
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section4.py
Labels: approved, ready to merge, bot is merging ⏳

#3715 [16.0] [FIX] set l10n_it_fatturapa_out XML templates as not translatable
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out_di/data/invoice_it_template.xml
  l10n_it_fatturapa_out_stamp/views/account_invoice_it_dati_bollo.xml
  l10n_it_fatturapa_out_wt/views/account_invoice_it_dati_ritenuta.xml
Labels: bot is merging ⏳, 16.0

#3729 [FIX] account_vat_period_end_statement: Creazione del movimento quando c'è un termine di pagamento
  account_vat_period_end_statement/README.rst
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/readme/CONTRIBUTORS.md
  account_vat_period_end_statement/static/description/index.html
  account_vat_period_end_statement/tests/common.py
  account_vat_period_end_statement/tests/test_vat_statement.py
Labels: bot is merging ⏳, 16.0, no issue needed

#4202 [16.0][ADD] l10n_it_ricevute_bancarie: allow set 'Paid' lines by due date
  l10n_it_riba/__manifest__.py
  l10n_it_riba/models/riba.py
  l10n_it_riba/security/ir.model.access.csv
  l10n_it_riba/static/description/index.html
  l10n_it_riba/views/wizard_due_date_settlement.xml
  l10n_it_riba/wizard/__init__.py
  l10n_it_riba/wizard/wizard_due_date_settlement.py
Labels: approved, bot is merging ⏳

#4191 [FIX] l10n_it_delivery_note: unlink DNs from invoices at Cancel
  l10n_it_delivery_note/models/account_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#3824 [16.0][FIX] l10n_it_delivery_note: removed cli migration from l10n_it_ddt
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/__init__.py
  l10n_it_delivery_note/cli/__init__.py
  l10n_it_delivery_note/cli/core.py
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/readme/USAGE.md
  l10n_it_delivery_note/static/description/index.html
Labels: bot is merging ⏳, stale

#4226 [14.0][FIX] l10n_it_delivery_note: unlink DNs from invoices at Cancel
  l10n_it_delivery_note/models/account_invoice.py
Labels: approved, bot is merging ⏳

#4198 [FIX] l10n_it_declaration_of_intent: improve date description and positioning
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/views/declaration_of_intent_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳, 16.0, no issue needed

#3877 [FIX][l10n_it_riba] creazione configurazioni Ri.Ba con utente multicompany
  l10n_it_riba/models/riba_config.py
  l10n_it_riba/tests/riba_common.py
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/views/configuration_view.xml
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#2841 [14.0] [ADD] new module l10n_it_amount_to_text
  l10n_it_amount_to_text/README.rst
  l10n_it_amount_to_text/__init__.py
  l10n_it_amount_to_text/__manifest__.py
  l10n_it_amount_to_text/i18n/it.po
  l10n_it_amount_to_text/i18n/l10n_it_amount_to_text.pot
  l10n_it_amount_to_text/models/__init__.py
  l10n_it_amount_to_text/models/res_currency.py
  l10n_it_amount_to_text/readme/CONFIGURE.rst
  l10n_it_amount_to_text/readme/CONTRIBUTORS.rst
  l10n_it_amount_to_text/readme/DESCRIPTION.rst
  l10n_it_amount_to_text/readme/USAGE.rst
  l10n_it_amount_to_text/static/description/index.html
  l10n_it_amount_to_text/tests/__init__.py
  l10n_it_amount_to_text/tests/test_amount_to_text.py
  requirements.txt
  setup/l10n_it_amount_to_text/odoo/addons/l10n_it_amount_to_text
  setup/l10n_it_amount_to_text/setup.py
Labels: bot is merging ⏳, 14.0, new module

#4009 [14.0][l10n_it_fatturapa] Add FoglioStileSouthTyrol-bilingue.xsl as alternative stylesheet for electronic invoices preview
  .pre-commit-config.yaml
  l10n_it_fatturapa/data/FoglioStileSouthTyrol-bilingue.xsl
  l10n_it_fatturapa/models/company.py
Labels: approved, ready to merge, bot is merging ⏳
