Repository OCA/l10n-italy, pull requests merged in 2024-02, with the labels that each got.

#3919 [14.0] [IMP] l10n_it_delivery_note: delivery note company field adjustments
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳, 14.0

#3838 [14.0] [IMP] l10n_it_delivery_note: link carrier with delivery method
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/demo/delivery_carrier_demo.xml
  l10n_it_delivery_note/demo/res_partner_demo.xml
  l10n_it_delivery_note/migrations/14.0.3.0.0/post-migrate.py
  l10n_it_delivery_note/models/res_company.py
  l10n_it_delivery_note/models/res_config_settings.py
  l10n_it_delivery_note/models/res_partner.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/readme/CONFIGURE.rst
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/security/ir.model.access.csv
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/views/res_config_settings.xml
  l10n_it_delivery_note/views/res_partner.xml
  l10n_it_delivery_note/views/stock_delivery_note.xml
  l10n_it_delivery_note/views/stock_picking.xml
  l10n_it_delivery_note/wizard/__init__.py
  l10n_it_delivery_note/wizard/delivery_note_base.py
  l10n_it_delivery_note/wizard/delivery_note_confirm.py
  l10n_it_delivery_note/wizard/delivery_note_confirm.xml
  l10n_it_delivery_note/wizard/delivery_note_create.py
  l10n_it_delivery_note/wizard/delivery_note_select.py
  l10n_it_delivery_note/wizard/delivery_note_select.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3696 [16.0] [FIX] l10n_it_fatturapa_out: fix migration script
  l10n_it_fatturapa_out/migrations/16.0.1.0.0/pre-migrate.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#3906 [16.0][FIX] l10n_it_reverse_charge: fix case there is a line with abbuoni
  l10n_it_reverse_charge/__manifest__.py
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳, 16.0

#3256 [14.0][IMP] l10n_it_intrastat: added intrastat country origin on product and category
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/models/product.py
  l10n_it_intrastat/views/product.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3817 [16.0][IMP] l10n_it_delivery_note: filter 'type_id' based on company
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/views/stock_delivery_note.xml
  l10n_it_delivery_note/wizard/delivery_note_base.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
Labels: approved, bot is merging ⏳

#3923 [16.0] FIX l10n_it_fatturapa_out: Unexpected child with tag 'Nome'
  l10n_it_fatturapa_out/data/invoice_it_template.xml
Labels: approved, bot is merging ⏳, 16.0, missing issue

#3885 [16.0] l10n_it_riba: fix state update on riba lines
  l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/wizard/wizard_credit.py
Labels: approved, ready to merge, bot is merging ⏳

#3250 14.0][FIX] l10n_it_central_journal_reportlab, esclude linee con account name o code non valorizzato.
  l10n_it_central_journal_reportlab/readme/CONTRIBUTORS.rst
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3733 [14.0][FIX] Remove unused css classes
  account_vat_period_end_statement/static/src/css/l10n_it_vat_registries.css
Labels: bot is merging ⏳, 14.0

#3854 [16.0] FIX l10n_it_account_stamp for multi-company env
  l10n_it_account_stamp/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#3935 [14.0] [FIX] l10n_it_delivery_note: fix picking view
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳, 14.0, no issue needed

#3916 [14.0] [FIX] l10n_it_fatturapa_import_zip: seleziona le imposte di vendita corrette in caso di fatture attive
  l10n_it_fatturapa_import_zip/wizards/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#2939 [FIX] Pagamenti ritenuta d'acconto duplicati
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, ready to merge, 12.0, bot is merging ⏳

#3934 [FIX] l10n_it_account_stamp error in multi-company env
  l10n_it_account_stamp/models/account_move.py
Labels: approved, bot is merging ⏳, 14.0

#3910 [16.0] [FIX] l10n_it_fatturapa_import_zip: seleziona le imposte di vendita corrette in caso di fatture attive
  l10n_it_fatturapa_import_zip/wizards/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#3852 [FIX] Data dismissione già compilata per cespite da fattura di acquisto
  assets_management/tests/test_assets_management.py
  assets_management/wizard/account_move_manage_asset.py
Labels: bot is merging ⏳, 14.0

#2960 [12.0] FIX l10n_it_reverse_charge in case of refunds
  l10n_it_reverse_charge/models/account_invoice.py
Labels: approved, 12.0, bot is merging ⏳

#3966 [FIX] l10n_it_declaration_of_intent: remove _convert_prepared_anglosaxon_line override
  l10n_it_declaration_of_intent/models/__init__.py
  l10n_it_declaration_of_intent/models/product.py
Labels: bot is merging ⏳

#3963 [16.0] FIX l10n_it_fatturapa_out : avoind currency conversion when not needed.
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: bot is merging ⏳, 16.0, missing issue

#3648 [14.0] [FIX] l10n_it_declaration_of_intent: controllo dichiarazione solo se tipo fattura
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, bot is merging ⏳, 14.0

#3563 [14.0][FIX] l10n_it_declaration_of_intent: separate "in" and "out" declarations in tests
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, bot is merging ⏳, 14.0, missing issue

#3967 [FIX] parziale backport di #3446
  l10n_it_declaration_of_intent/models/account_move.py
Labels: bot is merging ⏳

#3947 [16.0][FIX] l10n_it_declaration_of_intent: remove _convert_prepared_anglosaxon_line override
  l10n_it_declaration_of_intent/models/__init__.py
  l10n_it_declaration_of_intent/models/product.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#3463 [14.0][FW] l10n_it_declaration_of_intent: FW of #2356
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/views/company_view.xml
  l10n_it_fatturapa_out_di/tests/test_fatturapa_xml_validation.py
Labels: bot is merging ⏳, 14.0

#3304 [14.0] [FIX] l10n_it_declaration_of_intent: use currency.compare_amounts()
  l10n_it_declaration_of_intent/i18n/l10n_it_dichiarazione_intento.pot
Labels: bot is merging ⏳, 14.0

#3474 l10n_it_declaration_of_intent - bug in float comparisons
  l10n_it_declaration_of_intent/i18n/l10n_it_dichiarazione_intento.pot
  l10n_it_declaration_of_intent/models/account_move.py
Labels: bot is merging ⏳, 16.0

#3936 [14.0] [IMP] l10n_it_delivery_note: Add setting to make 'Partner ref' required
  l10n_it_delivery_note/models/res_config_settings.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/security/res_groups.xml
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#2957 [14.0][IMP] Implements "Account used for VAT settlement"
  account_vat_period_end_statement/README.rst
  account_vat_period_end_statement/__manifest__.py
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/readme/CONFIGURE.rst
  account_vat_period_end_statement/readme/DESCRIPTION.rst
  account_vat_period_end_statement/static/description/index.html
  account_vat_period_end_statement/views/account_view.xml
Labels: approved, bot is merging ⏳

#3819 [14.0] [FIX] l10n_it_intrastat: change field used for date search
  l10n_it_intrastat_statement/models/intrastat_statement.py
  l10n_it_intrastat_statement/tests/test_intrastat_statement.py
Labels: merged 🎉, 14.0

#3449 [14.0][FIX]l10n_it_declaration_of_intent:Rimozione required per numero e data documento partner
  l10n_it_declaration_of_intent/models/account_move.py
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out_di/tests/data/IT06363391001_00003.xml
Labels: bot is merging ⏳, 14.0

#2943 [14.0] [FIX] Selezione liquidazione IVA precedente
  account_vat_period_end_statement/README.rst
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/readme/CONTRIBUTORS.rst
  account_vat_period_end_statement/tests/test_vat_statement.py
Labels: approved, bot is merging ⏳, 14.0

#2425 [14.0] ADD dn_supplier_number and dn_supplier_date fields updated from ddt_supplier_number and ddt_supplier_date of l10n_it_ddt module
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳, 14.0

#3614 [14.0][IMP] assets_management multicompany
  assets_management/models/asset.py
  assets_management/models/asset_category.py
  assets_management/models/asset_category_depreciation_type.py
  assets_management/models/asset_depreciation.py
  assets_management/models/asset_depreciation_line.py
  assets_management/models/asset_depreciation_line_type.py
  assets_management/models/asset_depreciation_mode.py
  assets_management/models/asset_depreciation_type.py
  assets_management/models/asset_tag.py
  assets_management/security/rules.xml
  assets_management/tests/__init__.py
  assets_management/tests/test_assets_common.py
  assets_management/tests/test_assets_management.py
  assets_management/tests/test_assets_multicompany.py
  assets_management/views/asset.xml
  assets_management/views/asset_category.xml
  assets_management/wizard/account_move_manage_asset.py
  assets_management/wizard/account_move_manage_asset_view.xml
  assets_management/wizard/asset_generate_depreciation.py
  assets_management/wizard/asset_journal_report.py
  assets_management/wizard/asset_journal_report_view.xml
  assets_management/wizard/asset_previsional_report.py
  assets_management/wizard/asset_previsional_report_view.xml
Labels: bot is merging ⏳, 14.0

#3707 [16.0][FIX] l10n_it_withholding_tax: reconcile payments after reset invoice to draft
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#3959 [16.0] [FIX] l10n_it_fatturapa_import_zip correctly imports all XML files in zip
  l10n_it_fatturapa_import_zip/models/attachment.py
  l10n_it_fatturapa_import_zip/readme/DESCRIPTION.rst
  l10n_it_fatturapa_import_zip/tests/data/xml_import.zip
Labels: approved, ready to merge, bot is merging ⏳

#2785 [14.0][FIX] l10n_it_delivery_note: fix partner ddt
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3962 [FIX] l10n_it_delivery_note rimosso script di migrazione per campo non più esistente is_carrier
  l10n_it_delivery_note/migrations/14.0.2.0.0/post-migration.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0, Migration scripts

#3988 [FW][16.0]l10n_it_delivery_note: delivery note company field adjustments
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳

#2673 [14.0][FIX] l10n_it_withholding_tax: reconcile payments after reset invoice to draft
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: bot is merging ⏳, 14.0

#3971 [16.0] IMP l10n_it_vat_registries: ordering option
  l10n_it_vat_registries/models/account_tax_registry.py
  l10n_it_vat_registries/models/vat_registry.py
  l10n_it_vat_registries/report/report_registro_iva.xml
  l10n_it_vat_registries/views/account_tax_registry_view.xml
  l10n_it_vat_registries/wizard/print_registro_iva.py
  l10n_it_vat_registries/wizard/print_registro_iva.xml
Labels: approved, ready to merge, bot is merging ⏳

#3837 [14.0][FIX] l10n_it_ricevute_bancarie: migration script for rules
  l10n_it_ricevute_bancarie/README.rst
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/migrations/14.0.1.8.2/noupdate_changes.xml
  l10n_it_ricevute_bancarie/migrations/14.0.1.8.2/post-migration.py
  l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
  l10n_it_ricevute_bancarie/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳, 14.0, Migration scripts, no issue needed

#3751 [14.0] FIX l10n_it_fatturapa_in: importing refund with negative lines
  l10n_it_fatturapa_in/models/account.py
  l10n_it_fatturapa_in/tests/data/IT02098391200_FPR16.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
Labels: bot is merging ⏳, 14.0

#3882 [14.0][l10n_it_intrastat_statement] Code optimization when generating the statement
  l10n_it_intrastat_statement/models/intrastat_statement.py
Labels: approved, bot is merging ⏳, 14.0

#3980 [FW][16.0]l10n_it_delivery_note_batch: forward-port of https://github.com/OCA/l10n-italy/pull/3821
  l10n_it_delivery_note_batch/README.rst
  l10n_it_delivery_note_batch/__manifest__.py
  l10n_it_delivery_note_batch/models/stock_picking_batch.py
  l10n_it_delivery_note_batch/static/description/index.html
  l10n_it_delivery_note_batch/views/stock_picking_batch_views.xml
Labels: bot is merging ⏳, 16.0

#3859 [14.0] [FIX] l10n_it_delivery_note_base: add migration for model data
  l10n_it_delivery_note_base/migrations/14.0.1.0.1/pre-migrate.py
Labels: bot is merging ⏳, 14.0, Migration scripts, no issue needed

#3903 [14.0] l10n_it_intrastat_statement ricalcola la sequenza dopo la possibile rimozione di righe per rettifiche
  l10n_it_intrastat_statement/models/intrastat_statement.py
Labels: bot is merging ⏳

#3898 [14.0] set date order to intrastat statement l10n_it_intrastat_statement
  l10n_it_intrastat_statement/models/intrastat_statement.py
Labels: bot is merging ⏳, 14.0

#3760 [14.0][FIX] account_vat_period_end_statement order on account.vat.period.end.statement
  account_vat_period_end_statement/models/account.py
Labels: approved, bot is merging ⏳, 14.0

#3865 [FIX] l10n_it_intrastat country destination visible in out refund too
  l10n_it_intrastat/views/account.xml
Labels: bot is merging ⏳, 14.0

#3782 [14.0][FIX] l10n_it_ricevute_bancarie sostituzione caratteri non ammessi
  l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
Labels: bot is merging ⏳, 14.0

#3762 [14.0][FIX] account_vat_period_end_statement multicompany non stampa le imposte
  account_vat_period_end_statement/report/vat_statement.py
Labels: bot is merging ⏳, 14.0

#3987 Speed-up issues backlog processing
  .github/workflows/stale.yml
Labels: approved, bot is merging ⏳

#3847 [14.0] porting l10n_it_fatturapa_out_oss
  l10n_it_fatturapa_out_oss/README.rst
  l10n_it_fatturapa_out_oss/__init__.py
  l10n_it_fatturapa_out_oss/__manifest__.py
  l10n_it_fatturapa_out_oss/data/invoice_it_template.xml
  l10n_it_fatturapa_out_oss/i18n/it.po
  l10n_it_fatturapa_out_oss/i18n/l10n_it_fatturapa_out_oss.pot
  l10n_it_fatturapa_out_oss/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out_oss/readme/DESCRIPTION.rst
  l10n_it_fatturapa_out_oss/static/description/icon.png
  l10n_it_fatturapa_out_oss/static/description/index.html
  l10n_it_fatturapa_out_oss/tests/__init__.py
  l10n_it_fatturapa_out_oss/tests/data/IT06363391001_00001.xml
  l10n_it_fatturapa_out_oss/tests/data/IT06363391001_00002.xml
  l10n_it_fatturapa_out_oss/tests/fatturapa_common.py
  l10n_it_fatturapa_out_oss/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out_oss/wizard/__init__.py
  l10n_it_fatturapa_out_oss/wizard/l10n_eu_oss_wizard.py
  l10n_it_fatturapa_out_oss/wizard/wizard_export_fatturapa.py
  setup/l10n_it_fatturapa_out_oss/odoo/addons/l10n_it_fatturapa_out_oss
  setup/l10n_it_fatturapa_out_oss/setup.py
Labels: migration, bot is merging ⏳, 14.0

#3149 [FIX][l10n_it_split_payment] fix migration script issue https://githu…
  l10n_it_split_payment/migrations/14.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳, 14.0, Migration scripts

#3405 [FIX] l10n_it_fatturapa: restore ACL before https://github.com/OCA/l10n-italy/pull/3335
  l10n_it_fatturapa/security/ir.model.access.csv
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳, 14.0, missing issue

#3945 [14.0][FIX] Usare company_id in fatturapa.attachment.out invece che self.env.company o user's company
  l10n_it_fatturapa_pec/models/sdi.py
  l10n_it_sdi_channel/models/fatturapa_attachment_out.py
Labels: bot is merging ⏳, 14.0, missing issue

#3393 [14.0][FIX] assets_management: includere nella stampa cespiti non ancora ammortizzati
  assets_management/report/asset_journal.py
Labels: bot is merging ⏳, 14.0

#3965 [16.0] FIX l10n_it_intrastat: multi company for account.invoice.intrastat
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/security/rules.xml
Labels: bot is merging ⏳, 16.0, missing issue

#3537 [14.0][REF] l10n_it_central_journal_reportlab: update title like report in "l10n_it_central_journal"
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
Labels: bot is merging ⏳, 14.0, missing issue

#3346 [14.0][FIX] assets_management get only not null dates
  assets_management/wizard/account_move_manage_asset.py
Labels: bot is merging ⏳, 14.0

#3125 [14.0][FIX] assets_management do not create depreciation lines with zero amount
  assets_management/models/asset_depreciation.py
Labels: bot is merging ⏳, 14.0

#3830 [14.0][IMP] l10n_it_central_journal_reportlab add last data info - page and row
  l10n_it_central_journal_reportlab/models/account.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
Labels: bot is merging ⏳, 14.0

#3592 [14.0][FIX] l10n_it_website_sale_fiscalcode: fix fiscalcode check
  l10n_it_website_sale_fiscalcode/controllers/main.py
Labels: approved, bot is merging ⏳, 14.0

#3596 [14.0] FIX l10n_it_split_payment migration in case amount_sp already exists (with odoo enterprise)
  l10n_it_split_payment/migrations/14.0.1.0.0/pre-move_split_amount.py
Labels: bot is merging ⏳, 14.0, missing issue

#4004 [FIX] account_vat_period_end_statement: Evitare anno bisestile
  account_vat_period_end_statement/tests/test_vat_statement.py
Labels: approved, merged 🎉

#3995 [16.0][FIX] l10n_it_delivery_note: always show partner_ref in DN
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳
