Repository OCA/l10n-italy, pull requests merged in 2024-12, with the labels that each got.

#4457 [14.0][IMP] l10n_it_ricevute_bancarie: Add exposure/risk and improve the management of unsolved riba
  l10n_it_ricevute_bancarie/README.rst
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/demo/riba_demo.xml
  l10n_it_ricevute_bancarie/models/account.py
  l10n_it_ricevute_bancarie/models/riba.py
  l10n_it_ricevute_bancarie/models/riba_config.py
  l10n_it_ricevute_bancarie/readme/CONFIGURE.rst
  l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
  l10n_it_ricevute_bancarie/readme/USAGE.rst
  l10n_it_ricevute_bancarie/security/ir.model.access.csv
  l10n_it_ricevute_bancarie/static/description/index.html
  l10n_it_ricevute_bancarie/tests/riba_common.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/account_view.xml
  l10n_it_ricevute_bancarie/views/configuration_view.xml
  l10n_it_ricevute_bancarie/views/riba_detail_view.xml
  l10n_it_ricevute_bancarie/views/riba_view.xml
  l10n_it_ricevute_bancarie/views/wizard_riba_payment_date.xml
  l10n_it_ricevute_bancarie/wizard/__init__.py
  l10n_it_ricevute_bancarie/wizard/wizard_riba_payment_date.py
  l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py
Labels: bot is merging ⏳, 14.0, is porting

#4472 [14.0] FIX l10n_it_vat_settlement_date with l10n_it_vat_statement_communication: VAT comunication must use statement base amounts
  l10n_it_vat_settlement_date/__manifest__.py
  l10n_it_vat_settlement_date/models/__init__.py
  l10n_it_vat_settlement_date/models/comunicazione_liquidazione.py
Labels: approved, bot is merging ⏳, missing issue

#4453 [FIX] [16.0] account_vat_period_end_statement: untranslatable strings
  account_vat_period_end_statement/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#4475 FIX l10n_it_vat_settlement_date with l10n_it_vat_statement_communication: VAT comunication must use statement base amounts
  l10n_it_vat_settlement_date/__manifest__.py
  l10n_it_vat_settlement_date/models/__init__.py
  l10n_it_vat_settlement_date/models/comunicazione_liquidazione.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0, missing issue, is porting

#4493 [14.0][FIX] Ricevute bancarie "Al dopo incasso"
  l10n_it_ricevute_bancarie/README.rst
  l10n_it_ricevute_bancarie/models/riba.py
  l10n_it_ricevute_bancarie/readme/CONFIGURE.rst
  l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
  l10n_it_ricevute_bancarie/static/description/index.html
  l10n_it_ricevute_bancarie/tests/riba_common.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/configuration_view.xml
  l10n_it_ricevute_bancarie/views/riba_view.xml
Labels: approved, bot is merging ⏳, is porting

#4459 [14.0][IMP]l10n_it_ricevute_bancarie: improvements for is_unsolved field
  l10n_it_ricevute_bancarie/models/account.py
  l10n_it_ricevute_bancarie/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#4446 [FIX] Precisione decimale non usata durante l'importazione della fattura elettronica
  l10n_it_fatturapa_in/__init__.py
  l10n_it_fatturapa_in/fields.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR16.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: approved, ready to merge, bot is merging ⏳

#4507 [14.0] [DEL] l10n_it_delivery_note: useless filter
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳, no issue needed

#4506 [16.0] [DEL] l10n_it_delivery_note: useless filter
  l10n_it_delivery_note/views/stock_delivery_note.xml
Labels: approved, bot is merging ⏳, no issue needed

#4402 [MIG] l10n_it_account_stamp: Migrazione a 18.0
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__init__.py
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/data/data.xml
  l10n_it_account_stamp/i18n/it.po
  l10n_it_account_stamp/i18n/l10n_it_account_stamp.pot
  l10n_it_account_stamp/migrations/18.0.1.0.0/noupdate_changes.xml
  l10n_it_account_stamp/migrations/18.0.1.0.0/post-migration.py
  l10n_it_account_stamp/migrations/18.0.1.0.0/pre-migration.py
  l10n_it_account_stamp/models/__init__.py
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/models/company.py
  l10n_it_account_stamp/models/product.py
  l10n_it_account_stamp/pyproject.toml
  l10n_it_account_stamp/readme/CONFIGURE.md
  l10n_it_account_stamp/readme/CONTRIBUTORS.md
  l10n_it_account_stamp/readme/DESCRIPTION.md
  l10n_it_account_stamp/readme/ROADMAP.md
  l10n_it_account_stamp/readme/USAGE.md
  l10n_it_account_stamp/static/description/icon.png
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/tests/__init__.py
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
  l10n_it_account_stamp/views/account_move_report.xml
  l10n_it_account_stamp/views/account_move_view.xml
  l10n_it_account_stamp/views/company_view.xml
  l10n_it_account_stamp/views/product_view.xml
Labels: approved, migration, ready to merge, bot is merging ⏳, 18.0

#4496 [FIX] l10n_it_account: add original t-if attribute
  l10n_it_account/reports/account_reports_view.xml
Labels: bot is merging ⏳

#4474 [16.0] FIX l10n_it_vat_settlement_date: avoid to copy l10n_it_vat_settlement_date
  l10n_it_vat_settlement_date/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳, missing issue, is porting

#4321 [MIG] l10n_it_accompanying_invoice: Migration to 16.0
  l10n_it_accompanying_invoice/README.rst
  l10n_it_accompanying_invoice/__init__.py
  l10n_it_accompanying_invoice/__manifest__.py
  l10n_it_accompanying_invoice/hooks.py
  l10n_it_accompanying_invoice/i18n/it.po
  l10n_it_accompanying_invoice/models/__init__.py
  l10n_it_accompanying_invoice/models/account_move.py
  l10n_it_accompanying_invoice/models/sale_order.py
  l10n_it_accompanying_invoice/pyproject.toml
  l10n_it_accompanying_invoice/readme/CONTRIBUTORS.md
  l10n_it_accompanying_invoice/readme/DESCRIPTION.md
  l10n_it_accompanying_invoice/readme/ROADMAP.md
  l10n_it_accompanying_invoice/readme/USAGE.md
  l10n_it_accompanying_invoice/readme/migrations/16.0.1.0.1/post-migration.py
  l10n_it_accompanying_invoice/readme/migrations/16.0.1.0.1/pre-migrate.py
  l10n_it_accompanying_invoice/static/description/icon.png
  l10n_it_accompanying_invoice/static/description/index.html
  l10n_it_accompanying_invoice/tests/__init__.py
  l10n_it_accompanying_invoice/tests/test_account_move.py
  l10n_it_accompanying_invoice/tests/test_report.py
  l10n_it_accompanying_invoice/tests/test_sale_order.py
  l10n_it_accompanying_invoice/views/account.xml
  l10n_it_accompanying_invoice/views/report_invoice.xml
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/mixins/__init__.py
  l10n_it_delivery_note/mixins/delivery_mixin.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/readme/CONTRIBUTORS.md
  l10n_it_delivery_note/report/delivery_data.xml
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/static/description/index.html
Labels: approved, migration, ready to merge, bot is merging ⏳, 16.0
