Repository OCA/l10n-italy, pull requests merged in 2024-03, with the labels that each got.

#2520 [14.0][MIG] l10n_it_website_portal_fatturapa
  l10n_it_website_portal_fatturapa/README.rst
  l10n_it_website_portal_fatturapa/__init__.py
  l10n_it_website_portal_fatturapa/__manifest__.py
  l10n_it_website_portal_fatturapa/controllers/__init__.py
  l10n_it_website_portal_fatturapa/controllers/main.py
  l10n_it_website_portal_fatturapa/i18n/it.po
  l10n_it_website_portal_fatturapa/i18n/l10n_it_website_portal_fatturapa.pot
  l10n_it_website_portal_fatturapa/readme/DESCRIPTION.rst
  l10n_it_website_portal_fatturapa/readme/ROADMAP.rst
  l10n_it_website_portal_fatturapa/static/description/icon.png
  l10n_it_website_portal_fatturapa/static/description/index.html
  l10n_it_website_portal_fatturapa/static/src/js/l10n_it_website_portal_fatturapa.js
  l10n_it_website_portal_fatturapa/views/l10n_it_website_portal_fatturapa_templates.xml
  setup/l10n_it_website_portal_fatturapa/odoo/addons/l10n_it_website_portal_fatturapa
  setup/l10n_it_website_portal_fatturapa/setup.py
Labels: migration, bot is merging ⏳, 14.0

#3989 [14.0][FIX] l10n_it_delivery_note shipping address
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/readme/CONTRIBUTORS.rst
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/wizard/delivery_note_base.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
Labels: bot is merging ⏳

#3891 [16.0][l10n_it_fatturapa] Add FoglioStileSouthTyrol-bilingue.xsl as alternative stylesheet for electronic invoices preview
  .pre-commit-config.yaml
  l10n_it_fatturapa/data/FoglioStileSouthTyrol-bilingue.xsl
  l10n_it_fatturapa/models/company.py
Labels: approved, bot is merging ⏳, 16.0

#4006 [PORT] #2412 to 14.0 l10n_it_declaration_of_intent
  l10n_it_declaration_of_intent/models/account_move.py
Labels: approved, merged 🎉

#4019 [FIX][l10n_it_reverse_charge] fix error when supplier invoice is anot…
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#4015 [REF] assets_management: Le righe di ammortamento si aggiornano correttamente
  assets_management/views/asset.xml
Labels: bot is merging ⏳, 14.0, no issue needed

#3724 [12.0] [IMP] l10n_it_fiscalcode: add codicefiscale.isvalid()
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fiscalcode/model/res_partner.py
  l10n_it_fiscalcode/tests/test_fiscalcode.py
Labels: 12.0, bot is merging ⏳

#4024 [IMP] l10n_it_delivery_note: prevent dn creation
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/models/__init__.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/models/stock_picking_type.py
  l10n_it_delivery_note/readme/CONFIGURE.rst
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/views/stock_picking_type.xml
Labels: approved, bot is merging ⏳

#4022 [FIX] l10n_it_vat_registries: supplier refund sign
  l10n_it_vat_registries/models/vat_registry.py
Labels: approved, bot is merging ⏳

#4046 [14.0] [FIX] assets_management: missing rule migration script
  assets_management/README.rst
  assets_management/__manifest__.py
  assets_management/migrations/14.0.1.4.4/noupdate_changes.xml
  assets_management/migrations/14.0.1.4.4/post-migration.py
  assets_management/static/description/index.html
Labels: approved, bot is merging ⏳, 14.0, Migration scripts

#4037 [14.0] Fix association between lines and related docs
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00017.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#4052 [14.0] [FIX] l10n_it_delivery_note: error in sequence name generation
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳, missing issue

#4016 [16.0] Fix association between lines and related docs
  l10n_it_fatturapa/models/account.py
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/tests/data/IT06363391001_00017.xml
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#4008 [FW] l10n_it_delivery_note: multipli fw-ports e il loro adattamento
  l10n_it_delivery_note/README.rst
  l10n_it_delivery_note/__init__.py
  l10n_it_delivery_note/__manifest__.py
  l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
  l10n_it_delivery_note/controllers/__init__.py
  l10n_it_delivery_note/controllers/portal.py
  l10n_it_delivery_note/demo/delivery_carrier_demo.xml
  l10n_it_delivery_note/demo/res_partner_demo.xml
  l10n_it_delivery_note/migrations/14.0.3.0.0/post-migrate.py
  l10n_it_delivery_note/models/__init__.py
  l10n_it_delivery_note/models/account_invoice.py
  l10n_it_delivery_note/models/account_invoice_line.py
  l10n_it_delivery_note/models/res_company.py
  l10n_it_delivery_note/models/res_config_settings.py
  l10n_it_delivery_note/models/res_partner.py
  l10n_it_delivery_note/models/sale_order.py
  l10n_it_delivery_note/models/stock_delivery_note.py
  l10n_it_delivery_note/models/stock_delivery_note_line.py
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/readme/CONFIGURE.md
  l10n_it_delivery_note/readme/CONTRIBUTORS.md
  l10n_it_delivery_note/readme/USAGE.md
  l10n_it_delivery_note/report/report_delivery_note.xml
  l10n_it_delivery_note/security/ir.model.access.csv
  l10n_it_delivery_note/security/ir_rule.xml
  l10n_it_delivery_note/security/res_groups.xml
  l10n_it_delivery_note/static/description/index.html
  l10n_it_delivery_note/static/src/js/stock_delivery_note_portal.js
  l10n_it_delivery_note/tests/__init__.py
  l10n_it_delivery_note/tests/delivery_note_common.py
  l10n_it_delivery_note/tests/test_stock_delivery_note.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_portal.py
  l10n_it_delivery_note/tests/test_stock_delivery_note_sequence.py
  l10n_it_delivery_note/views/assets.xml
  l10n_it_delivery_note/views/portal_my_delivery_notes.xml
  l10n_it_delivery_note/views/portal_templates.xml
  l10n_it_delivery_note/views/res_config_settings.xml
  l10n_it_delivery_note/views/res_partner.xml
  l10n_it_delivery_note/views/stock_delivery_note.xml
  l10n_it_delivery_note/views/stock_picking.xml
  l10n_it_delivery_note/wizard/__init__.py
  l10n_it_delivery_note/wizard/delivery_note_base.py
  l10n_it_delivery_note/wizard/delivery_note_confirm.py
  l10n_it_delivery_note/wizard/delivery_note_confirm.xml
  l10n_it_delivery_note/wizard/delivery_note_create.py
  l10n_it_delivery_note/wizard/delivery_note_invoice.py
  l10n_it_delivery_note/wizard/delivery_note_invoice.xml
  l10n_it_delivery_note/wizard/delivery_note_select.py
  l10n_it_delivery_note/wizard/delivery_note_select.xml
Labels: approved, bot is merging ⏳

#4061 [14.0] [FIX] l10n_it_intrastat: compute weight in case of variants
  l10n_it_intrastat/models/account.py
Labels: approved, bot is merging ⏳

#3769 [14.0] [FIX] l10n_it_fatturapa_in_rc: flag RC in importazione e-fattura con raggruppamento per Aliquota
  l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳, 14.0

#4059 Update repo template
  .copier-answers.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#4045 [FIX] l10n_it_fatturapa: remove pdf conversion of XML preview
  l10n_it_fatturapa/controllers/main.py
Labels: approved, bot is merging ⏳

#4066 [14.0][REF] l10n_it_delivery_note: change nature field and add digits='Product Price'
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#4067 [16.0][REF] l10n_it_delivery_note: change nature field and add digits='Product Price'
  l10n_it_delivery_note/models/stock_delivery_note_line.py
Labels: approved, bot is merging ⏳

#4049 [14.0] [FIX] l10n_it_fatturapa_import_zip: avoid VAT check
  l10n_it_fatturapa_import_zip/models/attachment.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0, missing issue

#2295 [14.0] REF removing cee_type
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/report/vat_statement.py
  l10n_it_account/models/account_tax.py
  l10n_it_vat_registries/models/vat_registry.py
  l10n_it_vat_registries/views/account_view.xml
Labels: bot is merging ⏳, 14.0, missing issue

#4069 [14.0] [FIX] l10n_it_delivery_note: use recipient language
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, ready to merge, bot is merging ⏳

#4076 [FIX] l10n_it_fiscalcode - Cambiando tipologia del partner non viene eseguito il controllo del CF
  l10n_it_fiscalcode/README.rst
  l10n_it_fiscalcode/model/res_partner.py
  l10n_it_fiscalcode/readme/CONTRIBUTORS.md
  l10n_it_fiscalcode/static/description/index.html
  l10n_it_fiscalcode/tests/test_fiscalcode.py
Labels: approved, bot is merging ⏳

#4058 [REF] account_vat_period_end_statement: Ripristino contributor
  account_vat_period_end_statement/readme/CONTRIBUTORS.md
Labels: bot is merging ⏳, no issue needed
