Repository OCA/l10n-italy, pull requests merged in 2024-10, with the labels that each got.

#4381 [fix]l10n_it_fatturapa_out risuzione problema fattura con anticipo
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: approved, bot is merging ⏳

#4352 [14.0][MIG] l10n_it_withholding_tax_payment_order : Migration to 14.0
  l10n_it_withholding_tax_payment_order/README.rst
  l10n_it_withholding_tax_payment_order/__init__.py
  l10n_it_withholding_tax_payment_order/__manifest__.py
  l10n_it_withholding_tax_payment_order/i18n/l10n_it_withholding_tax_payment_order.pot
  l10n_it_withholding_tax_payment_order/models/__init__.py
  l10n_it_withholding_tax_payment_order/models/account_move_line.py
  l10n_it_withholding_tax_payment_order/readme/CONTRIBUTORS.md
  l10n_it_withholding_tax_payment_order/readme/DESCRIPTION.md
  l10n_it_withholding_tax_payment_order/static/description/icon.png
  l10n_it_withholding_tax_payment_order/static/description/index.html
  setup/l10n_it_withholding_tax_payment_order/odoo/addons/l10n_it_withholding_tax_payment_order
  setup/l10n_it_withholding_tax_payment_order/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#4383 [IMP] l10n_it_riba: modificare data pagamento distinte
  l10n_it_riba/README.rst
  l10n_it_riba/__manifest__.py
  l10n_it_riba/models/riba.py
  l10n_it_riba/readme/USAGE.md
  l10n_it_riba/security/ir.model.access.csv
  l10n_it_riba/static/description/index.html
  l10n_it_riba/tests/riba_common.py
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/views/riba_view.xml
  l10n_it_riba/views/wizard_due_date_settlement.xml
  l10n_it_riba/views/wizard_past_due.xml
  l10n_it_riba/wizard/__init__.py
  l10n_it_riba/wizard/wizard_due_date_settlement.py
  l10n_it_riba/wizard/wizard_past_due.py
  l10n_it_riba/wizard/wizard_riba_multiple_payment.py
  l10n_it_riba/wizard/wizard_riba_multiple_payment_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#4071 [IMP] Calcolo ammortamenti mensili per simulazione bilanci
  l10n_it_asset_management/README.rst
  l10n_it_asset_management/__manifest__.py
  l10n_it_asset_management/data/asset_data.xml
  l10n_it_asset_management/migrations/16.0.1.1.0/pre-migrate.py
  l10n_it_asset_management/models/account_fiscal_year.py
  l10n_it_asset_management/models/asset_depreciation.py
  l10n_it_asset_management/models/asset_depreciation_line.py
  l10n_it_asset_management/models/asset_depreciation_mode_line.py
  l10n_it_asset_management/static/description/index.html
  l10n_it_asset_management/tests/test_assets_management.py
  l10n_it_asset_management/views/asset_depreciation_mode.xml
  l10n_it_asset_management/wizard/asset_generate_depreciation.py
  l10n_it_asset_management/wizard/asset_generate_depreciation_view.xml
Labels: approved, ready to merge, bot is merging ⏳, needs technical review

#4154 [FIX] add a warning in l10n_it_intrastat_statement when there are invoices in draft or cancel state
  l10n_it_intrastat_statement/models/__init__.py
  l10n_it_intrastat_statement/models/account.py
  l10n_it_intrastat_statement/models/intrastat_statement.py
Labels: approved, bot is merging ⏳, 14.0, stale

#3808 [FIX] [l10n_it_fatturapa_in] - Errata importazione XML
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/IT08973230967_6zZcm.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳, needs technical review

#4376 [14.0][IMP] l10n_it_vat_registries
  l10n_it_vat_registries/models/account_tax_registry.py
  l10n_it_vat_registries/models/vat_registry.py
  l10n_it_vat_registries/report/report_registro_iva.xml
  l10n_it_vat_registries/views/account_tax_registry_view.xml
  l10n_it_vat_registries/wizard/print_registro_iva.py
  l10n_it_vat_registries/wizard/print_registro_iva.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#4400 [16.0][FIX] l10n_it_central_journal_reportlab: escape Paragraph content
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
Labels: bot is merging ⏳

#4409 Update copier template
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  eslint.config.cjs
  prettier.config.cjs
Labels: bot is merging ⏳

#4147 [FIX] Ritenute: Nota di credito non mantiene la ritenuta e genera movimenti
  l10n_it_withholding_tax/README.rst
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax/static/description/index.html
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#4339 [FIX] DISMISSIONE PARZIALE CON RILEVAZIONE MINUSVALENZA: valore residuo dentro al cespite diverso dal valore residuo sulla stampa del registro
  l10n_it_asset_management/models/asset_depreciation_line.py
  l10n_it_asset_management/tests/test_assets_management.py
Labels: approved, ready to merge, bot is merging ⏳

#4300 [16.0][IMP] l10n_it_fatturapa_import_zip: import only xml + enable customer xml import + manage payment for customer invoice + set debit account for customer invoice
  l10n_it_fatturapa_import_zip/models/attachment.py
  l10n_it_fatturapa_import_zip/views/attachment_views.xml
  l10n_it_fatturapa_import_zip/wizards/wizard_import_fatturapa.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: bot is merging ⏳, 16.0

#4166 [IMP] Specificare un conto nell'ammortamento del cespite diverso dal conto nella categoria
  l10n_it_asset_management/models/asset_depreciation.py
  l10n_it_asset_management/models/asset_depreciation_line.py
  l10n_it_asset_management/tests/__init__.py
  l10n_it_asset_management/tests/common.py
  l10n_it_asset_management/tests/test_asset_depreciation.py
  l10n_it_asset_management/tests/test_assets_management.py
  l10n_it_asset_management/views/asset_depreciation.xml
  l10n_it_asset_management/wizard/account_move_manage_asset.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#4219 [14.0][FIX][l10n_it_fatturapa_in] do not fail import of XML e-invoice on missing/wrong bank account information
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#4367 [14.0][MIG] l10n_it_sct_cbi
  l10n_it_sct_cbi/README.rst
  l10n_it_sct_cbi/__init__.py
  l10n_it_sct_cbi/__manifest__.py
  l10n_it_sct_cbi/data/account_payment_method.xml
  l10n_it_sct_cbi/data/standards/CBIBdyCrossBorderPaymentRequest.00.01.01.xsd
  l10n_it_sct_cbi/data/standards/CBIBdyPaymentRequest.00.04.01.xsd
  l10n_it_sct_cbi/data/standards/CBICrossBorderPaymentRequestLogMsg.00.01.01.xsd
  l10n_it_sct_cbi/data/standards/CBICrossBorderPaymentRequestPhyMsg.00.01.01.xsd
  l10n_it_sct_cbi/data/standards/CBIHdrSrv.001.07.xsd
  l10n_it_sct_cbi/data/standards/CBIHdrTrt.001.07.xsd
  l10n_it_sct_cbi/data/standards/CBIPaymentRequest.00.04.01.xsd
  l10n_it_sct_cbi/data/standards/CBIPaymentRequestMsg.00.04.01.xsd
  l10n_it_sct_cbi/data/standards/CBISgnInf.001.04.xsd
  l10n_it_sct_cbi/i18n/it.po
  l10n_it_sct_cbi/i18n/l10n_it_sct_cbi.pot
  l10n_it_sct_cbi/i18n/sl.po
  l10n_it_sct_cbi/models/__init__.py
  l10n_it_sct_cbi/models/account_payment_method.py
  l10n_it_sct_cbi/models/account_payment_order.py
  l10n_it_sct_cbi/readme/CONFIGURE.md
  l10n_it_sct_cbi/readme/CONTRIBUTORS.md
  l10n_it_sct_cbi/readme/DESCRIPTION.md
  l10n_it_sct_cbi/readme/USAGE.md
  l10n_it_sct_cbi/static/company_setting.png
  l10n_it_sct_cbi/static/description/icon.png
  l10n_it_sct_cbi/static/description/index.html
  l10n_it_sct_cbi/static/generate_payment.png
  l10n_it_sct_cbi/static/make_payment_download.png
  l10n_it_sct_cbi/static/order_payment.png
  l10n_it_sct_cbi/static/payment_mode1.png
  l10n_it_sct_cbi/static/payment_mode2.png
  l10n_it_sct_cbi/tests/__init__.py
  l10n_it_sct_cbi/tests/test_generate_file.py
  setup/l10n_it_sct_cbi/odoo/addons/l10n_it_sct_cbi
  setup/l10n_it_sct_cbi/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#4418 [FIX] l10n_it_withholding_tax: pagando più fatture il rimane un amount_residual pari al valore delle ritenute
  l10n_it_withholding_tax/models/account.py
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/tests/test_withholding_tax.py
  l10n_it_withholding_tax/views/withholding_tax.xml
  l10n_it_withholding_tax/wizards/account_payment_register.py
Labels: approved, bot is merging ⏳

#4417 [16.0][FIX]l10n_it_intrastat_statement: adapt report format to correct version
  l10n_it_intrastat_statement/report/reports.xml
Labels: approved, bot is merging ⏳, 16.0, missing issue

#4416 [FIX] l10n_it_delivery_note: fix wrong partner in DdT in easy way
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, bot is merging ⏳, 16.0, missing issue

#4426 [16.0] FIX l10n_it_fatturapa_in when getting tax from product
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳, 16.0, missing issue

#4420 [FW][FIX] l10n_it_fatturapa_pec: Receive base64 attachments OCA#2915
  l10n_it_fatturapa_pec/models/mail_thread.py
  l10n_it_fatturapa_pec/tests/data/POSTA CERTIFICATA: Invio File 7339338 (base64).txt
  l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
  l10n_it_sdi_channel/models/sdi.py
Labels: approved, bot is merging ⏳
