Repository OCA/l10n-italy, pull requests merged in 2025-09, with the labels that each got.

#4877 [FIX] Conversione errata dettagli fattura negativi in fase di importazione fattura elettronica
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR07_bill.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳, is porting

#4749 [18.0][ADD]l10n_it_edi_related_document: l10n_it_edi extension for multiple related document type management
  l10n_it_edi_related_document/README.rst
  l10n_it_edi_related_document/__init__.py
  l10n_it_edi_related_document/__manifest__.py
  l10n_it_edi_related_document/data/invoice_it_template.xml
  l10n_it_edi_related_document/models/__init__.py
  l10n_it_edi_related_document/models/account_move.py
  l10n_it_edi_related_document/models/account_move_line.py
  l10n_it_edi_related_document/pyproject.toml
  l10n_it_edi_related_document/readme/CONTRIBUTORS.md
  l10n_it_edi_related_document/readme/DESCRIPTION.md
  l10n_it_edi_related_document/security/ir.model.access.csv
  l10n_it_edi_related_document/static/description/index.html
  l10n_it_edi_related_document/tests/__init__.py
  l10n_it_edi_related_document/tests/import_xmls/IT01234567888_FPR01_02.xml
  l10n_it_edi_related_document/tests/test_import_xml.py
  l10n_it_edi_related_document/views/account_move_related_documents.xml
  l10n_it_edi_related_document/views/l10n_it_views.xml
  l10n_it_edi_related_document/views/related_document_views.xml
Labels: approved, bot is merging ⏳, needs functional review

#4762 [18.0][IMP] l10n_it_vat_registries: add XLSX report
  l10n_it_vat_registries/README.rst
  l10n_it_vat_registries/__manifest__.py
  l10n_it_vat_registries/report/reports.xml
  l10n_it_vat_registries/static/description/index.html
  l10n_it_vat_registries/tests/test_registry.py
  l10n_it_vat_registries/wizard/__init__.py
  l10n_it_vat_registries/wizard/print_registro_iva.py
  l10n_it_vat_registries/wizard/print_registro_iva.xml
  l10n_it_vat_registries/wizard/report_registro_iva_xlsx.py
  l10n_it_vat_settlement_date/__init__.py
  l10n_it_vat_settlement_date/wizard/__init__.py
  l10n_it_vat_settlement_date/wizard/report_registro_iva_xlsx.py
Labels: bot is merging ⏳, 18.0, is porting

#4156 [16.0] [FIX] l10n_it_fatturapa_out: attach report to a xml invoice pops an error on "report_print_menu" field
  l10n_it_fatturapa_out/__manifest__.py
  l10n_it_fatturapa_out/migrations/16.0.1.6.0/pre-migrate.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa_view.xml
Labels: needs fixing, approved, bot is merging ⏳, 16.0

#4581 [16.0] [FIX] l10n_it_withholding_tax: amount_net_pay_residual calculated incorrectly due to the mixed use of fields
  l10n_it_withholding_tax/models/account.py
Labels: approved, bot is merging ⏳
