Repository OCA/l10n-italy, pull requests merged in 2025-01, with the labels that each got.

#4298 [16.0][FIX] accounting menu not translatable
  l10n_it_account/__init__.py
  l10n_it_account/models/__init__.py
  l10n_it_account/models/res_lang.py
  l10n_it_account/views/account_menuitem.xml
  l10n_it_account/wizards/__init__.py
  l10n_it_account/wizards/base_language_install.py
Labels: approved, bot is merging ⏳

#4210 [16.0][IMP] l10n_it_declaration_of_intent: adding force_declaration_of_intent_id in burger menu
  l10n_it_declaration_of_intent/views/account_invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#4209 [16.0][IMP] l10n_it_fatturapa_in_purchase: adding purchase_line_id in burger menu
  l10n_it_fatturapa_in_purchase/README.rst
  l10n_it_fatturapa_in_purchase/__manifest__.py
  l10n_it_fatturapa_in_purchase/static/description/index.html
  l10n_it_fatturapa_in_purchase/views/invoice_view.xml
Labels: approved, bot is merging ⏳, stale

#4208 [16.0][IMP] l10n_it_fatturapa_in: adding admin_ref in burger menu
  l10n_it_fatturapa_in/README.rst
  l10n_it_fatturapa_in/__manifest__.py
  l10n_it_fatturapa_in/static/description/index.html
  l10n_it_fatturapa_in/views/account_view.xml
Labels: approved, bot is merging ⏳, stale

#4523 [REF] l10n_it_fatturapa_pec: refactoring clean_messages_dict and avoid error if key not exist
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: approved, bot is merging ⏳, 16.0

#4525 [REF] l10n_it_fatturapa_pec: refactoring clean_messages_dict and avoid error if key not exist
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: bot is merging ⏳, 14.0, is porting

#4509 [14.0] [IMP] l10n_it_fatturapa_in: add self invoice type TD22
  l10n_it_fatturapa_in/models/attachment.py
Labels: bot is merging ⏳, 14.0, is porting

#4526 [16.0][FIX] l10n_it_delivery_note: create delivery note only after quantity done has been set
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, bot is merging ⏳

#4412 [FIX] ricevute bancarie ASCII instead UTF-8
  l10n_it_riba/wizard/wizard_riba_file_export.py
Labels: approved, bot is merging ⏳, is porting

#4452 [FIX]l10n_it_intrastat_statement: adapt report format to correct version
  l10n_it_intrastat_statement/report/reports.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0, needs functional review, is porting

#4543 [FIX] l10n_it_delivery_note: name generation
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#4548 [16.0] l10n_it_delivery_note: ADD dn_supplier_number and dn_supplier_date fields in stock.picking
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳, needs functional review, 16.0

#4544 [FIX] account_vat_period_end_statement: untranslatable strings
  account_vat_period_end_statement/models/account.py
Labels: approved, bot is merging ⏳

#4502 [FIX] REF l10n_it_withholding_tax withholding.tax display_name with cleaner implementation
  l10n_it_withholding_tax/README.rst
  l10n_it_withholding_tax/models/withholding_tax.py
  l10n_it_withholding_tax/readme/CONTRIBUTORS.md
  l10n_it_withholding_tax/static/description/index.html
  l10n_it_withholding_tax/tests/test_withholding_tax.py
Labels: bot is merging ⏳, is porting

#4245 [14.0][ADD] l10n_it_intrastat: added company rule on intrastat line
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/security/intrastat_rules.xml
  l10n_it_intrastat/views/account.xml
Labels: approved, bot is merging ⏳, 14.0

#4497 [16.0] l10n_it_intrastat_statement: set date order to intrastat statement
  l10n_it_intrastat_statement/models/intrastat_statement.py
Labels: approved, ready to merge, bot is merging ⏳, is porting

#4537 [14.0][FIX] l10n_it_central_journal_reportlab: escape Paragraph content
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
Labels: approved, bot is merging ⏳

#4541 [14.0][IMP] l10n_it_account showing which accounts have wrong sign
  l10n_it_account/models/account_account.py
  l10n_it_account/models/account_group.py
Labels: approved, bot is merging ⏳, 14.0, needs technical review, is porting

#4177 [14.0] FIX l10n_it_fatturapa_out and l10n_it_fatturapa_out_rc avoiding to convert to EUR tax_base_amount as it is already in company currency (currency_field='company_currency_id')
  l10n_it_fatturapa_out/data/invoice_it_template.xml
  l10n_it_fatturapa_out/wizard/efattura.py
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
  l10n_it_fatturapa_out_oss/data/invoice_it_template.xml
  l10n_it_fatturapa_out_rc/views/invoice_it_template.xml
Labels: approved, bot is merging ⏳

#4524 [16.0][IMP] l10n_it_fatturapa_out: Improved RegimeFiscale tag for xml
  l10n_it_fatturapa_out/data/invoice_it_template.xml
Labels: needs fixing, approved, bot is merging ⏳

#4256 [14.0][IMP] add ability to set intrastat only for in_ or out_ invoices in l10n_it_intrastat
  l10n_it_intrastat/README.rst
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/migrations/14.0.1.6.1/pre-migrate.py
  l10n_it_intrastat/models/account.py
  l10n_it_intrastat/readme/CONFIGURE.rst
  l10n_it_intrastat/readme/CONTRIBUTORS.rst
  l10n_it_intrastat/static/description/index.html
  l10n_it_intrastat/tests/test_intrastat.py
  l10n_it_intrastat/views/account.xml
Labels: approved, ready to merge, bot is merging ⏳

#4531 [16.0] [FIX] l10n_it_reverse_charge: utilizzando il conto analitico su fattura che genera RC lo stesso viene indicato sia sulla fattura che su autofattura passiva generando un doppio movimento in analitica
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳, 16.0

#4455 [FIX] l10n_it_ricevute_bancarie: remove account and journal domain
  l10n_it_ricevute_bancarie/models/riba_config.py
  l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py
Labels: approved, bot is merging ⏳, 14.0, is porting

#4268 [14.0] l10n_it_declaration_of_intent: se elimino fattura già confermata non aggiorna plafond
  l10n_it_declaration_of_intent/__manifest__.py
  l10n_it_declaration_of_intent/demo/declaration_of_intent.xml
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/static/description/index.html
  l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
Labels: approved, ready to merge, bot is merging ⏳, is porting

#4265 [14.0][FIX]assets_management: Company and page number out of page
  assets_management/report/layout.xml
Labels: bot is merging ⏳, is porting

#4540 [FIX] l10n_it_intrastat_statement: progressive_to_modify_id is not used
  l10n_it_intrastat_statement/models/intrastat_statement_purchase_section4.py
Labels: approved, bot is merging ⏳

#4500 [16.0][ADD] l10n_it_intrastat: added company rule on intrastat line
  l10n_it_intrastat/__manifest__.py
  l10n_it_intrastat/security/intrastat_rules.xml
  l10n_it_intrastat/views/account.xml
Labels: approved, ready to merge, bot is merging ⏳

#3811 [IMP] Impedire la creazione della fattura elettronica per i corrispettivi + abilita esportazione FE per note di credito
  l10n_it_fatturapa_out/views/account_view.xml
Labels: approved, ready to merge, bot is merging ⏳, needs functional review, is porting

#4572 [14.0] [IMP] l10n_it_fatturapa_in: avoid adding rounding lines when import level is not maximum
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#4571 [16.0] [IMP] l10n_it_fatturapa_in: porting of v. 14.0 fix to avoid adding rounding lines when import level is not maximum
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, bot is merging ⏳

#4534 [FIX] l10n_it_delivery_note: fix quantity done
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#4552 [REF] l10n_it_central_journal_reportlab: update title like report in l10n_it_central_journal
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
Labels: bot is merging ⏳

#4591 [FIX] l10n_it_delivery_note: fix delivery note invoice assignment by using invoice IDs
  l10n_it_delivery_note/models/stock_picking.py
  l10n_it_delivery_note/wizard/delivery_note_create.py
  l10n_it_delivery_note/wizard/delivery_note_select.py
Labels: approved, bot is merging ⏳

#4527 [16.0] [FIX] l10n_it_delivery_note: fix select exist DN
  l10n_it_delivery_note/views/stock_delivery_note.xml
  l10n_it_delivery_note/wizard/delivery_note_select.py
Labels: approved, bot is merging ⏳, missing issue
