Repository OCA/l10n-italy, pull requests merged in 2025-04, with the labels that each got.

#4603 [16.0] [FIX] l10n_it_account_stamp: stamp lines migration
  l10n_it_account_stamp/migrations/16.0.1.0.0/pre-migration.py
Labels: approved, ready to merge, bot is merging ⏳, hotfix, 16.0, Migration scripts, no issue needed

#4685 [14.0][IMP] l10n_it_account_stamp: backportings
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/readme/CONTRIBUTORS.rst
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
  l10n_it_account_stamp/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#4654 [16.0] [FIX] l10n_it_riba: fix tot_amount rounding in slip report
  l10n_it_riba/views/slip_report.xml
Labels: bot is merging ⏳, 16.0, no issue needed

#4656 [14.0] [FIX] l10n_it_riba: fix tot_amount rounding in slip report
  l10n_it_ricevute_bancarie/views/distinta_report.xml
Labels: bot is merging ⏳, 14.0, no issue needed

#3661 [16.0][IMP] l10n_it_financial_statements_report: add company header
  l10n_it_financial_statements_report/README.rst
  l10n_it_financial_statements_report/readme/USAGE.md
  l10n_it_financial_statements_report/report/templates/financial_statements_report.xml
  l10n_it_financial_statements_report/static/description/index.html
Labels: needs fixing, bot is merging ⏳, 16.0

#4670 [16.0][IMP] l10n_it_declaration_of_intent: add chatter
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/views/declaration_of_intent_view.xml
Labels: approved, bot is merging ⏳, 16.0

#4696 [16.0] REF removing cee_type
  account_vat_period_end_statement/models/account.py
  account_vat_period_end_statement/report/vat_statement.py
  l10n_it_account/models/account_tax.py
  l10n_it_vat_registries/models/vat_registry.py
  l10n_it_vat_registries/views/account_view.xml
Labels: bot is merging ⏳

#4390 [IMP] l10n_it_fatturapa_out: errore più verboso nel caso di presenza di caratteri non validi
  l10n_it_fatturapa_out/README.rst
  l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
  l10n_it_fatturapa_out/static/description/index.html
  l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
  l10n_it_fatturapa_out/wizard/efattura.py
Labels: approved, bot is merging ⏳, 14.0, stale

#4684 [14.0][FIX] l10n_it_fatturapa_out_rc: riferimenti duplicati in "Documenti correlati"
  l10n_it_fatturapa_out_rc/models/account_move.py
Labels: approved, bot is merging ⏳

#4204 [16.0][IMP] account_vat_period_end_statement: Updated "Total Statement" label to specify if total is credit or debit
  account_vat_period_end_statement/views/report_vatperiodendstatement.xml
Labels: bot is merging ⏳

#4704 [14.0][FIX] l10n_it_reverse_charge: original invoice date in RC
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#4065 [16.0] [FIX] l10n_it_reverse_charge: write supplier_invoice_vals in generate_supplier_self_invoice
  l10n_it_reverse_charge/models/account_move.py
Labels: bot is merging ⏳, missing issue

#4665 [18.0] [MIG] l10n_it_appointment_code
  l10n_it_appointment_code/README.rst
  l10n_it_appointment_code/__init__.py
  l10n_it_appointment_code/__manifest__.py
  l10n_it_appointment_code/data/appointment_code_data.xml
  l10n_it_appointment_code/i18n/it.po
  l10n_it_appointment_code/i18n/l10n_it_appointment_code.pot
  l10n_it_appointment_code/models/__init__.py
  l10n_it_appointment_code/models/appointment_code.py
  l10n_it_appointment_code/pyproject.toml
  l10n_it_appointment_code/readme/CONFIGURE.md
  l10n_it_appointment_code/readme/CONTRIBUTORS.md
  l10n_it_appointment_code/readme/DESCRIPTION.md
  l10n_it_appointment_code/readme/USAGE.md
  l10n_it_appointment_code/security/ir.model.access.csv
  l10n_it_appointment_code/static/description/icon.png
  l10n_it_appointment_code/static/description/index.html
  l10n_it_appointment_code/views/appointment_code_view.xml
Labels: bot is merging ⏳

#4712 [18.0][FIX] l10n_it_delivery_note: do not generate DN number twice
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: bot is merging ⏳

#4709 [14.0][FIX] l10n_it_ricevute_bancarie : Changed message string
  l10n_it_ricevute_bancarie/models/account.py
Labels: approved, bot is merging ⏳

#4648 [16.0] [IMP] l10n_it_riba: improve incasso flow with paid and past due management
  l10n_it_riba/models/riba_config.py
  l10n_it_riba/tests/riba_common.py
  l10n_it_riba/tests/test_riba.py
  l10n_it_riba/views/configuration_view.xml
  l10n_it_riba/views/riba_view.xml
  l10n_it_riba/views/wizard_past_due.xml
  l10n_it_riba/wizard/wizard_past_due.py
  l10n_it_riba/wizard/wizard_riba_multiple_payment.py
Labels: approved, ready to merge, merged 🎉

#4431 IMP l10n_it_account removing check_balance_sign_coherence.
  l10n_it_account/__init__.py
  l10n_it_account/migrations/16.0.1.0.0/post-migrate_balance_sign.py
  l10n_it_account/models/account_account.py
  l10n_it_account/models/account_group.py
  l10n_it_account/static/description/index.html
  l10n_it_account/tests/test_l10n_it_account.py
Labels: needs fixing, bot is merging ⏳, 16.0

#3917 [16.0] FIX l10n_it_withholding_tax when other localizations are installed
  l10n_it_withholding_tax/__manifest__.py
  l10n_it_withholding_tax/migrations/16.0.1.2.0/post-migrate.py
  l10n_it_withholding_tax/views/report_invoice.xml
Labels: bot is merging ⏳, 16.0

#4630 [16.0] [FIX] l10n_it_split_payment: fix invoice creation
  l10n_it_split_payment/models/account_move.py
  l10n_it_split_payment/models/account_move_line.py
Labels: bot is merging ⏳

#4693 [16.0][IMP]l10n_it_split_payment: Improved invoice report totals
  l10n_it_split_payment/README.rst
  l10n_it_split_payment/__manifest__.py
  l10n_it_split_payment/static/description/index.html
  l10n_it_split_payment/views/report_invoice.xml
Labels: bot is merging ⏳, 16.0, missing issue

#4038 [16.0] [IMP] account_vat_period_end_statement report avoiding generic e little significative term
  account_vat_period_end_statement/views/report_vatperiodendstatement.xml
Labels: bot is merging ⏳, missing issue

#3732 [16.0][FIX] l10n_it_financial_statements_report: use landscape format for PDF
  l10n_it_financial_statements_report/report/financial_statements_report.py
  l10n_it_financial_statements_report/report/reports.xml
Labels: bot is merging ⏳, hotfix, no stale, 16.0

#4660 [18.0] [MIG] l10n_it_bill_of_entry
  l10n_it_bill_of_entry/README.rst
  l10n_it_bill_of_entry/__init__.py
  l10n_it_bill_of_entry/__manifest__.py
  l10n_it_bill_of_entry/demo/bill_of_entry_demo.xml
  l10n_it_bill_of_entry/i18n/it.po
  l10n_it_bill_of_entry/i18n/l10n_it_bill_of_entry.pot
  l10n_it_bill_of_entry/models/__init__.py
  l10n_it_bill_of_entry/models/account_move.py
  l10n_it_bill_of_entry/models/company.py
  l10n_it_bill_of_entry/pyproject.toml
  l10n_it_bill_of_entry/readme/CONFIGURE.md
  l10n_it_bill_of_entry/readme/CONTRIBUTORS.md
  l10n_it_bill_of_entry/readme/DESCRIPTION.md
  l10n_it_bill_of_entry/readme/USAGE.md
  l10n_it_bill_of_entry/static/description/icon.png
  l10n_it_bill_of_entry/static/description/index.html
  l10n_it_bill_of_entry/tests/__init__.py
  l10n_it_bill_of_entry/tests/test_bill_of_entry.py
  l10n_it_bill_of_entry/views/account_invoice_view.xml
  l10n_it_bill_of_entry/views/company_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#4073 [16.0] [FIX] l10n_it_reverse_charge: refunds with rc_supplier_invoice
  l10n_it_reverse_charge/models/account_move.py
Labels: bot is merging ⏳, 16.0, missing issue

#4736 [14.0][FIX] l10n_it_fatturapa_out: not generate empty Causale
  l10n_it_fatturapa_out/wizard/efattura.py
Labels: approved, bot is merging ⏳

#4642 [14.0][IMP] l10n_it_ricevute_bancarie: aggiunta spesa incasso insoluto
  l10n_it_ricevute_bancarie/models/riba_config.py
  l10n_it_ricevute_bancarie/tests/test_riba.py
  l10n_it_ricevute_bancarie/views/configuration_view.xml
  l10n_it_ricevute_bancarie/views/wizard_unsolved.xml
  l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py
Labels: approved, bot is merging ⏳, 14.0

#4599 [14.0][IMP] l10n_it_delivery_note: better handling for _action_confirm
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, ready to merge, bot is merging ⏳

#4705 [14.0][IMP] account_vat_period_end_statement: Updated "Total Statement" label
  account_vat_period_end_statement/views/report_vatperiodendstatement.xml
Labels: approved, bot is merging ⏳
