Repository OCA/l10n-italy, pull requests merged in 2025-05, with the labels that each got.

#4724 [ADD] Mostrare gli importi senza ritenute nei report di MIS Builder
  l10n_it_withholding_tax_mis_builder/README.rst
  l10n_it_withholding_tax_mis_builder/__init__.py
  l10n_it_withholding_tax_mis_builder/__manifest__.py
  l10n_it_withholding_tax_mis_builder/i18n/it.po
  l10n_it_withholding_tax_mis_builder/init_hook.py
  l10n_it_withholding_tax_mis_builder/models/__init__.py
  l10n_it_withholding_tax_mis_builder/models/account_move_line.py
  l10n_it_withholding_tax_mis_builder/models/mis_report_instance.py
  l10n_it_withholding_tax_mis_builder/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax_mis_builder/readme/DESCRIPTION.rst
  l10n_it_withholding_tax_mis_builder/static/description/index.html
  l10n_it_withholding_tax_mis_builder/tests/__init__.py
  l10n_it_withholding_tax_mis_builder/tests/common.py
  l10n_it_withholding_tax_mis_builder/tests/test_report.py
  l10n_it_withholding_tax_mis_builder/views/account_move_line_view.xml
  l10n_it_withholding_tax_mis_builder_cash_flow/README.rst
  l10n_it_withholding_tax_mis_builder_cash_flow/__init__.py
  l10n_it_withholding_tax_mis_builder_cash_flow/__manifest__.py
  l10n_it_withholding_tax_mis_builder_cash_flow/i18n/it.po
  l10n_it_withholding_tax_mis_builder_cash_flow/readme/CONTRIBUTORS.rst
  l10n_it_withholding_tax_mis_builder_cash_flow/readme/DESCRIPTION.rst
  l10n_it_withholding_tax_mis_builder_cash_flow/report/__init__.py
  l10n_it_withholding_tax_mis_builder_cash_flow/report/mis_cash_flow.py
  l10n_it_withholding_tax_mis_builder_cash_flow/report/mis_cash_flow_views.xml
  l10n_it_withholding_tax_mis_builder_cash_flow/static/description/index.html
  l10n_it_withholding_tax_mis_builder_cash_flow/tests/__init__.py
  l10n_it_withholding_tax_mis_builder_cash_flow/tests/test_report.py
  setup/l10n_it_withholding_tax_mis_builder/odoo/addons/l10n_it_withholding_tax_mis_builder
  setup/l10n_it_withholding_tax_mis_builder/setup.py
  setup/l10n_it_withholding_tax_mis_builder_cash_flow/odoo/addons/l10n_it_withholding_tax_mis_builder_cash_flow
  setup/l10n_it_withholding_tax_mis_builder_cash_flow/setup.py
Labels: approved, ready to merge, bot is merging ⏳, new module

#4662 [IMP] l10n_it_fatturapa_in: Improved bank account creation in XML import
  l10n_it_fatturapa_in/tests/data/IT02780790107_11004_bank.xml
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#4667 [16.0] [FIX] l10n_it_bill_of_entry: fix storno reconciliation for multiple boes
  l10n_it_bill_of_entry/models/account_move.py
  l10n_it_bill_of_entry/tests/test_bill_of_entry.py
Labels: approved, ready to merge, bot is merging ⏳

#4715 [16.0][ADD]l10n_it_reverse_charge_start_end_dates: Added module
  l10n_it_reverse_charge_start_end_dates/README.rst
  l10n_it_reverse_charge_start_end_dates/__init__.py
  l10n_it_reverse_charge_start_end_dates/__manifest__.py
  l10n_it_reverse_charge_start_end_dates/models/__init__.py
  l10n_it_reverse_charge_start_end_dates/models/account_move.py
  l10n_it_reverse_charge_start_end_dates/pyproject.toml
  l10n_it_reverse_charge_start_end_dates/readme/CONTRIBUTORS.md
  l10n_it_reverse_charge_start_end_dates/readme/DESCRIPTION.md
  l10n_it_reverse_charge_start_end_dates/static/description/index.html
Labels: approved, bot is merging ⏳

#4738 [FIX]l10n_it_split_payment fix duplicate invoice when invoice have sp…
  l10n_it_split_payment/models/account_move.py
Labels: approved, bot is merging ⏳

#4756 [14.0][IMP]l10n_it_declaration_of_intent: add chatter
  l10n_it_declaration_of_intent/models/declaration.py
  l10n_it_declaration_of_intent/views/declaration_of_intent_view.xml
Labels: approved, bot is merging ⏳

#4681 [14.0][FIX] l10n_it_sdd_cbi: fix generate file with multi lines
  l10n_it_sdd_cbi/models/account_payment_order.py
Labels: approved, bot is merging ⏳, no issue needed

#4758 [14.0][FIX] l10n_it_reverse_charge: utilizzando il conto analitico su fattura che genera RC lo stesso viene indicato sia sulla fattura che su autofattura passiva generando un doppio movimento in analitica
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#4680 [ADD]l10n_it_edi_doi_extension: modulo per gestione dichiarazioni di intento emesse dall'azienda
  l10n_it_edi_doi_extension/README.rst
  l10n_it_edi_doi_extension/__init__.py
  l10n_it_edi_doi_extension/__manifest__.py
  l10n_it_edi_doi_extension/models/__init__.py
  l10n_it_edi_doi_extension/models/account_move.py
  l10n_it_edi_doi_extension/models/account_tax.py
  l10n_it_edi_doi_extension/models/declaration_of_intent.py
  l10n_it_edi_doi_extension/models/purchase_order.py
  l10n_it_edi_doi_extension/models/res_company.py
  l10n_it_edi_doi_extension/pyproject.toml
  l10n_it_edi_doi_extension/readme/CONTRIBUTORS.md
  l10n_it_edi_doi_extension/readme/DESCRIPTION.md
  l10n_it_edi_doi_extension/readme/USAGE.md
  l10n_it_edi_doi_extension/static/description/index.html
  l10n_it_edi_doi_extension/tests/__init__.py
  l10n_it_edi_doi_extension/tests/test_doi_issued_from_company.py
  l10n_it_edi_doi_extension/views/account_move_views.xml
  l10n_it_edi_doi_extension/views/l10n_it_edi_doi_declaration_of_intent_views.xml
  l10n_it_edi_doi_extension/views/purchase_order_views.xml
  l10n_it_edi_doi_extension/views/res_company.xml
Labels: bot is merging ⏳, new module, 18.0

#4699 [16.0][IMP] l10n_it_vat_registries: add XLSX report
  l10n_it_vat_registries/__manifest__.py
  l10n_it_vat_registries/report/reports.xml
  l10n_it_vat_registries/tests/test_registry.py
  l10n_it_vat_registries/wizard/__init__.py
  l10n_it_vat_registries/wizard/print_registro_iva.py
  l10n_it_vat_registries/wizard/print_registro_iva.xml
  l10n_it_vat_registries/wizard/report_registro_iva_xlsx.py
  l10n_it_vat_settlement_date/__init__.py
  l10n_it_vat_settlement_date/wizard/__init__.py
  l10n_it_vat_settlement_date/wizard/report_registro_iva_xlsx.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#4601 [16.0][IMP] l10n_it_delivery_note: better handling for _action_confirm
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳, is porting

#4489 [FIX] l10n_it_delivery_note: check only on incoming picking presence to avoid DN invoicing
  l10n_it_delivery_note/models/stock_delivery_note.py
Labels: approved, bot is merging ⏳

#4765 [14.0][FIX] l10n_it_reverse_charge: refunds with rc_supplier_invoice
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳

#4155 [16.0] [FIX] l10n_it_reverse_charge: disable possible link with purchase order line, because self invoice must not be linked to purchase order
  l10n_it_reverse_charge/models/account_move.py
Labels: approved, bot is merging ⏳, needs functional review, 16.0

#4766 [14.0][IMP] Calcolo ammortamenti mensili per simulazione bilanci
  assets_management/README.rst
  assets_management/data/asset_data.xml
  assets_management/models/account_fiscal_year.py
  assets_management/models/asset_depreciation.py
  assets_management/models/asset_depreciation_line.py
  assets_management/models/asset_depreciation_mode_line.py
  assets_management/static/description/index.html
  assets_management/tests/test_assets_management.py
  assets_management/views/asset_depreciation_mode.xml
  assets_management/wizard/asset_generate_depreciation.py
  assets_management/wizard/asset_generate_depreciation_view.xml
  l10n_it_asset_management/migrations/16.0.1.1.0/pre-migrate.py
Labels: approved, bot is merging ⏳

#4768 [FIX] Precisione decimale non usata durante l'importazione della fattura elettronica
  l10n_it_fatturapa_in/__init__.py
  l10n_it_fatturapa_in/fields.py
  l10n_it_fatturapa_in/models/attachment.py
  l10n_it_fatturapa_in/tests/data/IT01234567890_FPR16.xml
  l10n_it_fatturapa_in/tests/fatturapa_common.py
  l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
  l10n_it_fatturapa_pec/models/mail_thread.py
Labels: approved, bot is merging ⏳

#4687 [16.0][IMP] l10n_it_fatturapa_in: create partner with company on import
  l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
Labels: approved, ready to merge, bot is merging ⏳

#4491 18.0 mig l10n it central journal reportlab
  l10n_it_central_journal_reportlab/README.rst
  l10n_it_central_journal_reportlab/__init__.py
  l10n_it_central_journal_reportlab/__manifest__.py
  l10n_it_central_journal_reportlab/i18n/it.po
  l10n_it_central_journal_reportlab/i18n/l10n_it_central_journal_reportlab.pot
  l10n_it_central_journal_reportlab/models/__init__.py
  l10n_it_central_journal_reportlab/models/account.py
  l10n_it_central_journal_reportlab/pyproject.toml
  l10n_it_central_journal_reportlab/readme/CONTRIBUTORS.md
  l10n_it_central_journal_reportlab/readme/DESCRIPTION.md
  l10n_it_central_journal_reportlab/security/ir.model.access.csv
  l10n_it_central_journal_reportlab/static/description/icon.png
  l10n_it_central_journal_reportlab/static/description/index.html
  l10n_it_central_journal_reportlab/tests/__init__.py
  l10n_it_central_journal_reportlab/tests/test_central_journal_reportlab.py
  l10n_it_central_journal_reportlab/views/date_range_view.xml
  l10n_it_central_journal_reportlab/wizard/__init__.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.py
  l10n_it_central_journal_reportlab/wizard/print_giornale.xml
Labels: migration, bot is merging ⏳, 18.0

#4700 [FIX] l10n_it_fatturapa_pec: avoid changing email on user when testing smtp connection
  l10n_it_fatturapa_pec/models/ir_mail_server.py
Labels: approved, bot is merging ⏳, 16.0
