Repository OCA/l10n-italy, pull requests merged in 2025-08, with the labels that each got.

#4872 Ottimizzazione resoconto previsionale cespiti
  assets_management/report/asset_previsional.py
  assets_management/report/templates/asset_previsional.xml
Labels: approved, bot is merging ⏳

#4866 [FIX] l10n_it_account_stamp: use right migration function's signature
  l10n_it_account_stamp/migrations/18.0.1.0.0/post-migration.py
  l10n_it_account_stamp/migrations/18.0.1.0.0/pre-migration.py
Labels: approved, ready to merge, bot is merging ⏳

#4867 [FIX] l10n_it_account_vat_period_end_settlement: fix migration script
  l10n_it_account_vat_period_end_settlement/migrations/18.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳

#4888 [14.0][FIX] l10n_it_appointment_code force pip creation
  l10n_it_appointment_code/__manifest__.py
  l10n_it_appointment_code/static/description/index.html
Labels: bot is merging ⏳

#4868 [FIX] l10n_it_vat_settlement_communication: fix migration script
  l10n_it_vat_settlement_communication/migrations/18.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳
