Repository OCA/l10n-italy, pull requests merged in 2025-02, with the labels that each got.

#4615 [14.0][IMP] l10n_it_delivery_note: refactor delivery note creation by extracting value preparation into a separate method to allow inheriting
  l10n_it_delivery_note/models/stock_picking.py
Labels: approved, bot is merging ⏳

#4619 [14.0][FIX] l10n_it_fatturapa: added mail.activity.mixin inheritance
  l10n_it_fatturapa/models/ir_attachment.py
Labels: approved, bot is merging ⏳

#4480 [14.0][ADD] l10n_it_sdd_cbi: adding module for CBI SDD Italy
  l10n_it_sdd_cbi/README.rst
  l10n_it_sdd_cbi/__init__.py
  l10n_it_sdd_cbi/__manifest__.py
  l10n_it_sdd_cbi/data/CBIBdySDDReq.00.01.00.xsd
  l10n_it_sdd_cbi/data/CBIBdySDDReq.00.01.01.xsd
  l10n_it_sdd_cbi/data/CBISDDReqLogMsg.00.01.00.xsd
  l10n_it_sdd_cbi/data/CBISDDReqLogMsg.00.01.01.xsd
  l10n_it_sdd_cbi/data/account_payment_method.xml
  l10n_it_sdd_cbi/models/__init__.py
  l10n_it_sdd_cbi/models/account_payment_line.py
  l10n_it_sdd_cbi/models/account_payment_method.py
  l10n_it_sdd_cbi/models/account_payment_order.py
  l10n_it_sdd_cbi/models/res_company.py
  l10n_it_sdd_cbi/models/res_config_settings.py
  l10n_it_sdd_cbi/post_install.py
  l10n_it_sdd_cbi/readme/CONTRIBUTORS.rst
  l10n_it_sdd_cbi/readme/DESCRIPTION.rst
  l10n_it_sdd_cbi/static/description/icon.png
  l10n_it_sdd_cbi/static/description/index.html
  l10n_it_sdd_cbi/views/account_payment_order_view.xml
  l10n_it_sdd_cbi/views/res_config_settings_view.xml
  setup/l10n_it_sdd_cbi/odoo/addons/l10n_it_sdd_cbi
  setup/l10n_it_sdd_cbi/setup.py
Labels: approved, bot is merging ⏳, 14.0, new module

#4529 [16.0] [FIX] l10n_it_account_stamp: messaggio errato dopo applicazione bollo + reimposta a bozza modifica l'addebito del bollo
  l10n_it_account_stamp/README.rst
  l10n_it_account_stamp/__manifest__.py
  l10n_it_account_stamp/migrations/16.0.1.2.0/post-migration.py
  l10n_it_account_stamp/models/account_move.py
  l10n_it_account_stamp/static/description/index.html
  l10n_it_account_stamp/tests/test_account_stamp_invoicing.py
  l10n_it_account_stamp/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳, hotfix, no stale, 16.0

#4614 [FIX]14.0 l10n_it_vat_registries fix issue 4612
  l10n_it_vat_registries/wizard/print_registro_iva.py
Labels: approved, ready to merge, bot is merging ⏳

#4613 16.0 fix issue4612
  l10n_it_vat_registries/wizard/print_registro_iva.py
Labels: approved, ready to merge, bot is merging ⏳
